import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useTranslations } from 'next-intl';
import { Dialog, DialogContent, Input, Label } from '@workspace/ui';
import type { WorkspacePriority, WorkspaceWorkflowStatus, WorkspaceLabel } from '@/shared/types/domain';
import {
  BaseBranchField,
  CreateWorkspaceFooter,
  CreateWorkspaceHeader,
  GithubLinkImportSection,
  ProjectSelectField,
  WorkspaceBranchField,
} from '@/features/workspace/components/CreateWorkspaceDialogParts';
import {
  IssueLinkPanel,
  PrLinkPanel,
} from '@/features/workspace/components/CreateWorkspaceDialogGithubPanels';
import type { RepoContext } from '@/features/workspace/components/CreateWorkspaceDialogTypes';
import { useProjectStore } from '@/features/project/store/use-project-store';
import {
  useProjects,
  useWorkspaceLabels,
} from '@/features/project/hooks/use-project-bootstrap-query';
import {
  gitApi,
  llmProvidersApi,
  type GithubIssuePayload,
  type GithubPrPayload,
  wsScriptApi,
  wsGithubApi,
} from '@/api/ws-api';
import { useContextParams } from '@/shared/hooks/use-context-params';
import {
  getWorkspaceCreateOriginKey,
  useWorkspaceCreationStore,
} from '@/features/workspace/store/workspace-creation-store';
import {
  ISSUE_CACHE_TTL_MS,
  issueListCache,
  issueToBranchName,
  issueToWorkspaceName,
  isAutoGeneratedBranchConflictError,
  isBranchConflictError,
  prToWorkspaceName,
  regeneratePokemonSuffixBranch,
  resolveWorkspaceIssueTodoProvider,
  sanitizeCreateWorkspaceErrorMessage,
} from '@/features/welcome/lib/welcome-page-helpers';
import {
  useRepoPrListQuery,
  useInvalidateGithubPrs,
} from '@/features/github/hooks/use-github-pr-query';
import { setWorkspaceGitignoreDirsMessages } from '@/features/workspace/store/workspace-gitignore-dirs-store';

interface CreateWorkspaceDialogProps {
  isOpen: boolean;
  onClose: () => void;
  defaultProjectId?: string;
  defaultWorkflowStatus?: WorkspaceWorkflowStatus;
  projectSelectionInHeader?: boolean;
  requireProjectSelection?: boolean;
  // Build from Issue Only mode
  preselectedIssue?: GithubIssuePayload;
  sourceWorkspaceId?: string;
}

export const CreateWorkspaceDialog: React.FC<CreateWorkspaceDialogProps> = ({
  isOpen,
  onClose,
  defaultProjectId,
  defaultWorkflowStatus,
  projectSelectionInHeader = false,
  requireProjectSelection = false,
  preselectedIssue,
}: CreateWorkspaceDialogProps) => {
  const t = useTranslations('Workspace.components');
  const { currentView, workspaceId: currentWorkspaceId, projectId: currentProjectId } = useContextParams();
  const projects = useProjects();
  const addWorkspace = useProjectStore((s) => s.addWorkspace);
  const startCreating = useWorkspaceCreationStore((s) => s.startCreating);
  const bindWorkspace = useWorkspaceCreationStore((s) => s.bindWorkspace);
  const failCreating = useWorkspaceCreationStore((s) => s.failCreating);

  const [projectId, setProjectId] = useState(() => {
    if (defaultProjectId) return defaultProjectId;
    if (requireProjectSelection) return '';
    return projects.length > 0 ? projects[0].id : '';
  });
  const [name, setName] = useState('');
  const [branch, setBranch] = useState('');
  const [baseBranch, setBaseBranch] = useState('main');
  const [remoteBranches, setRemoteBranches] = useState<string[]>([]);
  const [baseBranchFilter, setBaseBranchFilter] = useState('');
  const [isBaseBranchOpen, setIsBaseBranchOpen] = useState(false);
  const [issueUrl, setIssueUrl] = useState('');
  const [selectedIssueNumber, setSelectedIssueNumber] = useState<string>('');
  const [issuePreview, setIssuePreview] = useState<GithubIssuePayload | null>(null);
  const [issues, setIssues] = useState<GithubIssuePayload[]>([]);
  const [prUrl, setPrUrl] = useState('');
  const [selectedPrNumber, setSelectedPrNumber] = useState<string>('');
  const [prPreview, setPrPreview] = useState<GithubPrPayload | null>(null);
  const [localPrError, setLocalPrError] = useState<string | null>(null);
  const [isPrPreviewLoading, setIsPrPreviewLoading] = useState(false);
  const [repoContext, setRepoContext] = useState<RepoContext | null>(null);

  const prListQuery = useRepoPrListQuery({
    owner: repoContext?.owner ?? '',
    repo: repoContext?.repo ?? '',
    enabled: Boolean(repoContext?.owner && repoContext?.repo),
  });
  const invalidateGithubPrs = useInvalidateGithubPrs();
  const prs = prListQuery.data ?? [];
  const isPrsLoading = Boolean(repoContext) && prListQuery.isFetching;
  const prError =
    localPrError ??
    (prListQuery.error instanceof Error
      ? prListQuery.error.message
      : prListQuery.error
        ? t('createDialog.pr.errors.failedToLoadPrs')
        : null);
  const [isRepoLoading, setIsRepoLoading] = useState(false);
  const [isBaseBranchesLoading, setIsBaseBranchesLoading] = useState(false);
  const [isIssuesLoading, setIsIssuesLoading] = useState(false);
  const [isIssuePreviewLoading, setIsIssuePreviewLoading] = useState(false);
  const [isLlmRoutingLoading, setIsLlmRoutingLoading] = useState(false);
  const [hasSetupScript, setHasSetupScript] = useState(false);
  const [issueError, setIssueError] = useState<string | null>(null);
  const [branchError, setBranchError] = useState<string | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [autoExtractTodos, setAutoExtractTodos] = useState(false);
  const [autoExtractTodosPr, setAutoExtractTodosPr] = useState(false);
  const [linkType, setLinkType] = useState<'none' | 'issue' | 'pr'>('none');
  const [displayedLinkType, setDisplayedLinkType] = useState<'issue' | 'pr'>('issue');
  useEffect(() => {
    if (linkType !== 'none') setDisplayedLinkType(linkType);
  }, [linkType]);
  const [todoProviderLabel, setTodoProviderLabel] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Metadata states - defaults: no_priority, in_progress, empty labels
  const [priority, setPriority] = useState<WorkspacePriority>('no_priority');
  const [workflowStatus, setWorkflowStatus] = useState<WorkspaceWorkflowStatus>(
    defaultWorkflowStatus ?? 'in_progress',
  );
  const [selectedLabels, setSelectedLabels] = useState<WorkspaceLabel[]>([]);

  const workspaceLabels = useWorkspaceLabels();
  const createWorkspaceLabel = useProjectStore(s => s.createWorkspaceLabel);

  const nameTouchedRef = useRef(false);
  const branchTouchedRef = useRef(false);
  const generatedBranchRef = useRef<string | null>(null);
  const branchFieldRef = useRef<HTMLDivElement | null>(null);
  const branchInputRef = useRef<HTMLInputElement | null>(null);
  const repoContextErrorTextRef = useRef({
    failedToLoadPrs: t('createDialog.pr.errors.failedToLoadPrs'),
    failedToLoadIssues: t('createDialog.issue.errors.failedToLoadIssues'),
  });

  useEffect(() => {
    setWorkspaceGitignoreDirsMessages({
      settingsSyncFailedTitle: t('gitignoreStore.settingsSyncFailedTitle'),
      invalidPathTitle: t('gitignoreStore.invalidPathTitle'),
      invalidPathDescription: t('gitignoreStore.invalidPathDescription'),
      failedMasterSwitch: t('gitignoreStore.failedMasterSwitch'),
      failedStrategy: t('gitignoreStore.failedStrategy'),
      failedAddCustom: t('gitignoreStore.failedAddCustom'),
      failedRemoveDirectory: t('gitignoreStore.failedRemoveDirectory'),
      failedUpdatePath: t('gitignoreStore.failedUpdatePath'),
    });
  }, [t]);

  useEffect(() => {
    repoContextErrorTextRef.current = {
      failedToLoadPrs: t('createDialog.pr.errors.failedToLoadPrs'),
      failedToLoadIssues: t('createDialog.issue.errors.failedToLoadIssues'),
    };
  }, [t]);

  const selectedProject = useMemo(
    () => projects.find((project) => project.id === projectId) ?? null,
    [projectId, projects],
  );
  const selectedProjectId = selectedProject?.id ?? null;
  const selectedProjectPath = selectedProject?.mainFilePath ?? null;

  useEffect(() => {
    if (defaultProjectId) {
      setProjectId(defaultProjectId);
      return;
    }

    if (!projectId && projects.length > 0 && !requireProjectSelection) {
      setProjectId(projects[0].id);
    }
  }, [defaultProjectId, projectId, projects, requireProjectSelection]);

  useEffect(() => {
    if (!isOpen) return;
    setWorkflowStatus(defaultWorkflowStatus ?? 'in_progress');
  }, [defaultWorkflowStatus, isOpen]);

  // Reset only when the dialog closes — do not depend on `projects` identity
  // (useProjects can return a fresh `[]` while loading and would loop forever).
  const wasOpenRef = useRef(isOpen);
  useEffect(() => {
    const wasOpen = wasOpenRef.current;
    wasOpenRef.current = isOpen;
    if (!wasOpen || isOpen) {
      return;
    }

    setProjectId(
      defaultProjectId || (!requireProjectSelection && projects.length > 0 ? projects[0].id : ''),
    );
    setName('');
    setBranch('');
    setBaseBranch('main');
    setRemoteBranches([]);
    setBaseBranchFilter('');
    setIsBaseBranchOpen(false);
    setIssueUrl('');
    setSelectedIssueNumber('');
    setIssuePreview(null);
    setIssues([]);
    setPrUrl('');
    setSelectedPrNumber('');
    setPrPreview(null);
    setLocalPrError(null);
    setIsPrPreviewLoading(false);
    setIsRepoLoading(false);
    setIsBaseBranchesLoading(false);
    setIsIssuesLoading(false);
    setIsIssuePreviewLoading(false);
    setIsLlmRoutingLoading(false);
    setHasSetupScript(false);
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);
    setAutoExtractTodos(false);
    setAutoExtractTodosPr(false);
    setLinkType('none');
    setDisplayedLinkType('issue');
    setTodoProviderLabel(null);
    setIsSubmitting(false);
    setPriority('no_priority');
    setWorkflowStatus(defaultWorkflowStatus ?? 'in_progress');
    setSelectedLabels([]);
    // Reset refs
    nameTouchedRef.current = false;
    branchTouchedRef.current = false;
    generatedBranchRef.current = null;
  }, [defaultProjectId, defaultWorkflowStatus, isOpen, projects, requireProjectSelection]);

  // Handle preselectedIssue for Build from Issue Only mode
  useEffect(() => {
    if (isOpen && preselectedIssue) {
      setIssuePreview(preselectedIssue);
      setIssueUrl(preselectedIssue.url);
      setSelectedIssueNumber(preselectedIssue.number.toString());
      setLinkType('issue');
      setDisplayedLinkType('issue');
      // Auto-fill workspace name and branch from issue
      const workspaceName = issueToWorkspaceName(preselectedIssue);
      const branchName = issueToBranchName(preselectedIssue);
      setName(workspaceName);
      setBranch(branchName);
    }
  }, [isOpen, preselectedIssue]);

  useEffect(() => {
    let cancelled = false;

    async function loadLlmRouting() {
      if (!isOpen) {
        return;
      }

      setIsLlmRoutingLoading(true);
      try {
        const config = await llmProvidersApi.get();
        if (cancelled) return;

        const provider = resolveWorkspaceIssueTodoProvider(config);
        setTodoProviderLabel(provider?.label ?? null);
      } catch {
        if (!cancelled) {
          setTodoProviderLabel(null);
        }
      } finally {
        if (!cancelled) {
          setIsLlmRoutingLoading(false);
        }
      }
    }

    loadLlmRouting();
    return () => {
      cancelled = true;
    };
  }, [isOpen]);

  useEffect(() => {
    let cancelled = false;

    async function loadRepoContext() {
      if (!isOpen || !selectedProjectId || !selectedProjectPath) {
        return;
      }

      setIsRepoLoading(true);
      setIsBaseBranchesLoading(true);
      setIssueError(null);
      setRepoContext(null);
      setRemoteBranches([]);
      setIssues([]);
      if (!preselectedIssue) {
        setIssuePreview(null);
        setSelectedIssueNumber('');
        setIssueUrl('');
      }
      setPrPreview(null);
      setSelectedPrNumber('');
      setPrUrl('');
      setLocalPrError(null);
      if (!preselectedIssue) {
        setLinkType('none');
      }
      setAutoExtractTodos(false);
      setAutoExtractTodosPr(false);
      setHasSetupScript(false);

      try {
        const fetchedRemoteBranches = await gitApi.listRemoteBranches(selectedProjectPath);
        if (!cancelled) {
          const nextRemoteBranches = fetchedRemoteBranches.sort();
          setRemoteBranches(nextRemoteBranches);
          if (nextRemoteBranches.includes('main')) {
            setBaseBranch('main');
          } else if (nextRemoteBranches.length > 0) {
            setBaseBranch(nextRemoteBranches[0]);
          } else {
            setBaseBranch('main');
          }
        }

        const { scripts } = await wsScriptApi.get(selectedProjectId);
        if (!cancelled) {
          setHasSetupScript(
            typeof scripts.setup === 'string' && scripts.setup.trim().length > 0,
          );
        }

        const status = await gitApi.getStatus(selectedProjectPath);
        if (cancelled) return;

        if (status.github_owner && status.github_repo) {
          const nextContext = {
            owner: status.github_owner,
            repo: status.github_repo,
          };
          setRepoContext(nextContext);

          const cacheKey = `${nextContext.owner}/${nextContext.repo}`;
          const cachedIssues = issueListCache.get(cacheKey);
          if (cachedIssues && cachedIssues.expiresAt > Date.now()) {
            setIssues(cachedIssues.issues);
          } else {
            setIsIssuesLoading(true);
            const fetchedIssues = await wsGithubApi.listIssues(nextContext);
            if (cancelled) return;
            setIssues(fetchedIssues);
            issueListCache.set(cacheKey, {
              expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
              issues: fetchedIssues,
            });
          }

          // PR list is now owned by TanStack Query (prListQuery above).
          // Setting repoContext enables the query which fetches automatically.
        }
      } catch (error) {
        if (!cancelled) {
          setIssueError(error instanceof Error ? error.message : repoContextErrorTextRef.current.failedToLoadIssues);
        }
      } finally {
        if (!cancelled) {
          setIsRepoLoading(false);
          setIsBaseBranchesLoading(false);
          setIsIssuesLoading(false);
        }
      }
    }

    loadRepoContext();
    return () => {
      cancelled = true;
    };
  }, [isOpen, preselectedIssue, selectedProjectId, selectedProjectPath]);

  useEffect(() => {
    if (!issuePreview) {
      if (!prPreview) {
        generatedBranchRef.current = null;
      }
      return;
    }

    if (!nameTouchedRef.current) {
      setName(issueToWorkspaceName(issuePreview));
    }
    if (!branchTouchedRef.current) {
      const generated = issueToBranchName(issuePreview);
      generatedBranchRef.current = generated;
      setBranch(generated);
    }
  }, [issuePreview, prPreview]);

  useEffect(() => {
    if (!prPreview) return;

    if (!nameTouchedRef.current) {
      setName(prToWorkspaceName(prPreview));
    }
    setBranch(prPreview.head_ref);
    if (prPreview.base_ref) {
      setBaseBranch(prPreview.base_ref);
    }
  }, [prPreview]);

  useEffect(() => {
    if (!issuePreview || !todoProviderLabel) setAutoExtractTodos(false);
  }, [issuePreview, todoProviderLabel]);

  useEffect(() => {
    if (!prPreview || !todoProviderLabel) setAutoExtractTodosPr(false);
  }, [prPreview, todoProviderLabel]);

  const clearPrSelection = () => {
    setPrPreview(null);
    setSelectedPrNumber('');
    setPrUrl('');
    setLocalPrError(null);
    setAutoExtractTodosPr(false);
  };

  const clearIssueSelection = () => {
    setIssuePreview(null);
    setSelectedIssueNumber('');
    setIssueUrl('');
    setIssueError(null);
    setAutoExtractTodos(false);
  };

  const handleSelectLinkType = (next: 'issue' | 'pr') => {
    if (preselectedIssue) {
      return;
    }

    if (linkType === next) {
      setLinkType('none');
      if (next === 'issue') clearIssueSelection();
      else clearPrSelection();
      return;
    }
    setLinkType(next);
    if (next === 'issue') clearPrSelection();
    else clearIssueSelection();
  };

  const handleSelectIssue = async (value: string) => {
    setSelectedIssueNumber(value);
    setIssueUrl('');
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);

    const selected = issues.find((issue) => String(issue.number) === value) ?? null;
    setIssuePreview(selected);
    clearPrSelection();
  };

  const handleSelectPr = (value: string) => {
    setSelectedPrNumber(value);
    setPrUrl('');
    setLocalPrError(null);
    setBranchError(null);
    setSubmitError(null);
    const selected = prs.find((pr) => String(pr.number) === value) ?? null;
    setPrPreview(selected);
    clearIssueSelection();
  };

  const handleLoadPrFromUrl = async () => {
    if (!prUrl.trim()) {
      setLocalPrError(null);
      return;
    }
    setIsPrPreviewLoading(true);
    setLocalPrError(null);
    setBranchError(null);
    setSubmitError(null);
    setSelectedPrNumber('');
    try {
      const preview = await wsGithubApi.getPr({ prUrl: prUrl.trim() });
      const currentRepo = repoContext ? `${repoContext.owner}/${repoContext.repo}` : null;
      const previewRepo = `${preview.owner}/${preview.repo}`;
      if (currentRepo && currentRepo !== previewRepo) {
        setPrPreview(null);
        setLocalPrError(t('createDialog.pr.errors.repoMismatch', { previewRepo, currentRepo }));
        return;
      }
      setPrPreview(preview);
      clearIssueSelection();
    } catch (error) {
      setPrPreview(null);
      setLocalPrError(error instanceof Error ? error.message : t('createDialog.pr.errors.failedToLoadPreview'));
    } finally {
      setIsPrPreviewLoading(false);
    }
  };

  const handleRefreshPrs = () => {
    if (!repoContext) return;
    setLocalPrError(null);
    invalidateGithubPrs({ owner: repoContext.owner, repo: repoContext.repo });
  };

  const handleLoadIssueFromUrl = async () => {
    if (!issueUrl.trim()) {
      setIssueError(null);
      return;
    }

    setIsIssuePreviewLoading(true);
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);
    setSelectedIssueNumber('');

    try {
      const preview = await wsGithubApi.getIssue({ issueUrl: issueUrl.trim() });
      const currentRepo = repoContext ? `${repoContext.owner}/${repoContext.repo}` : null;
      const previewRepo = `${preview.owner}/${preview.repo}`;

      if (currentRepo && currentRepo !== previewRepo) {
        setIssuePreview(null);
        setIssueError(t('createDialog.issue.errors.repoMismatch', { previewRepo, currentRepo }));
        return;
      }

      setIssuePreview(preview);
      clearPrSelection();
    } catch (error) {
      setIssuePreview(null);
      setIssueError(error instanceof Error ? error.message : t('createDialog.issue.errors.failedToLoadPreview'));
    } finally {
      setIsIssuePreviewLoading(false);
    }
  };

  const handleRefreshIssues = async () => {
    if (!repoContext) return;
    setIsIssuesLoading(true);
    setIssueError(null);
    try {
      const cacheKey = `${repoContext.owner}/${repoContext.repo}`;
      issueListCache.delete(cacheKey);
      const fetchedIssues = await wsGithubApi.listIssues(repoContext);
      setIssues(fetchedIssues);
      issueListCache.set(cacheKey, {
        expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
        issues: fetchedIssues,
      });
    } catch (error) {
      setIssueError(error instanceof Error ? error.message : t('createDialog.issue.errors.failedToRefreshIssues'));
    } finally {
      setIsIssuesLoading(false);
    }
  };

  const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    nameTouchedRef.current = true;
    setBranchError(null);
    setSubmitError(null);
    setName(event.target.value);
  };

  const handleBranchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    branchTouchedRef.current = true;
    setBranchError(null);
    setSubmitError(null);
    setBranch(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!projectId) return;

    let keepGlobalLoading = false;
    setIsSubmitting(true);
    setBranchError(null);
    setSubmitError(null);
    const originKey = getWorkspaceCreateOriginKey({
      currentView,
      workspaceId: currentWorkspaceId,
      projectId: currentProjectId,
    });
    const jobId = startCreating({
      originKey,
      label: name.trim() || null,
    });
    try {
      const finalDisplayName = prPreview
        ? name.trim() || prToWorkspaceName(prPreview)
        : name.trim() || (issuePreview ? issueToWorkspaceName(issuePreview) : '');
      const finalBranch = prPreview
        ? prPreview.head_ref
        : branch.trim() ||
          (!branchTouchedRef.current && generatedBranchRef.current) ||
          (issuePreview ? issueToBranchName(issuePreview) : '');
      const finalBaseBranch = prPreview ? prPreview.base_ref || baseBranch : baseBranch;

      // Create labels from GitHub issue/PR if present
      let labelsToUse = selectedLabels;
      if (prPreview && prPreview.labels && prPreview.labels.length > 0) {
        const source = 'gitHub_pr' as const;
        for (const prLabel of prPreview.labels) {
          // Check if label already exists with same name (case-insensitive) and source
          const existingLabel = workspaceLabels.find(
            (l) => l.name.toLowerCase() === prLabel.name.toLowerCase() && l.source === source
          );
          if (!existingLabel) {
            const newLabel = await createWorkspaceLabel({
              name: prLabel.name,
              color: prLabel.color ? `#${prLabel.color.replace(/^#/, '')}` : '#94a3b8',
              source,
            });
            labelsToUse = [...labelsToUse, newLabel];
          } else if (!labelsToUse.find((l) => l.id === existingLabel.id)) {
            labelsToUse = [...labelsToUse, existingLabel];
          }
        }
      } else if (issuePreview && issuePreview.labels && issuePreview.labels.length > 0) {
        const source = 'gitHub_issue' as const;
        for (const issueLabel of issuePreview.labels) {
          // Check if label already exists with same name (case-insensitive) and source
          const existingLabel = workspaceLabels.find(
            (l) => l.name.toLowerCase() === issueLabel.name.toLowerCase() && l.source === source
          );
          if (!existingLabel) {
            const newLabel = await createWorkspaceLabel({
              name: issueLabel.name,
              color: issueLabel.color ? `#${issueLabel.color.replace(/^#/, '')}` : '#94a3b8',
              source,
            });
            labelsToUse = [...labelsToUse, newLabel];
          } else if (!labelsToUse.find((l) => l.id === existingLabel.id)) {
            labelsToUse = [...labelsToUse, existingLabel];
          }
        }
      }

      const workspaceId = await addWorkspace({
        projectId,
        name: finalBranch,
        displayName: finalDisplayName || null,
        branch: finalBranch,
        baseBranch: finalBaseBranch,
        initialRequirement: null,
        githubIssue: prPreview ? null : issuePreview,
        githubPr: prPreview,
        autoExtractTodos:
          !!todoProviderLabel &&
          ((prPreview && autoExtractTodosPr) || (!prPreview && !!issuePreview && autoExtractTodos)),
        hasSetupScript,
        priority,
        workflowStatus,
        labels: labelsToUse,
      });
      keepGlobalLoading = true;
      bindWorkspace(jobId, workspaceId, finalDisplayName || null);
      onClose();
    } catch (error) {
      failCreating(jobId);
      const message = sanitizeCreateWorkspaceErrorMessage(
        error instanceof Error ? error.message : t('createDialog.errors.failedToCreateWorkspace'),
      );

      if (isBranchConflictError(message)) {
        setBranchError(message);
        requestAnimationFrame(() => {
          branchFieldRef.current?.scrollIntoView({
            behavior: 'smooth',
            block: 'center',
          });
          branchInputRef.current?.focus();
        });
      } else {
        setSubmitError(message);
      }
    } finally {
      if (!keepGlobalLoading) {
        setIsSubmitting(false);
      }
    }
  };

  const handleRegenerateBranch = () => {
    const nextBranch = regeneratePokemonSuffixBranch(branch, issuePreview?.number);
    branchTouchedRef.current = true;
    setBranch(nextBranch);
    setBranchError(null);
    setSubmitError(null);
    requestAnimationFrame(() => {
      branchInputRef.current?.focus();
    });
  };

  const repoLabel = repoContext ? `${repoContext.owner}/${repoContext.repo}` : t('createDialog.repo.noGithubRepository');
  const issueBodyPreview = issuePreview?.body?.trim() || t('createDialog.issue.noDescription');
  const canAutoExtractTodosIssue = !!issuePreview && !!todoProviderLabel && !isLlmRoutingLoading;
  const canAutoExtractTodosPr = !!prPreview && !!todoProviderLabel && !isLlmRoutingLoading;
  const filteredRemoteBranches = useMemo(
    () => remoteBranches.filter((remoteBranch) =>
      remoteBranch.toLowerCase().includes(baseBranchFilter.trim().toLowerCase()),
    ),
    [remoteBranches, baseBranchFilter],
  );
  const buildAutoExtractDescription = (kind: 'issue' | 'pr') => {
    const hasPreview = kind === 'issue' ? !!issuePreview : !!prPreview;
    if (!hasPreview) return t('createDialog.autoExtract.importFirst', {
      kind: kind === 'pr' ? t('createDialog.common.pr') : t('createDialog.common.issue'),
    });
    if (isLlmRoutingLoading) return t('createDialog.autoExtract.checkingRouting');
    if (todoProviderLabel)
      return t('createDialog.autoExtract.usesProvider', {
        provider: todoProviderLabel,
        kind: kind === 'pr' ? t('createDialog.common.pr') : t('createDialog.common.issue'),
      });
    return t('createDialog.autoExtract.configureRouting');
  };
  const autoExtractDescriptionIssue = buildAutoExtractDescription('issue');
  const autoExtractDescriptionPr = buildAutoExtractDescription('pr');
  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[720px] max-h-[80vh] overflow-y-auto [scrollbar-gutter:stable] gap-4 bg-background p-6 pt-7">
        <CreateWorkspaceHeader
          isBuildFromIssue={!!preselectedIssue}
          projectSelectionInHeader={projectSelectionInHeader}
          selectedProjectName={selectedProject?.name ?? null}
          isRepoLoading={isRepoLoading}
          repoLabel={repoLabel}
        />
        <div className="-mx-6 border-b border-border/60" />

        <form onSubmit={handleSubmit} className="flex flex-col">
          <div className="pr-1 pt-2 space-y-5">
            {!defaultProjectId && projectSelectionInHeader && (
              <ProjectSelectField
                id="project-inline"
                label={t('createDialog.fields.project')}
                placeholder={t('createDialog.projectSelect.pleaseSelectProject')}
                value={projectId}
                projects={projects}
                onChange={setProjectId}
                requireSelectionMessage={t('createDialog.projectSelect.requireSelectionMessage')}
              />
            )}

            {!defaultProjectId && !projectSelectionInHeader && (
              <ProjectSelectField
                id="project"
                label={t('createDialog.fields.project')}
                placeholder={t('createDialog.projectSelect.selectProject')}
                value={projectId}
                projects={projects}
                onChange={setProjectId}
                disabled={!!defaultProjectId}
              />
            )}

            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="workspace-name">{t('createDialog.fields.name')}</Label>
                <Input
                  id="workspace-name"
                  value={name}
                  onChange={handleNameChange}
                  placeholder={t('createDialog.name.placeholder')}
                  autoFocus
                />
                <p className="text-xs text-muted-foreground">
                  {t('createDialog.name.help')}
                </p>
              </div>

              <BaseBranchField
                baseBranch={baseBranch}
                isOpen={isBaseBranchOpen}
                isLoading={isBaseBranchesLoading}
                remoteBranches={remoteBranches}
                branchFilter={baseBranchFilter}
                filteredRemoteBranches={filteredRemoteBranches}
                selectedProjectId={selectedProjectId}
                onOpenChange={(open) => {
                  setIsBaseBranchOpen(open);
                  if (open) setBaseBranchFilter('');
                }}
                onFilterChange={setBaseBranchFilter}
                onSelectBranch={setBaseBranch}
              />

              <WorkspaceBranchField
                branchFieldRef={branchFieldRef}
                branchInputRef={branchInputRef}
                branch={branch}
                branchError={branchError}
                canRegenerateBranch={!!branchError && isAutoGeneratedBranchConflictError(branchError)}
                onBranchChange={handleBranchChange}
                onRegenerateBranch={handleRegenerateBranch}
              />
            </div>

            <GithubLinkImportSection
              linkType={linkType}
              displayedLinkType={displayedLinkType}
              isPreselectedIssue={!!preselectedIssue}
              repoContext={repoContext}
              isIssuesLoading={isIssuesLoading}
              isPrsLoading={isPrsLoading}
              onSelectLinkType={handleSelectLinkType}
              onRefreshIssues={() => void handleRefreshIssues()}
              onRefreshPrs={() => void handleRefreshPrs()}
              issuePanel={
                <IssueLinkPanel
                  repoContext={repoContext}
                  selectedProjectId={selectedProjectId}
                  isPreselectedIssue={!!preselectedIssue}
                  issues={issues}
                  selectedIssueNumber={selectedIssueNumber}
                  issueUrl={issueUrl}
                  issueError={issueError}
                  isIssuesLoading={isIssuesLoading}
                  isIssuePreviewLoading={isIssuePreviewLoading}
                  issuePreview={issuePreview}
                  issueBodyPreview={issueBodyPreview}
                  autoExtractTodos={autoExtractTodos}
                  canAutoExtractTodos={canAutoExtractTodosIssue}
                  autoExtractDescription={autoExtractDescriptionIssue}
                  onSelectIssue={handleSelectIssue}
                  onIssueUrlChange={(value) => {
                    setIssuePreview(null);
                    setIssueError(null);
                    setIssueUrl(value);
                  }}
                  onLoadIssueFromUrl={handleLoadIssueFromUrl}
                  onAutoExtractTodosChange={(checked) => setAutoExtractTodos(Boolean(checked))}
                />
              }
              prPanel={
                <PrLinkPanel
                  repoContext={repoContext}
                  selectedProjectId={selectedProjectId}
                  prs={prs}
                  selectedPrNumber={selectedPrNumber}
                  prUrl={prUrl}
                  prError={prError}
                  isPrsLoading={isPrsLoading}
                  isPrPreviewLoading={isPrPreviewLoading}
                  prPreview={prPreview}
                  autoExtractTodosPr={autoExtractTodosPr}
                  canAutoExtractTodos={canAutoExtractTodosPr}
                  autoExtractDescription={autoExtractDescriptionPr}
                  onSelectPr={handleSelectPr}
                  onPrUrlChange={(value) => {
                    setPrPreview(null);
                    setLocalPrError(null);
                    setPrUrl(value);
                  }}
                  onLoadPrFromUrl={handleLoadPrFromUrl}
                  onAutoExtractTodosChange={(checked) => setAutoExtractTodosPr(Boolean(checked))}
                />
              }
            />

            {submitError && (
              <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                {submitError}
              </div>
            )}
          </div>

          <div className="mx-1 mt-4 border-b border-border/60" />
          <CreateWorkspaceFooter
            priority={priority}
            workflowStatus={workflowStatus}
            selectedLabels={selectedLabels}
            workspaceLabels={workspaceLabels}
            isSubmitting={isSubmitting}
            canSubmit={
              !isSubmitting &&
              !!projectId &&
              !isIssuePreviewLoading &&
              !isBaseBranchesLoading &&
              remoteBranches.length > 0
            }
            onPriorityChange={setPriority}
            onWorkflowStatusChange={setWorkflowStatus}
            onLabelsChange={setSelectedLabels}
            onCreateLabel={createWorkspaceLabel}
            onClose={onClose}
          />
        </form>
      </DialogContent>
    </Dialog>
  );
};
