use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Automation::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Automation::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Automation::CreatedAt).date_time().not_null())
                    .col(ColumnDef::new(Automation::UpdatedAt).date_time().not_null())
                    .col(
                        ColumnDef::new(Automation::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Automation::DisplayName).string().not_null())
                    .col(ColumnDef::new(Automation::AgentId).string().not_null())
                    .col(ColumnDef::new(Automation::TargetKind).string().not_null())
                    .col(ColumnDef::new(Automation::ProjectGuid).string().null())
                    .col(ColumnDef::new(Automation::WorkspaceGuid).string().null())
                    .col(
                        ColumnDef::new(Automation::ScheduleEnabled)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Automation::SchedulePaused)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Automation::ScheduleKind).string().null())
                    .col(ColumnDef::new(Automation::ScheduleExpr).string().null())
                    .col(
                        ColumnDef::new(Automation::ScheduleTimezone)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Automation::NextRunAt).date_time().null())
                    .col(
                        ColumnDef::new(Automation::InstructionsPath)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Automation::ArtifactRoot).string().not_null())
                    .col(ColumnDef::new(Automation::LastRunGuid).string().null())
                    .col(ColumnDef::new(Automation::LastStatus).string().null())
                    .col(
                        ColumnDef::new(Automation::RunCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_automation_schedule_due")
                    .table(Automation::Table)
                    .col(Automation::ScheduleEnabled)
                    .col(Automation::SchedulePaused)
                    .col(Automation::NextRunAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_automation_target")
                    .table(Automation::Table)
                    .col(Automation::TargetKind)
                    .col(Automation::ProjectGuid)
                    .col(Automation::WorkspaceGuid)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(AutomationRun::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AutomationRun::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::AutomationGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::TriggerKind)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AutomationRun::Status).string().not_null())
                    .col(ColumnDef::new(AutomationRun::FailureKind).string().null())
                    .col(ColumnDef::new(AutomationRun::ErrorMessage).string().null())
                    .col(
                        ColumnDef::new(AutomationRun::TargetKind)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(AutomationRun::ProjectGuid).string().null())
                    .col(ColumnDef::new(AutomationRun::WorkspaceGuid).string().null())
                    .col(
                        ColumnDef::new(AutomationRun::CreatedWorkspaceGuid)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(AutomationRun::Cwd).string().not_null())
                    .col(ColumnDef::new(AutomationRun::RunDir).string().not_null())
                    .col(
                        ColumnDef::new(AutomationRun::PromptPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::OutputPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::ResultPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::RunJsonPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::TerminalDisplayName)
                            .string()
                            .not_null()
                            .default("Automations"),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::TmuxSessionName)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::TmuxWindowName)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::TmuxWindowIndex)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::StartedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AutomationRun::CompletedAt)
                            .date_time()
                            .null(),
                    )
                    .col(ColumnDef::new(AutomationRun::ExitCode).integer().null())
                    .col(
                        ColumnDef::new(AutomationRun::CancellationRequested)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_automation_run_automation")
                            .from(AutomationRun::Table, AutomationRun::AutomationGuid)
                            .to(Automation::Table, Automation::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_automation_run_automation_created")
                    .table(AutomationRun::Table)
                    .col(AutomationRun::AutomationGuid)
                    .col(AutomationRun::CreatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_automation_run_status")
                    .table(AutomationRun::Table)
                    .col(AutomationRun::Status)
                    .col(AutomationRun::UpdatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_automation_run_active_automation")
                    .table(AutomationRun::Table)
                    .col(AutomationRun::AutomationGuid)
                    .col(AutomationRun::Status)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(AutomationRun::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .drop_table(
                Table::drop()
                    .table(Automation::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }
}

#[derive(DeriveIden)]
enum Automation {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    DisplayName,
    AgentId,
    TargetKind,
    ProjectGuid,
    WorkspaceGuid,
    ScheduleEnabled,
    SchedulePaused,
    ScheduleKind,
    ScheduleExpr,
    ScheduleTimezone,
    NextRunAt,
    InstructionsPath,
    ArtifactRoot,
    LastRunGuid,
    LastStatus,
    RunCount,
}

#[derive(DeriveIden)]
enum AutomationRun {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    AutomationGuid,
    TriggerKind,
    Status,
    FailureKind,
    ErrorMessage,
    TargetKind,
    ProjectGuid,
    WorkspaceGuid,
    CreatedWorkspaceGuid,
    Cwd,
    RunDir,
    PromptPath,
    OutputPath,
    ResultPath,
    RunJsonPath,
    TerminalDisplayName,
    TmuxSessionName,
    TmuxWindowName,
    TmuxWindowIndex,
    StartedAt,
    CompletedAt,
    ExitCode,
    CancellationRequested,
}
