use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ReviewSession::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewSession::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewSession::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewSession::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewSession::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewSession::WorkspaceGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewSession::ProjectGuid)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewSession::RepoPath).string().not_null())
                    .col(
                        ColumnDef::new(ReviewSession::StorageRootRelPath)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewSession::BaseRef).string().null())
                    .col(ColumnDef::new(ReviewSession::BaseCommit).string().null())
                    .col(
                        ColumnDef::new(ReviewSession::HeadCommit)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewSession::CurrentRevisionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewSession::Status).string().not_null())
                    .col(ColumnDef::new(ReviewSession::Title).string().null())
                    .col(ColumnDef::new(ReviewSession::CreatedBy).string().null())
                    .col(ColumnDef::new(ReviewSession::ClosedAt).date_time().null())
                    .col(ColumnDef::new(ReviewSession::ArchivedAt).date_time().null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_session-workspace-updated")
                    .table(ReviewSession::Table)
                    .col(ReviewSession::WorkspaceGuid)
                    .col(ReviewSession::UpdatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewRevision::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewRevision::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::SessionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::ParentRevisionGuid)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::SourceKind)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewRevision::FixRunGuid).string().null())
                    .col(ColumnDef::new(ReviewRevision::Title).string().null())
                    .col(
                        ColumnDef::new(ReviewRevision::StorageRootRelPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewRevision::BaseRevisionGuid)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(ReviewRevision::CreatedBy).string().null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_revision-session")
                            .from(ReviewRevision::Table, ReviewRevision::SessionGuid)
                            .to(ReviewSession::Table, ReviewSession::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_revision-session-created")
                    .table(ReviewRevision::Table)
                    .col(ReviewRevision::SessionGuid)
                    .col(ReviewRevision::CreatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewFileIdentity::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewFileIdentity::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileIdentity::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileIdentity::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileIdentity::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewFileIdentity::SessionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileIdentity::CanonicalFilePath)
                            .string()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_file_identity-session")
                            .from(ReviewFileIdentity::Table, ReviewFileIdentity::SessionGuid)
                            .to(ReviewSession::Table, ReviewSession::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_file_identity-session-path")
                    .table(ReviewFileIdentity::Table)
                    .col(ReviewFileIdentity::SessionGuid)
                    .col(ReviewFileIdentity::CanonicalFilePath)
                    .unique()
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewFileSnapshot::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::RevisionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::FileIdentityGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::FilePath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::GitStatus)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::OldRelPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::NewRelPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::MetaRelPath)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::OldSha256)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::NewSha256)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::OldSize)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::NewSize)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::IsBinary)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewFileSnapshot::DisplayOrder)
                            .integer()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_file_snapshot-revision")
                            .from(ReviewFileSnapshot::Table, ReviewFileSnapshot::RevisionGuid)
                            .to(ReviewRevision::Table, ReviewRevision::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_file_snapshot-file_identity")
                            .from(
                                ReviewFileSnapshot::Table,
                                ReviewFileSnapshot::FileIdentityGuid,
                            )
                            .to(ReviewFileIdentity::Table, ReviewFileIdentity::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_file_snapshot-revision-order")
                    .table(ReviewFileSnapshot::Table)
                    .col(ReviewFileSnapshot::RevisionGuid)
                    .col(ReviewFileSnapshot::DisplayOrder)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewFileState::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewFileState::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::RevisionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::FileIdentityGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::FileSnapshotGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::Reviewed)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::ReviewedAt)
                            .date_time()
                            .null(),
                    )
                    .col(ColumnDef::new(ReviewFileState::ReviewedBy).string().null())
                    .col(
                        ColumnDef::new(ReviewFileState::InheritedFromFileStateGuid)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFileState::LastCodeChangeAt)
                            .date_time()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_file_state-revision")
                            .from(ReviewFileState::Table, ReviewFileState::RevisionGuid)
                            .to(ReviewRevision::Table, ReviewRevision::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_file_state-file_identity")
                            .from(ReviewFileState::Table, ReviewFileState::FileIdentityGuid)
                            .to(ReviewFileIdentity::Table, ReviewFileIdentity::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_file_state-file_snapshot")
                            .from(ReviewFileState::Table, ReviewFileState::FileSnapshotGuid)
                            .to(ReviewFileSnapshot::Table, ReviewFileSnapshot::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_file_state-revision-file")
                    .table(ReviewFileState::Table)
                    .col(ReviewFileState::RevisionGuid)
                    .col(ReviewFileState::FileIdentityGuid)
                    .unique()
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewComment::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewComment::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::SessionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::RevisionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::FileSnapshotGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::AnchorSide)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::AnchorStartLine)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::AnchorEndLine)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewComment::AnchorLineRangeKind)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewComment::AnchorJson).text().not_null())
                    .col(ColumnDef::new(ReviewComment::Status).string().not_null())
                    .col(
                        ColumnDef::new(ReviewComment::ParentCommentGuid)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(ReviewComment::Title).string().null())
                    .col(ColumnDef::new(ReviewComment::CreatedBy).string().null())
                    .col(ColumnDef::new(ReviewComment::FixedAt).date_time().null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_comment-session")
                            .from(ReviewComment::Table, ReviewComment::SessionGuid)
                            .to(ReviewSession::Table, ReviewSession::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_comment-revision")
                            .from(ReviewComment::Table, ReviewComment::RevisionGuid)
                            .to(ReviewRevision::Table, ReviewRevision::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_comment-file_snapshot")
                            .from(ReviewComment::Table, ReviewComment::FileSnapshotGuid)
                            .to(ReviewFileSnapshot::Table, ReviewFileSnapshot::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_comment-session-created")
                    .table(ReviewComment::Table)
                    .col(ReviewComment::SessionGuid)
                    .col(ReviewComment::CreatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_comment-file-anchor")
                    .table(ReviewComment::Table)
                    .col(ReviewComment::FileSnapshotGuid)
                    .col(ReviewComment::AnchorSide)
                    .col(ReviewComment::AnchorStartLine)
                    .col(ReviewComment::AnchorEndLine)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewMessage::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewMessage::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewMessage::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewMessage::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewMessage::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewMessage::CommentGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewMessage::AuthorType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewMessage::Kind).string().not_null())
                    .col(
                        ColumnDef::new(ReviewMessage::BodyStorageKind)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewMessage::Body).text().not_null())
                    .col(ColumnDef::new(ReviewMessage::BodyRelPath).string().null())
                    .col(ColumnDef::new(ReviewMessage::FixRunGuid).string().null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_message-comment")
                            .from(ReviewMessage::Table, ReviewMessage::CommentGuid)
                            .to(ReviewComment::Table, ReviewComment::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_message-comment-created")
                    .table(ReviewMessage::Table)
                    .col(ReviewMessage::CommentGuid)
                    .col(ReviewMessage::CreatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ReviewFixRun::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ReviewFixRun::Guid)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::CreatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::UpdatedAt)
                            .date_time()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::IsDeleted)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::SessionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::BaseRevisionGuid)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::ResultRevisionGuid)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::ExecutionMode)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ReviewFixRun::Status).string().not_null())
                    .col(ColumnDef::new(ReviewFixRun::PromptRelPath).string().null())
                    .col(ColumnDef::new(ReviewFixRun::ResultRelPath).string().null())
                    .col(ColumnDef::new(ReviewFixRun::PatchRelPath).string().null())
                    .col(ColumnDef::new(ReviewFixRun::SummaryRelPath).string().null())
                    .col(
                        ColumnDef::new(ReviewFixRun::AgentSessionRef)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ReviewFixRun::FinalizeAttempts)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(ReviewFixRun::FailureReason).text().null())
                    .col(ColumnDef::new(ReviewFixRun::CreatedBy).string().null())
                    .col(ColumnDef::new(ReviewFixRun::StartedAt).date_time().null())
                    .col(ColumnDef::new(ReviewFixRun::FinishedAt).date_time().null())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_fix_run-session")
                            .from(ReviewFixRun::Table, ReviewFixRun::SessionGuid)
                            .to(ReviewSession::Table, ReviewSession::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-review_fix_run-base_revision")
                            .from(ReviewFixRun::Table, ReviewFixRun::BaseRevisionGuid)
                            .to(ReviewRevision::Table, ReviewRevision::Guid)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx-review_fix_run-session-created")
                    .table(ReviewFixRun::Table)
                    .col(ReviewFixRun::SessionGuid)
                    .col(ReviewFixRun::CreatedAt)
                    .if_not_exists()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(ReviewFixRun::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewMessage::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewComment::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewFileState::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewFileSnapshot::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewFileIdentity::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewRevision::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ReviewSession::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum ReviewSession {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    WorkspaceGuid,
    ProjectGuid,
    RepoPath,
    StorageRootRelPath,
    BaseRef,
    BaseCommit,
    HeadCommit,
    CurrentRevisionGuid,
    Status,
    Title,
    CreatedBy,
    ClosedAt,
    ArchivedAt,
}

#[derive(DeriveIden)]
enum ReviewRevision {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    SessionGuid,
    ParentRevisionGuid,
    SourceKind,
    FixRunGuid,
    Title,
    StorageRootRelPath,
    BaseRevisionGuid,
    CreatedBy,
}

#[derive(DeriveIden)]
enum ReviewFileIdentity {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    SessionGuid,
    CanonicalFilePath,
}

#[derive(DeriveIden)]
enum ReviewFileSnapshot {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    RevisionGuid,
    FileIdentityGuid,
    FilePath,
    GitStatus,
    OldRelPath,
    NewRelPath,
    MetaRelPath,
    OldSha256,
    NewSha256,
    OldSize,
    NewSize,
    IsBinary,
    DisplayOrder,
}

#[derive(DeriveIden)]
enum ReviewFileState {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    RevisionGuid,
    FileIdentityGuid,
    FileSnapshotGuid,
    Reviewed,
    ReviewedAt,
    ReviewedBy,
    InheritedFromFileStateGuid,
    LastCodeChangeAt,
}

#[derive(DeriveIden)]
enum ReviewComment {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    SessionGuid,
    RevisionGuid,
    FileSnapshotGuid,
    AnchorSide,
    AnchorStartLine,
    AnchorEndLine,
    AnchorLineRangeKind,
    AnchorJson,
    Status,
    ParentCommentGuid,
    Title,
    CreatedBy,
    FixedAt,
}

#[derive(DeriveIden)]
enum ReviewMessage {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    CommentGuid,
    AuthorType,
    Kind,
    BodyStorageKind,
    Body,
    BodyRelPath,
    FixRunGuid,
}

#[derive(DeriveIden)]
enum ReviewFixRun {
    Table,
    Guid,
    CreatedAt,
    UpdatedAt,
    IsDeleted,
    SessionGuid,
    BaseRevisionGuid,
    ResultRevisionGuid,
    ExecutionMode,
    Status,
    PromptRelPath,
    ResultRelPath,
    PatchRelPath,
    SummaryRelPath,
    AgentSessionRef,
    FinalizeAttempts,
    FailureReason,
    CreatedBy,
    StartedAt,
    FinishedAt,
}
