import React from "react";
import {
  AlertCircle,
  AlertTriangle,
  AlignLeft,
  AppWindow,
  ArrowLeftRight,
  Badge as BadgeIcon,
  BarChart3,
  Bell,
  Calendar,
  CalendarDays,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleDot,
  CircleUser,
  ClipboardList,
  Columns2,
  Columns3,
  Command,
  Component,
  CreditCard,
  FormInput,
  GalleryHorizontal,
  Group,
  Hash,
  Inbox,
  Info,
  Keyboard,
  LayoutPanelTop,
  LayoutTemplate,
  List,
  ListChecks,
  ListFilter,
  LoaderCircle,
  LogIn,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Minus,
  MoreHorizontal,
  MousePointerClick,
  Navigation,
  Paperclip,
  PanelBottom,
  PanelLeft,
  PanelRight,
  RectangleHorizontal,
  ScanSearch,
  Settings,
  SlidersHorizontal,
  Square,
  StretchHorizontal,
  Table,
  Table2,
  Tag,
  TextCursorInput,
  ToggleLeft,
  Type,
  UnfoldVertical,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  accordion: ChevronsDownUp,
  alert: AlertCircle,
  "alert-dialog": AlertTriangle,
  "aspect-ratio": RectangleHorizontal,
  attachment: Paperclip,
  avatar: CircleUser,
  badge: BadgeIcon,
  breadcrumb: ChevronRight,
  bubble: MessageCircle,
  button: Square,
  "button-group": Columns2,
  calendar: Calendar,
  card: CreditCard,
  carousel: GalleryHorizontal,
  chart: BarChart3,
  checkbox: CheckSquare,
  collapsible: ChevronsUpDown,
  combobox: ChevronsUpDown,
  command: Command,
  "context-menu": MousePointerClick,
  "data-table": Table2,
  "date-picker": CalendarDays,
  dialog: AppWindow,
  direction: ArrowLeftRight,
  drawer: PanelBottom,
  "dropdown-menu": ChevronDown,
  empty: Inbox,
  field: FormInput,
  form: ClipboardList,
  "hover-card": ScanSearch,
  input: TextCursorInput,
  "input-group": Group,
  "input-otp": Hash,
  item: List,
  kbd: Keyboard,
  label: Tag,
  marker: MapPin,
  menubar: Menu,
  message: MessageSquare,
  "message-scroller": MessagesSquare,
  "native-select": ListFilter,
  "navigation-menu": Navigation,
  pagination: MoreHorizontal,
  popover: MessageSquare,
  progress: LoaderCircle,
  questionnaire: ListChecks,
  "radio-group": CircleDot,
  resizable: StretchHorizontal,
  "scroll-area": UnfoldVertical,
  select: ChevronDown,
  separator: Minus,
  sheet: PanelRight,
  sidebar: PanelLeft,
  skeleton: Square,
  slider: SlidersHorizontal,
  sonner: Bell,
  spinner: LoaderCircle,
  switch: ToggleLeft,
  table: Table,
  tabs: LayoutPanelTop,
  textarea: AlignLeft,
  toast: Bell,
  toggle: ToggleLeft,
  "toggle-group": Columns3,
  tooltip: Info,
  typography: Type,
  "block.auth-form": LogIn,
  "block.settings-shell": Settings,
  "block.empty-state": Inbox,
  "block.nav-content": LayoutTemplate,
};

export const ComponentSidebarIcon = Component;

export function CatalogTypeIcon({
  componentType,
  size = 14,
}: {
  componentType: string;
  size?: number;
}) {
  const Icon = ICONS[componentType] ?? Square;
  return <Icon size={size} strokeWidth={2} aria-hidden />;
}

export function catalogIconTypes(): string[] {
  return Object.keys(ICONS);
}
