import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { chromeTokens, resolveBoardTheme } from "./chrome";

describe("embed chrome tokens", () => {
  test("dark tokens never use a light canvas or light fallback foreground", () => {
    const dark = chromeTokens("dark");
    expect(dark.canvas).toBe("#09090b");
    expect(dark.fg).toContain("--foreground");
    expect(dark.fg).not.toContain("#18181b");
    expect(dark.bg).toContain("--background");
    expect(dark.bg).not.toContain("#fafafa");
  });

  test("light tokens keep a readable dark foreground fallback", () => {
    const light = chromeTokens("light");
    expect(light.canvas).toBe("#ffffff");
    expect(light.fg).toContain("#18181b");
  });

  test("resolveBoardTheme honors an explicit theme", () => {
    expect(resolveBoardTheme("dark")).toBe("dark");
    expect(resolveBoardTheme("light")).toBe("light");
  });
});

describe("excalidraw API handoff", () => {
  test("does not call onApi from the constructor-time excalidrawAPI callback", () => {
    const board = readFileSync(new URL("./ExcalidrawBoard.tsx", import.meta.url), "utf8");
    expect(board).toContain("bindHostApi");
    expect(board).toContain("handedOffRef.current = true");
    expect(board).toContain("onApiRef.current(");
    expect(board).toContain("bindHostApi(api");
    expect(board).toContain("handleKeyboardGlobally={editModeHandlesKeyboardGlobally(viewModeEnabled)}");
    expect(board).not.toContain("handleKeyboardGlobally={false}");
    expect(board).toContain("onFocusCapture");
    expect(board).toContain("onKeyDownCapture");
    expect(board).toContain("convertToExcalidrawElements");
    expect(board).toContain("regenerateIds: false");
    expect(board).toContain("stampPtCustomData");
    expect(board).toContain("toExcalidrawCompatElements");
    expect(board).not.toMatch(/excalidrawAPI=\{\(api\) => \{[\s\S]*onApiRef\.current/);
  });
});

describe("excalidraw Atmos chrome", () => {
  test("board disables invert and remaps islands to Atmos tokens", () => {
    const board = readFileSync(new URL("./ExcalidrawBoard.tsx", import.meta.url), "utf8");
    const css = readFileSync(new URL("./excalidraw-theme.css", import.meta.url), "utf8");
    const app = readFileSync(new URL("./PtDesignApp.tsx", import.meta.url), "utf8");
    expect(board).toContain('import "./excalidraw-theme.css"');
    expect(board).toContain("pt-design-excalidraw-theme");
    expect(board).toContain("DISABLE_CANVAS_INVERT");
    expect(board).toContain("MainMenu");
    expect(board).toContain("changeViewBackgroundColor: false");
    expect(board).not.toContain("DefaultItems");
    expect(css).toContain(".excalidraw.theme--dark canvas");
    expect(css).toContain("filter: none");
    expect(css).toContain("--theme-filter: none");
    expect(css).toContain("--island-bg-color: var(--card");
    expect(css).toContain("#09090b");
    expect(css).toContain(".zoom-actions");
    expect(css).toContain(".undo-redo-buttons");
    expect(css).toContain(".library-button");
    expect(css).toContain(".help-icon");
    expect(css).toContain(".default-sidebar-trigger");
    expect(css).toContain(".sidebar-trigger__label-element");
    expect(css).toContain(".sidebar__dock");
    expect(css).toContain(".ToolIcon__lock");
    expect(css).toContain('data-testid="toolbar-lock"');
    expect(css).toContain(".App-toolbar .App-toolbar__divider");
    expect(css).toContain(".excalidraw .App-toolbar.Island");
    expect(css).toContain("--pt-island-pad:");
    expect(css).toContain("--pt-island-size:");
    expect(css).toContain("--padding: 1");
    expect(css).toContain("min-height: var(--pt-island-size)");
    expect(css).toContain("height: var(--pt-chrome-size)");
    expect(css).toContain(".pt-design-mode-toggle");
    expect(css).toContain(".pt-design-back");
    expect(css).toContain("--pt-back-slot");
    expect(css).toContain("--pt-chrome-size: var(--lg-button-size, 2.25rem)");
    expect(css).toContain("--pt-chrome-btn-size: calc(var(--pt-chrome-size) - 2 * var(--pt-island-pad))");
    expect(css).toContain("width: calc(var(--pt-chrome-size) - 2 * var(--pt-island-pad))");
    expect(css).toContain("gap: var(--pt-island-pad)");
    expect(css).toContain("--pt-back-slot: calc(var(--pt-chrome-size) + 8px)");
    expect(css).not.toContain("--pt-back-slot: calc(4.25rem + 8px)");
    expect(css).toContain("justify-content: center");
    expect(board).toContain("aria-label={backLabel ?? \"Back\"}");
    expect(board).not.toMatch(/>\s*\{backLabel \?\? "Back"\}\s*</);
    expect(css).toContain(".App-menu_top .main-menu-trigger");
    expect(css).toContain("left: calc(var(--editor-container-padding, 1rem) + var(--pt-back-slot, 0px) + var(--pt-chrome-size) + 8px)");
    expect(css).toContain("padding: var(--pt-island-pad)");
    expect(css).not.toContain("padding: 0 2px 0 var(--lg-button-size, 2.25rem)");
    expect(css).not.toContain("--padding: 0");
    expect(css).toContain("background: var(--island-bg-color, var(--card)) !important");
    expect(css).toContain("[data-pt-palette]");
    expect(css).toContain("button.pt-design-catalog-row");
    expect(css).toContain(".pt-design-top-right__actions");
    expect(css).toContain(".excalidraw .App-menu_top");
    expect(css).toContain(".excalidraw.excalidraw--view-mode .App-menu_top__left");
    expect(css).toContain(".excalidraw.excalidraw--view-mode .layer-ui__wrapper__top-right");
    expect(css).toContain("margin-top: var(--pt-island-pad, 0.25rem)");
    expect(css).toContain("border-radius: 12px");
    expect(css).toContain(".pt-design-island-trigger");
    expect(css).toContain(".sidebar-tab-trigger");
    expect(css).toContain(".sidebar__header::after");
    expect(css).toContain("display: none");
    expect(css).toContain(".default-sidebar .sidebar-triggers");
    expect(css).toContain(".pt-design-library-sidebar .sidebar-triggers .sidebar-tab-trigger:nth-child(1)::after");
    expect(css).toContain('.pt-design-library-sidebar .sidebar-triggers .sidebar-tab-trigger:nth-child(2)::after');
    expect(css).toContain('content: "Search"');
    expect(css).toContain('content: "Library"');
    expect(css).toContain('content: "搜索"');
    expect(css).toContain('content: "素材库"');
    expect(board).toContain("pt-design-catalog-tab-component");
    expect(board).toContain("pt-design-catalog-tab-block");
    expect(board).toContain("pt-design-catalog-tab-charts");
    expect(board).toContain("ChartSidebarIcon");
    expect(board).toContain("CatalogStyleMenu");
    const styleMenu = readFileSync(new URL("./CatalogStyleMenu.tsx", import.meta.url), "utf8");
    expect(styleMenu).toContain("pt-design-catalog-style");
    expect(styleMenu).toContain("pt-design-catalog-style-radius");
    expect(css).toContain(".pt-design-catalog-sidebar [data-testid=\"sidebar-close\"]");
    expect(css).toContain(".pt-design-catalog-style-menu");
    expect(board).toContain("BlockSidebarIcon");
    expect(board).toContain("ComponentSidebarIcon");
    expect(board).toContain("pt-design-library-sidebar");
    expect(board).toContain("blockCatalog");
    expect(board).toContain("chartCatalog");
    expect(board).toContain("ChartSidebarIcon");
    expect(css).toContain('data-icon-only="true"');
    expect(css).toContain(".color-picker__top-picks");
    expect(css).toContain("#fafafa");
    expect(css).toContain("input.pt-design-catalog-search");
    expect(css).toContain(".pt-design-place-reveal");
    expect(css).toContain("pt-design-place-breathe");
    expect(css).toContain(".pt-design-agent-highlight");
    expect(css).toContain("pt-design-agent-pulse");
    expect(css).toContain(".excalidraw .follow-mode");
    expect(css).toContain("border-radius: var(--radius-xl");
    expect(css).toContain(".excalidraw .context-menu");
    expect(css).toContain(".excalidraw .popover:has(.context-menu)");
    expect(css).toContain("pt-design-menu-in");
    expect(css).toContain(".context-menu-item.checkmark::before");
    expect(css).toContain(".context-menu-item:hover");
    expect(css).toContain("var(--pt-menu-hover)");
    expect(css).toContain(".context-menu-item-separator");
    expect(css).toContain(".dropdown-menu .dropdown-menu-container");
    expect(css).toContain("min-width: 0");
    expect(css).toContain(".excalidraw.excalidraw--mobile .main-menu-trigger");
    expect(css).toContain(".excalidraw.excalidraw--mobile .App-top-bar .App-toolbar-content");
    expect(css).toContain(".excalidraw.excalidraw--mobile .mobile-toolbar");
    expect(css).toContain(".App-toolbar-content .dropdown-menu--mobile");
    expect(css).toContain("width: max-content");
    expect(css).toContain(".pt-design-top-right");
    expect(css).toContain(".excalidraw.excalidraw--mobile .excalidraw-ui-top-left");
    expect(css).toContain("[data-testid=\"pt-design-board\"] > .pt-design-mode-toggle");
    expect(css).toContain("left: calc(var(--editor-container-padding, 1rem) + var(--pt-back-slot, 0px) + var(--pt-chrome-size) + 8px)");
    expect(board).toContain("pt-design-back");
    expect(board).toContain("data-has-back");
    expect(css).toContain(".pt-design-mode-toggle__btn:active");
    expect(css).toContain("margin-left: var(--pt-back-slot)");
    expect(css).not.toContain("display: contents");
    expect(css).not.toContain("@media (pointer: fine)");
    expect(board).toContain("pt-design-top-right");
    expect(board).toContain("pt-design-top-right__actions");
    expect(board).toContain("{topLeftChrome}");
    expect(board).not.toMatch(/renderTopRightUI[\s\S]{0,240}\{topLeftChrome\}/);
    expect(board).toContain("iconOnly={isMobile}");
    expect(css).not.toContain("background-color: var(--select-highlight-color)");
    expect(css).toContain(".context-menu-item__shortcut > kbd");
    expect(board).toContain("observeShortcutDecorations");
    expect(board).toContain("boardRef");
    expect(board).toContain("applySceneCameraNever");
    expect(app).not.toContain("scrollToContent");
    expect(app).toContain("pt-design-place-reveal");
    expect(app).toContain("revealOnBoard");
    expect(app).toContain("createLiveBoard");
    expect(app).toContain("menuItems={menuItems}");
    expect(app).toContain("topLeftChrome");
    expect(app).toContain("onBack={onBack ? handleBack : undefined}");
    expect(app).toContain("catalog=");
    expect(app).toContain("blockCatalog=");
    expect(app).toContain("LibraryOverlay");
    expect(app).toContain("shouldPromptLibraryName");
    expect(app).toContain("namedPersistForLibrarySave");
    expect(app).toContain("fileSyncDebouncer");
    expect(app).toContain("saveBoundLibrary");
    expect(app).toContain('"save"');
    expect(app).not.toContain('id: "open" as const');
    expect(app).not.toContain('label: "Open"');
    const overlay = readFileSync(new URL("./LibraryOverlay.tsx", import.meta.url), "utf8");
    expect(overlay).not.toContain("pt-design-library-item");
    expect(overlay).not.toContain("Saved on this computer");
    expect(overlay).not.toContain("No saved designs yet.");
    expect(app).toContain("Give to Agent");
    expect(app).not.toContain("Add frame");
    expect(app).not.toContain("Copy IR");
    expect(app).not.toContain('id: "add-frame"');
    expect(app).not.toContain('id: "copy-ir"');
    expect(app).not.toContain('id: "share" as const');
    expect(board).toContain("drawingAppState");
    expect(board).toContain("resolveDrawingStrokeColor");
    expect(board).toContain("applyThemeInkToElements");
    expect(board).toContain("DefaultSidebar");
    expect(board).toContain("pt-design-library-trigger");
    expect(board).toContain("iconOnly");
    expect(app).toContain("SelectionPropsRail");
    expect(app).toContain("catalogStyle");
    expect(app).toContain('radius: "default"');
    expect(app).toContain("settings: { radius");
    expect(app).not.toContain("translateX(-50%)");
    const collabHook = readFileSync(new URL("./use-collab.ts", import.meta.url), "utf8");
    expect(collabHook).toContain('captureUpdate: "NEVER"');
    expect(css).toContain(".pt-design-prop-rail");
    expect(css).toContain(".pt-design-prop-trigger");
    expect(css).toContain(".pt-design-prop-options");
    expect(css).toContain(".pt-design-prop-option");
    expect(css).toContain("flex-direction: column");
    expect(css).toContain('[data-placement="bottom"]');
    expect(css).toContain("flex-direction: column-reverse");
    expect(css).toContain("align-items: flex-end");
    const rail = readFileSync(new URL("./SelectionPropsRail.tsx", import.meta.url), "utf8");
    expect(rail).toContain("RadiusGlyph");
    expect(rail).toContain('data-placement={placement}');
    expect(rail).toContain("mobileColorTool");
    expect(rail).toContain("railAnchorFromLayout");
  });
});

describe("S27 collab remote apply NEVER", () => {
  test("onScene applies remote elements with captureUpdate NEVER", () => {
    const collabHook = readFileSync(new URL("./use-collab.ts", import.meta.url), "utf8");
    expect(collabHook).toMatch(
      /onScene:\s*\([^)]*\)\s*=>\s*\{[\s\S]*?captureUpdate:\s*"NEVER"/,
    );
  });
});

describe("excalidraw collaboration", () => {
  test("board opens an Atmos share popover instead of the official dialog", () => {
    const board = readFileSync(new URL("./ExcalidrawBoard.tsx", import.meta.url), "utf8");
    const app = readFileSync(new URL("./PtDesignApp.tsx", import.meta.url), "utf8");
    const popover = readFileSync(new URL("./SharePopover.tsx", import.meta.url), "utf8");
    const css = readFileSync(new URL("./excalidraw-theme.css", import.meta.url), "utf8");
    expect(board).toContain("SharePopover");
    expect(board).toContain("pt-design-share-trigger");
    expect(board).not.toContain("LiveCollaborationTrigger");
    expect(board).toContain("isCollaborating");
    expect(app).toContain("useExcalidrawCollab");
    expect(app).toContain("sharePanel");
    expect(app).toContain("clientId");
    expect(app).not.toMatch(/if \(!agentBridge \|\| !collab\.room\)/);
    expect(app).not.toMatch(/id: "give-to-agent"[\s\S]{0,400}collab\.start/);
    expect(app).not.toMatch(/const openShare[\s\S]{0,80}collab\.start/);
    expect(app).not.toContain("useLiveEvents");
    expect(app).not.toContain("AgentPulse");
    expect(popover).toContain("Your name");
    expect(popover).toContain("Copy prompt");
    expect(popover).toContain("open board");
    expect(popover).not.toContain("no Share, MCP");
    expect(popover).not.toContain("Copy MCP config");
    expect(popover).toContain("pt-design-share-tab-${id}");
    expect(popover).toContain('"agent"');
    expect(popover).toContain('"human"');
    expect(popover).toContain("agentTab");
    expect(popover).toContain("humanTab");
    expect(popover).toContain("With Agent");
    expect(popover).toContain("With Human");
    expect(popover).toContain("Collaborate");
    expect(popover).toContain("Copy link");
    expect(popover).toContain("Paste a collaboration link to join");
    expect(popover).toContain("onJoin");
    expect(popover).not.toContain("readOnly");
    expect(popover).toContain("Start collaboration");
    expect(popover).toContain("Stop collaboration");
    expect(popover).not.toContain("Stop session");
    expect(popover).not.toMatch(/qr|QRCode/i);
    expect(css).toContain(".pt-design-share-trigger");
  });
});

