/** Pinned from local shadcn/ui clone `apps/v4/lib/components.ts` (2026-08). */
export const CATALOG_VERSION = "2026.08-shadcn";

export const SHADCN_BASIC_IDS = [
  "accordion",
  "alert",
  "alert-dialog",
  "aspect-ratio",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "button-group",
  "calendar",
  "card",
  "carousel",
  "chart",
  "checkbox",
  "collapsible",
  "combobox",
  "command",
  "context-menu",
  "data-table",
  "date-picker",
  "dialog",
  "direction",
  "drawer",
  "dropdown-menu",
  "empty",
  "field",
  "form",
  "hover-card",
  "input",
  "input-group",
  "input-otp",
  "item",
  "kbd",
  "label",
  "menubar",
  "native-select",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "resizable",
  "scroll-area",
  "select",
  "separator",
  "sheet",
  "sidebar",
  "skeleton",
  "slider",
  "sonner",
  "spinner",
  "switch",
  "table",
  "tabs",
  "textarea",
  "toast",
  "toggle",
  "toggle-group",
  "tooltip",
  "typography",
] as const;

export type ShadcnBasicId = (typeof SHADCN_BASIC_IDS)[number];

export const REQUIRED_BLOCKS = [
  "block.auth-form",
  "block.settings-shell",
  "block.empty-state",
  "block.nav-content",
] as const;

export type RequiredBlockId = (typeof REQUIRED_BLOCKS)[number];
