pub mod agent;
pub mod agent_hooks;

pub mod agent_chat;
pub mod automation;
pub mod canvas;
pub mod canvas_agent_relay;
pub mod center_layout;
pub mod cli_identity;
pub mod disk_analyzer;
pub mod git_commit_message;
pub mod group;
pub mod linear;
pub mod linear_credentials;
pub mod llm_text_generation;
pub mod local_services;
pub mod message_push;
pub mod notification;
pub mod project;
mod project_logo;
pub mod resource_monitor;
pub mod review;
pub mod skill;
pub mod terminal;
pub mod terminal_overview;
pub mod test;
pub mod workspace;
pub mod workspace_gitignore_dirs;
mod workspace_support;
pub mod workspace_todos;
