"use client";

import React from "react";
import {
  Badge,
  Button,
  Card,
  CardContent,
  Checkbox,
  Collapsible,
  CollapsibleContent,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  Input,
  Label,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ScrollArea,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  cn,
} from "@workspace/ui";
import {
  Check,
  ChevronDown,
  CircleDot,
  CloudDownload,
  Ellipsis,
  ExternalLink,
  GitBranch,
  GitPullRequestArrow,
  Loader2,
  LoaderCircle,
  RotateCw,
  Sparkles,
} from "lucide-react";
import type { GithubIssuePayload, GithubPrPayload } from "@/api/ws-api";
import {
  isAutoGeneratedBranchConflictError,
  type RepoContext,
} from "@/components/welcome/welcome-page-helpers";

export function WelcomeAdvancedOptions({
  autoExtractDescriptionIssue,
  autoExtractDescriptionPr,
  autoExtractTodos,
  autoExtractTodosPr,
  baseBranch,
  baseBranchFilter,
  branch,
  branchError,
  branchInputRef,
  canAutoExtractTodosIssue,
  canAutoExtractTodosPr,
  displayedLinkType,
  filteredRemoteBranches,
  handleLoadIssueFromUrl,
  handleLoadPrFromUrl,
  handleRefreshIssues,
  handleRefreshPrs,
  handleRegenerateBranch,
  handleSelectIssue,
  handleSelectLinkType,
  handleSelectPr,
  isAdvancedOpen,
  isBaseBranchesLoading,
  isBaseBranchOpen,
  isIssuePreviewLoading,
  isIssuesLoading,
  isPrPreviewLoading,
  isPrsLoading,
  issueError,
  issuePreview,
  issues,
  issueUrl,
  linkType,
  name,
  onIssueUrlChange,
  onNameChange,
  onBranchChange,
  onPrUrlChange,
  prError,
  prPreview,
  prs,
  prUrl,
  remoteBranches,
  repoContext,
  selectedIssueNumber,
  selectedPrNumber,
  selectedProjectId,
  setAutoExtractTodos,
  setAutoExtractTodosPr,
  setBaseBranch,
  setBaseBranchFilter,
  setIsAdvancedOpen,
  setIsBaseBranchOpen,
  submitError,
}: {
  autoExtractDescriptionIssue: string;
  autoExtractDescriptionPr: string;
  autoExtractTodos: boolean;
  autoExtractTodosPr: boolean;
  baseBranch: string;
  baseBranchFilter: string;
  branch: string;
  branchError: string | null;
  branchInputRef: React.RefObject<HTMLInputElement | null>;
  canAutoExtractTodosIssue: boolean;
  canAutoExtractTodosPr: boolean;
  displayedLinkType: "issue" | "pr";
  filteredRemoteBranches: string[];
  handleLoadIssueFromUrl: () => void | Promise<void>;
  handleLoadPrFromUrl: () => void | Promise<void>;
  handleRefreshIssues: () => void | Promise<void>;
  handleRefreshPrs: () => void | Promise<void>;
  handleRegenerateBranch: () => void;
  handleSelectIssue: (value: string) => void;
  handleSelectLinkType: (next: "issue" | "pr") => void;
  handleSelectPr: (value: string) => void;
  isAdvancedOpen: boolean;
  isBaseBranchesLoading: boolean;
  isBaseBranchOpen: boolean;
  isIssuePreviewLoading: boolean;
  isIssuesLoading: boolean;
  isPrPreviewLoading: boolean;
  isPrsLoading: boolean;
  issueError: string | null;
  issuePreview: GithubIssuePayload | null;
  issues: GithubIssuePayload[];
  issueUrl: string;
  linkType: "none" | "issue" | "pr";
  name: string;
  onIssueUrlChange: (value: string) => void;
  onNameChange: (value: string) => void;
  onBranchChange: (value: string) => void;
  onPrUrlChange: (value: string) => void;
  prError: string | null;
  prPreview: GithubPrPayload | null;
  prs: GithubPrPayload[];
  prUrl: string;
  remoteBranches: string[];
  repoContext: RepoContext | null;
  selectedIssueNumber: string;
  selectedPrNumber: string;
  selectedProjectId: string | null;
  setAutoExtractTodos: (value: boolean) => void;
  setAutoExtractTodosPr: (value: boolean) => void;
  setBaseBranch: (value: string) => void;
  setBaseBranchFilter: (value: string) => void;
  setIsAdvancedOpen: (value: boolean) => void;
  setIsBaseBranchOpen: (value: boolean) => void;
  submitError: string | null;
}) {
  return (
    <Popover open={isAdvancedOpen} onOpenChange={setIsAdvancedOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          className="inline-flex size-9 items-center justify-center rounded-md border border-border/60 bg-background/35 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
          aria-label="Open advanced workspace options"
        >
          <Ellipsis className="size-4" />
        </button>
      </PopoverTrigger>
      <PopoverContent
        side="right"
        align="end"
        sideOffset={8}
        collisionPadding={16}
        className="flex w-[min(92vw,760px)] max-w-[760px] flex-col overflow-hidden rounded-[1.5rem] border border-border/60 bg-background p-0 shadow-2xl backdrop-blur-md"
        style={{ maxHeight: "var(--radix-popover-content-available-height)" }}
      >
        <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
          <div className="grid gap-5">
            <div className="grid gap-4 md:grid-cols-2">
              <div className="grid gap-2">
                <Label htmlFor="workspace-name-inline">Name</Label>
                <Input
                  id="workspace-name-inline"
                  value={name}
                  onChange={(event) => onNameChange(event.target.value)}
                  placeholder="Workspace display name"
                  className="h-10 bg-muted/35"
                />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="workspace-branch-inline">Current workspace branch</Label>
                <Input
                  id="workspace-branch-inline"
                  ref={branchInputRef}
                  value={branch}
                  onChange={(event) => onBranchChange(event.target.value)}
                  placeholder="Workspace branch"
                  className="h-10 bg-muted/35"
                />
                {branchError ? (
                  <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
                    <span>{branchError}</span>
                    {isAutoGeneratedBranchConflictError(branchError) ? (
                      <Button
                        type="button"
                        variant="link"
                        className="ml-1 h-auto p-0 text-xs align-baseline"
                        onClick={handleRegenerateBranch}
                      >
                        Random generate again
                      </Button>
                    ) : null}
                  </div>
                ) : null}
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="workspace-base-branch-trigger-inline">Base branch</Label>
              <DropdownMenu
                open={isBaseBranchOpen}
                onOpenChange={(open) => {
                  setIsBaseBranchOpen(open);
                  if (open) setBaseBranchFilter("");
                }}
                modal={false}
              >
                <DropdownMenuTrigger asChild>
                  <button
                    id="workspace-base-branch-trigger-inline"
                    type="button"
                    disabled={isBaseBranchesLoading || remoteBranches.length === 0}
                    className="flex h-11 w-full items-center justify-between rounded-xl border border-border/60 bg-muted/35 px-3 text-sm disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <div className="flex min-w-0 items-center text-muted-foreground">
                      <span className="mr-1 shrink-0 opacity-50">origin/</span>
                      <span className="truncate">{baseBranch}</span>
                    </div>
                    <ChevronDown className="size-4 opacity-50" />
                  </button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="start" className="w-[var(--radix-dropdown-menu-trigger-width)] p-3">
                  <div className="space-y-2">
                    <p className="text-[12px] text-muted-foreground">Select target branch</p>
                    <Input
                      value={baseBranchFilter}
                      onChange={(event) => setBaseBranchFilter(event.target.value)}
                      onKeyDown={(event) => event.stopPropagation()}
                      placeholder="Search branches..."
                      className="h-8 text-[12px]"
                    />
                  </div>
                  <ScrollArea className="mt-2 h-[220px] overflow-x-auto">
                    <div className="p-1">
                      {isBaseBranchesLoading ? (
                        <div className="p-2 text-center text-[12px] text-muted-foreground">
                          Loading branches...
                        </div>
                      ) : filteredRemoteBranches.length > 0 ? (
                        filteredRemoteBranches.map((remoteBranch) => (
                          <DropdownMenuItem
                            key={remoteBranch}
                            onClick={() => setBaseBranch(remoteBranch)}
                            className={cn(
                              "cursor-pointer justify-between whitespace-nowrap text-[13px]",
                              baseBranch === remoteBranch &&
                                "bg-accent text-accent-foreground",
                            )}
                          >
                            <span className="flex items-center">
                              {baseBranch === remoteBranch ? (
                                <Check className="mr-2 size-3.5 text-emerald-500" />
                              ) : (
                                <GitBranch className="mr-2 size-3.5 text-muted-foreground" />
                              )}
                              <span className="mr-1 text-muted-foreground/60">origin/</span>
                              <span>{remoteBranch}</span>
                            </span>
                          </DropdownMenuItem>
                        ))
                      ) : (
                        <div className="p-2 text-center text-[12px] text-muted-foreground">
                          No matching branches
                        </div>
                      )}
                    </div>
                  </ScrollArea>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>

            <div className="rounded-2xl border border-border/60 bg-background/35">
              <div className="flex items-center gap-2 p-1.5">
                <button
                  type="button"
                  onClick={() => handleSelectLinkType("issue")}
                  className={cn(
                    "inline-flex flex-1 items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm transition-colors",
                    linkType === "issue"
                      ? "bg-muted text-foreground shadow-sm"
                      : "text-muted-foreground hover:bg-muted/60 hover:text-foreground",
                  )}
                >
                  <CircleDot className="size-4" />
                  <span className="font-medium">GitHub Issue</span>
                </button>
                <button
                  type="button"
                  onClick={() => handleSelectLinkType("pr")}
                  className={cn(
                    "inline-flex flex-1 items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm transition-colors",
                    linkType === "pr"
                      ? "bg-muted text-foreground shadow-sm"
                      : "text-muted-foreground hover:bg-muted/60 hover:text-foreground",
                  )}
                >
                  <GitPullRequestArrow className="size-4" />
                  <span className="font-medium">GitHub PR</span>
                </button>
                {repoContext && linkType === "issue" ? (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-8"
                    onClick={() => void handleRefreshIssues()}
                    disabled={isIssuesLoading}
                    title="Refresh issues"
                  >
                    {isIssuesLoading ? <LoaderCircle className="size-4 animate-spin" /> : <RotateCw className="size-4" />}
                  </Button>
                ) : repoContext && linkType === "pr" ? (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-8"
                    onClick={() => void handleRefreshPrs()}
                    disabled={isPrsLoading}
                    title="Refresh PRs"
                  >
                    {isPrsLoading ? <LoaderCircle className="size-4 animate-spin" /> : <RotateCw className="size-4" />}
                  </Button>
                ) : null}
              </div>

              <Collapsible open={linkType !== "none"}>
                <CollapsibleContent>
                  {displayedLinkType === "issue" ? (
                    <IssueLinkPanel
                      autoExtractDescription={autoExtractDescriptionIssue}
                      autoExtractTodos={autoExtractTodos}
                      canAutoExtractTodos={canAutoExtractTodosIssue}
                      handleLoadIssueFromUrl={handleLoadIssueFromUrl}
                      handleSelectIssue={handleSelectIssue}
                      isIssuePreviewLoading={isIssuePreviewLoading}
                      isIssuesLoading={isIssuesLoading}
                      issueError={issueError}
                      issuePreview={issuePreview}
                      issues={issues}
                      issueUrl={issueUrl}
                      onIssueUrlChange={onIssueUrlChange}
                      repoContext={repoContext}
                      selectedIssueNumber={selectedIssueNumber}
                      selectedProjectId={selectedProjectId}
                      setAutoExtractTodos={setAutoExtractTodos}
                    />
                  ) : null}

                  {displayedLinkType === "pr" ? (
                    <PrLinkPanel
                      autoExtractDescription={autoExtractDescriptionPr}
                      autoExtractTodos={autoExtractTodosPr}
                      canAutoExtractTodos={canAutoExtractTodosPr}
                      handleLoadPrFromUrl={handleLoadPrFromUrl}
                      handleSelectPr={handleSelectPr}
                      isPrPreviewLoading={isPrPreviewLoading}
                      isPrsLoading={isPrsLoading}
                      onPrUrlChange={onPrUrlChange}
                      prError={prError}
                      prPreview={prPreview}
                      prs={prs}
                      prUrl={prUrl}
                      repoContext={repoContext}
                      selectedPrNumber={selectedPrNumber}
                      selectedProjectId={selectedProjectId}
                      setAutoExtractTodos={setAutoExtractTodosPr}
                    />
                  ) : null}
                </CollapsibleContent>
              </Collapsible>
            </div>

            {submitError ? (
              <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
                {submitError}
              </div>
            ) : null}
          </div>
        </div>
      </PopoverContent>
    </Popover>
  );
}

function IssueLinkPanel({
  autoExtractDescription,
  autoExtractTodos,
  canAutoExtractTodos,
  handleLoadIssueFromUrl,
  handleSelectIssue,
  isIssuePreviewLoading,
  isIssuesLoading,
  issueError,
  issuePreview,
  issues,
  issueUrl,
  onIssueUrlChange,
  repoContext,
  selectedIssueNumber,
  selectedProjectId,
  setAutoExtractTodos,
}: {
  autoExtractDescription: string;
  autoExtractTodos: boolean;
  canAutoExtractTodos: boolean;
  handleLoadIssueFromUrl: () => void | Promise<void>;
  handleSelectIssue: (value: string) => void;
  isIssuePreviewLoading: boolean;
  isIssuesLoading: boolean;
  issueError: string | null;
  issuePreview: GithubIssuePayload | null;
  issues: GithubIssuePayload[];
  issueUrl: string;
  onIssueUrlChange: (value: string) => void;
  repoContext: RepoContext | null;
  selectedIssueNumber: string;
  selectedProjectId: string | null;
  setAutoExtractTodos: (value: boolean) => void;
}) {
  return (
    <div className="border-t border-border/60 p-4">
      <div className="space-y-4">
        {repoContext ? (
          <div className="grid min-w-0 gap-4 md:grid-cols-[minmax(0,1fr)_auto]">
            <div className="grid min-w-0 gap-2">
              <Label htmlFor="issue-select-inline">Select from repository</Label>
              <Select
                value={selectedIssueNumber}
                onValueChange={handleSelectIssue}
                disabled={!isIssuesLoading && issues.length === 0}
              >
                <SelectTrigger
                  id="issue-select-inline"
                  className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
                >
                  <SelectValue
                    placeholder={
                      isIssuesLoading
                        ? "Loading issues..."
                        : issues.length === 0
                          ? "No issues available"
                          : "Select issue"
                    }
                  />
                </SelectTrigger>
                <SelectContent className="max-h-80">
                  {issues.length === 0 ? (
                    <div className="px-2 py-1.5 text-xs text-muted-foreground">
                      No GitHub issues found
                    </div>
                  ) : (
                    issues.map((issue) => (
                      <SelectItem key={issue.number} value={String(issue.number)}>
                        <div className="flex min-w-0 items-center gap-2">
                          <span className="font-mono text-xs text-muted-foreground">
                            #{issue.number}
                          </span>
                          <span className="truncate">{issue.title}</span>
                        </div>
                      </SelectItem>
                    ))
                  )}
                </SelectContent>
              </Select>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="issue-url-inline">Or paste issue URL</Label>
              <div className="flex gap-2">
                <Input
                  id="issue-url-inline"
                  value={issueUrl}
                  onChange={(event) => onIssueUrlChange(event.target.value)}
                  placeholder={`https://github.com/${repoContext.owner}/${repoContext.repo}/issues/40`}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => void handleLoadIssueFromUrl()}
                  disabled={isIssuePreviewLoading || !issueUrl.trim()}
                  title="Load issue"
                >
                  {isIssuePreviewLoading ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <CloudDownload className="size-4" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        ) : selectedProjectId ? (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            This project does not expose a GitHub remote, so issue import is unavailable.
          </div>
        ) : (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            Select a project first to load GitHub issue sync.
          </div>
        )}

        {issueError ? (
          <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
            {issueError}
          </div>
        ) : null}

        {isIssuePreviewLoading ? (
          <div className="flex items-center gap-2 rounded-xl border border-border/70 px-3 py-4 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            Loading issue preview
          </div>
        ) : issuePreview ? (
          <GithubPreviewCard
            bodyFallback="No issue description provided."
            labels={issuePreview.labels}
            owner={issuePreview.owner}
            repo={issuePreview.repo}
            number={issuePreview.number}
            state={issuePreview.state}
            title={issuePreview.title}
            url={issuePreview.url}
            body={issuePreview.body}
          />
        ) : null}

        <AutoExtractTodosCheckbox
          checked={autoExtractTodos}
          description={autoExtractDescription}
          disabled={!canAutoExtractTodos}
          onChange={setAutoExtractTodos}
        />
      </div>
    </div>
  );
}

function PrLinkPanel({
  autoExtractDescription,
  autoExtractTodos,
  canAutoExtractTodos,
  handleLoadPrFromUrl,
  handleSelectPr,
  isPrPreviewLoading,
  isPrsLoading,
  onPrUrlChange,
  prError,
  prPreview,
  prs,
  prUrl,
  repoContext,
  selectedPrNumber,
  selectedProjectId,
  setAutoExtractTodos,
}: {
  autoExtractDescription: string;
  autoExtractTodos: boolean;
  canAutoExtractTodos: boolean;
  handleLoadPrFromUrl: () => void | Promise<void>;
  handleSelectPr: (value: string) => void;
  isPrPreviewLoading: boolean;
  isPrsLoading: boolean;
  onPrUrlChange: (value: string) => void;
  prError: string | null;
  prPreview: GithubPrPayload | null;
  prs: GithubPrPayload[];
  prUrl: string;
  repoContext: RepoContext | null;
  selectedPrNumber: string;
  selectedProjectId: string | null;
  setAutoExtractTodos: (value: boolean) => void;
}) {
  return (
    <div className="border-t border-border/60 p-4">
      <div className="space-y-4">
        {repoContext ? (
          <div className="grid min-w-0 gap-4 md:grid-cols-[minmax(0,1fr)_auto]">
            <div className="grid min-w-0 gap-2">
              <Label htmlFor="pr-select-inline">Select from repository</Label>
              <Select
                value={selectedPrNumber}
                onValueChange={handleSelectPr}
                disabled={!isPrsLoading && prs.length === 0}
              >
                <SelectTrigger
                  id="pr-select-inline"
                  className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
                >
                  <SelectValue
                    placeholder={
                      isPrsLoading
                        ? "Loading PRs..."
                        : prs.length === 0
                          ? "No PRs available"
                          : "Select PR"
                    }
                  />
                </SelectTrigger>
                <SelectContent className="max-h-80">
                  {prs.length === 0 ? (
                    <div className="px-2 py-1.5 text-xs text-muted-foreground">
                      No GitHub PRs found
                    </div>
                  ) : (
                    prs.map((pr) => (
                      <SelectItem key={pr.number} value={String(pr.number)}>
                        <div className="flex min-w-0 items-center gap-2">
                          <span className="font-mono text-xs text-muted-foreground">
                            #{pr.number}
                          </span>
                          <span className="truncate">{pr.title}</span>
                        </div>
                      </SelectItem>
                    ))
                  )}
                </SelectContent>
              </Select>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="pr-url-inline">Or paste PR URL</Label>
              <div className="flex gap-2">
                <Input
                  id="pr-url-inline"
                  value={prUrl}
                  onChange={(event) => onPrUrlChange(event.target.value)}
                  placeholder={`https://github.com/${repoContext.owner}/${repoContext.repo}/pull/40`}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => void handleLoadPrFromUrl()}
                  disabled={isPrPreviewLoading || !prUrl.trim()}
                  title="Load PR"
                >
                  {isPrPreviewLoading ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <CloudDownload className="size-4" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        ) : selectedProjectId ? (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            This project does not expose a GitHub remote, so PR import is unavailable.
          </div>
        ) : (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            Select a project first to load GitHub PRs.
          </div>
        )}

        {prError ? (
          <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
            {prError}
          </div>
        ) : null}

        {isPrPreviewLoading ? (
          <div className="flex items-center gap-2 rounded-xl border border-border/70 px-3 py-4 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            Loading PR preview
          </div>
        ) : prPreview ? (
          <GithubPreviewCard
            bodyFallback="No PR description provided."
            labels={prPreview.labels}
            owner={prPreview.owner}
            repo={prPreview.repo}
            number={prPreview.number}
            state={prPreview.is_draft ? "draft" : prPreview.state}
            title={prPreview.title}
            url={prPreview.url}
            body={prPreview.body}
            branchMeta={
              <>
                <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
                  <span className="inline-flex items-center gap-1">
                    <GitBranch className="size-3" />
                    {prPreview.head_ref}
                  </span>
                  <span className="opacity-50">→</span>
                  <span className="inline-flex items-center gap-1">
                    <GitBranch className="size-3" />
                    {prPreview.base_ref}
                  </span>
                </div>
                <div className="rounded-md border border-border/70 bg-background/40 px-3 py-2 text-[11px] text-muted-foreground">
                  The workspace will reuse <span className="font-mono text-foreground">{prPreview.head_ref}</span> directly — no new branch will be created.
                </div>
              </>
            }
          />
        ) : null}

        <AutoExtractTodosCheckbox
          checked={autoExtractTodos}
          description={autoExtractDescription}
          disabled={!canAutoExtractTodos}
          onChange={setAutoExtractTodos}
        />
      </div>
    </div>
  );
}

function GithubPreviewCard({
  body,
  bodyFallback,
  branchMeta,
  labels,
  number,
  owner,
  repo,
  state,
  title,
  url,
}: {
  body: string | null;
  bodyFallback: string;
  branchMeta?: React.ReactNode;
  labels: Array<{ name: string }>;
  number: number;
  owner: string;
  repo: string;
  state: string;
  title: string;
  url: string;
}) {
  return (
    <Card className="rounded-xl border border-border/70 bg-muted/20 shadow-none">
      <CardContent className="space-y-3 p-4">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground">
                {owner}/{repo}#{number}
              </span>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="h-6 gap-1 rounded-md px-2 text-[11px]"
                onClick={() => window.open(url, "_blank", "noopener,noreferrer")}
              >
                <ExternalLink className="size-3" />
                Open on GitHub
              </Button>
            </div>
            <h3 className="mt-1 truncate text-sm font-medium text-foreground">
              {title}
            </h3>
            {branchMeta}
          </div>
          <Badge variant="secondary" className="rounded-full capitalize">
            {state}
          </Badge>
        </div>

        {labels.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {labels.map((label) => (
              <Badge key={label.name} variant="outline" className="rounded-full">
                {label.name}
              </Badge>
            ))}
          </div>
        ) : null}

        <p className="line-clamp-6 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">
          {body?.trim() || bodyFallback}
        </p>
      </CardContent>
    </Card>
  );
}

function AutoExtractTodosCheckbox({
  checked,
  description,
  disabled,
  onChange,
}: {
  checked: boolean;
  description: string;
  disabled: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <label className="flex items-center gap-3 rounded-xl border border-border/70 px-3 py-3 text-sm">
      <Checkbox
        checked={checked}
        onCheckedChange={(nextChecked) => onChange(Boolean(nextChecked))}
        disabled={disabled}
      />
      <div className="min-w-0">
        <div className="flex items-center gap-2 font-medium text-foreground">
          <Sparkles className="size-4 text-muted-foreground" />
          Auto-extract TODOs with LLM
        </div>
        <p className="mt-1 text-xs text-muted-foreground">
          {description}
        </p>
      </div>
    </label>
  );
}
