export const copy = {
  newChat: "New chat",
  emptyTitle: "Start chatting",
  emptyDescription: "Send a message to begin this chat.",
  placeholder: "Send a message to create a session",
  resumePlaceholder: "Send a message to resume the session",
  connectedPlaceholder: "Do anything with {agent}",
  send: "Send",
  stop: "Stop",
  queue: "Queue",
  steer: "Steer",
  agent: "Agent",
  model: "Model",
  thinking: "Thinking",
  permissionTitle: "Permission needed",
  sendFailed: "Could not send that message",
  history: "Chats",
  messages: "Messages",
  parameters: "Parameters",
  result: "Result",
  rename: "Rename chat",
  deleteChat: "Delete",
  attach: "Attach",
  context: "Context",
  close: "Close",
  mode: "Mode",
  permission: "Permission",
  add: "Add",
  photos: "Photos",
  allowPhotos: "Allow photo access",
  photosNeedRebuild: "Rebuild the app to attach photos.",
  effort: "Effort",
  fast: "Fast",
  favorites: "Favorites",
  searchModels: "Search models",
  noFavorites: "No favorites yet",
  noModels: "No models",
  addFavorite: "Add favorite",
  removeFavorite: "Remove favorite",
} as const;
