import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getMobileCssVariables } from "../src/theme/css-variables";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const variables = getMobileCssVariables("light");
const sortedEntries = Object.entries(variables).sort(([left], right) => left.localeCompare(right));

const cssPath = resolve(rootDir, "src/theme/generated-theme.css");
const cssLines = sortedEntries.map(([name, value]) => `  ${name}: ${value};`);
const css = `/* Generated by script/generate-mobile-global-theme.ts — do not edit */\n@theme {\n${cssLines.join("\n")}\n}\n`;
writeFileSync(cssPath, css, "utf8");

const snapshotPath = resolve(rootDir, "src/theme/generated-theme.snapshot.ts");
const snapshotLines = sortedEntries.map(([name, value]) => `  "${name}": "${value}",`);
const snapshot = `/* Generated by script/generate-mobile-global-theme.ts — do not edit */\nexport const mobileGeneratedThemeSnapshot = {\n${snapshotLines.join("\n")}\n} as const;\n`;
writeFileSync(snapshotPath, snapshot, "utf8");

console.log(`Wrote ${cssPath}`);
console.log(`Wrote ${snapshotPath}`);
