import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Badge,
  Button,
  Card,
  CardContent,
  Checkbox,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  Input,
  Label,
  ScrollArea,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@workspace/ui';
import { cn } from '@/lib/utils';
import {
  Check,
  ChevronDown,
  CircleDot,
  CloudDownload,
  ExternalLink,
  GitBranch,
  GitPullRequestArrow,
  Github,
  Loader2,
  RotateCw,
  Sparkles,
} from 'lucide-react';
import type { WorkspacePriority, WorkspaceWorkflowStatus, WorkspaceLabel } from '@/types/types';
import {
  WorkspaceLabelDots,
  WorkspaceLabelPicker,
  WorkspacePrioritySelect,
  WorkspaceStatusSelect,
} from '@/components/layout/sidebar/workspace-metadata-controls';
import { useProjectStore } from '@/hooks/use-project-store';
import {
  gitApi,
  llmProvidersApi,
  type GithubIssuePayload,
  type GithubPrPayload,
  type LlmProvidersFile,
  wsScriptApi,
  wsGithubApi,
} from '@/api/ws-api';
import { useAppRouter } from '@/hooks/use-app-router';
import { useWorkspaceCreationStore } from '@/hooks/use-workspace-creation-store';

interface CreateWorkspaceDialogProps {
  isOpen: boolean;
  onClose: () => void;
  defaultProjectId?: string;
  defaultWorkflowStatus?: WorkspaceWorkflowStatus;
  projectSelectionInHeader?: boolean;
  requireProjectSelection?: boolean;
  // Build from Issue Only mode
  preselectedIssue?: GithubIssuePayload;
  sourceWorkspaceId?: string;
}

interface RepoContext {
  owner: string;
  repo: string;
}

const ISSUE_CACHE_TTL_MS = 5 * 60 * 1000;
const issueListCache = new Map<string, { expiresAt: number; issues: GithubIssuePayload[] }>();
const prListCache = new Map<string, { expiresAt: number; prs: GithubPrPayload[] }>();

const POKEMON_NAMES = [
  'bulbasaur',
  'ivysaur',
  'venusaur',
  'charmander',
  'charmeleon',
  'charizard',
  'squirtle',
  'wartortle',
  'blastoise',
  'butterfree',
  'pikachu',
  'raichu',
  'vulpix',
  'jigglypuff',
  'zubat',
  'psyduck',
  'growlithe',
  'abra',
  'machop',
  'geodude',
  'ponyta',
  'slowpoke',
  'magnemite',
  'gastly',
  'gengar',
  'onix',
  'cubone',
  'chansey',
  'scyther',
  'magikarp',
  'gyarados',
  'lapras',
  'eevee',
  'vaporeon',
  'jolteon',
  'flareon',
  'snorlax',
  'articuno',
  'zapdos',
  'moltres',
  'dragonite',
  'mew',
  'mewtwo',
] as const;

function getRandomPokemonName(): string {
  const index = Math.floor(Math.random() * POKEMON_NAMES.length);
  return POKEMON_NAMES[index];
}

function issueToWorkspaceName(issue: GithubIssuePayload): string {
  const title = issue.title.trim();
  return title ? `[issue#${issue.number}] ${title}` : `[issue#${issue.number}]`;
}

function issueToBranchName(issue: GithubIssuePayload): string {
  return `issue-${issue.number}-${getRandomPokemonName()}`;
}

function prToWorkspaceName(pr: GithubPrPayload): string {
  const title = pr.title.trim();
  return title ? `[PR#${pr.number}] ${title}` : `[PR#${pr.number}]`;
}

function regeneratePokemonSuffixBranch(branchName: string, issueNumber?: number): string {
  const randomPokemon = getRandomPokemonName();

  if (typeof issueNumber === 'number') {
    return `issue-${issueNumber}-${randomPokemon}`;
  }

  const matchedIssue = branchName.trim().match(/^issue-(\d+)(?:-.+)?$/i);
  if (matchedIssue?.[1]) {
    return `issue-${matchedIssue[1]}-${randomPokemon}`;
  }

  return branchName.trim()
    ? `${branchName.trim()}-${randomPokemon}`
    : `issue-${Math.floor(Math.random() * 1000)}-${randomPokemon}`;
}

function resolveWorkspaceIssueTodoProvider(
  config: LlmProvidersFile,
): { id: string; label: string } | null {
  const providerId = config.features.workspace_issue_todo ?? null;
  if (!providerId) return null;

  const provider = config.providers[providerId];
  if (!provider?.enabled) return null;

  return {
    id: providerId,
    label: provider.displayName?.trim() || providerId,
  };
}

function sanitizeCreateWorkspaceErrorMessage(message: string): string {
  return message
    .replace(/^\[error\]\s*/i, '')
    .replace(/^validation error:\s*/i, '')
    .trim();
}

function isBranchConflictError(message: string): boolean {
  const normalized = message.toLowerCase();
  return (
    normalized.includes('branch `') ||
    normalized.includes('workspace directory') ||
    normalized.includes('directory name') ||
    normalized.includes('conflicts with an existing branch or workspace') ||
    normalized.includes('branch name already exists') ||
    normalized.includes('branch already exists')
  );
}

function isAutoGeneratedBranchConflictError(message: string): boolean {
  return message
    .toLowerCase()
    .includes('auto-generated workspace directory name');
}

export const CreateWorkspaceDialog: React.FC<CreateWorkspaceDialogProps> = ({
  isOpen,
  onClose,
  defaultProjectId,
  defaultWorkflowStatus,
  projectSelectionInHeader = false,
  requireProjectSelection = false,
  preselectedIssue,
  sourceWorkspaceId,
}: CreateWorkspaceDialogProps) => {
  const router = useAppRouter();
  const projects = useProjectStore((s) => s.projects);
  const addWorkspace = useProjectStore((s) => s.addWorkspace);
  const showCreating = useWorkspaceCreationStore((s) => s.showCreating);
  const showOpening = useWorkspaceCreationStore((s) => s.showOpening);
  const clearWorkspaceCreationOverlay = useWorkspaceCreationStore((s) => s.clear);

  const [projectId, setProjectId] = useState(() => {
    if (defaultProjectId) return defaultProjectId;
    if (requireProjectSelection) return '';
    return projects.length > 0 ? projects[0].id : '';
  });
  const [name, setName] = useState('');
  const [branch, setBranch] = useState('');
  const [baseBranch, setBaseBranch] = useState('main');
  const [remoteBranches, setRemoteBranches] = useState<string[]>([]);
  const [baseBranchFilter, setBaseBranchFilter] = useState('');
  const [isBaseBranchOpen, setIsBaseBranchOpen] = useState(false);
  const [issueUrl, setIssueUrl] = useState('');
  const [selectedIssueNumber, setSelectedIssueNumber] = useState<string>('');
  const [issuePreview, setIssuePreview] = useState<GithubIssuePayload | null>(null);
  const [issues, setIssues] = useState<GithubIssuePayload[]>([]);
  const [prUrl, setPrUrl] = useState('');
  const [selectedPrNumber, setSelectedPrNumber] = useState<string>('');
  const [prPreview, setPrPreview] = useState<GithubPrPayload | null>(null);
  const [prs, setPrs] = useState<GithubPrPayload[]>([]);
  const [prError, setPrError] = useState<string | null>(null);
  const [isPrsLoading, setIsPrsLoading] = useState(false);
  const [isPrPreviewLoading, setIsPrPreviewLoading] = useState(false);
  const [repoContext, setRepoContext] = useState<RepoContext | null>(null);
  const [isRepoLoading, setIsRepoLoading] = useState(false);
  const [isBaseBranchesLoading, setIsBaseBranchesLoading] = useState(false);
  const [isIssuesLoading, setIsIssuesLoading] = useState(false);
  const [isIssuePreviewLoading, setIsIssuePreviewLoading] = useState(false);
  const [isLlmRoutingLoading, setIsLlmRoutingLoading] = useState(false);
  const [hasSetupScript, setHasSetupScript] = useState(false);
  const [issueError, setIssueError] = useState<string | null>(null);
  const [branchError, setBranchError] = useState<string | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [autoExtractTodos, setAutoExtractTodos] = useState(false);
  const [autoExtractTodosPr, setAutoExtractTodosPr] = useState(false);
  const [linkType, setLinkType] = useState<'none' | 'issue' | 'pr'>('none');
  const [displayedLinkType, setDisplayedLinkType] = useState<'issue' | 'pr'>('issue');
  useEffect(() => {
    if (linkType !== 'none') setDisplayedLinkType(linkType);
  }, [linkType]);
  const [todoProviderLabel, setTodoProviderLabel] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Metadata states - defaults: no_priority, in_progress, empty labels
  const [priority, setPriority] = useState<WorkspacePriority>('no_priority');
  const [workflowStatus, setWorkflowStatus] = useState<WorkspaceWorkflowStatus>(
    defaultWorkflowStatus ?? 'in_progress',
  );
  const [selectedLabels, setSelectedLabels] = useState<WorkspaceLabel[]>([]);

  const workspaceLabels = useProjectStore(s => s.workspaceLabels);
  const createWorkspaceLabel = useProjectStore(s => s.createWorkspaceLabel);

  const nameTouchedRef = useRef(false);
  const branchTouchedRef = useRef(false);
  const generatedBranchRef = useRef<string | null>(null);
  const branchFieldRef = useRef<HTMLDivElement | null>(null);
  const branchInputRef = useRef<HTMLInputElement | null>(null);

  const selectedProject = useMemo(
    () => projects.find((project) => project.id === projectId) ?? null,
    [projectId, projects],
  );
  const selectedProjectId = selectedProject?.id ?? null;
  const selectedProjectPath = selectedProject?.mainFilePath ?? null;

  useEffect(() => {
    if (defaultProjectId) {
      setProjectId(defaultProjectId);
      return;
    }

    if (!projectId && projects.length > 0 && !requireProjectSelection) {
      setProjectId(projects[0].id);
    }
  }, [defaultProjectId, projectId, projects, requireProjectSelection]);

  useEffect(() => {
    if (!isOpen) return;
    setWorkflowStatus(defaultWorkflowStatus ?? 'in_progress');
  }, [defaultWorkflowStatus, isOpen]);

  useEffect(() => {
    if (!isOpen) {
      setProjectId(
        defaultProjectId || (!requireProjectSelection && projects.length > 0 ? projects[0].id : ''),
      );
      setName('');
      setBranch('');
      setBaseBranch('main');
      setRemoteBranches([]);
      setBaseBranchFilter('');
      setIsBaseBranchOpen(false);
      setIssueUrl('');
      setSelectedIssueNumber('');
      setIssuePreview(null);
      setIssues([]);
      setPrUrl('');
      setSelectedPrNumber('');
      setPrPreview(null);
      setPrs([]);
      setPrError(null);
      setIsPrsLoading(false);
      setIsPrPreviewLoading(false);
      setIsRepoLoading(false);
      setIsBaseBranchesLoading(false);
      setIsIssuesLoading(false);
      setIsIssuePreviewLoading(false);
      setIsLlmRoutingLoading(false);
      setHasSetupScript(false);
      setIssueError(null);
      setBranchError(null);
      setSubmitError(null);
      setAutoExtractTodos(false);
      setAutoExtractTodosPr(false);
      setLinkType('none');
      setDisplayedLinkType('issue');
      setTodoProviderLabel(null);
      setIsSubmitting(false);
      setPriority('no_priority');
      setWorkflowStatus(defaultWorkflowStatus ?? 'in_progress');
      setSelectedLabels([]);
    }
  }, [defaultProjectId, isOpen, projects, requireProjectSelection, defaultWorkflowStatus]);

  // Handle preselectedIssue for Build from Issue Only mode
  useEffect(() => {
    if (isOpen && preselectedIssue) {
      setIssuePreview(preselectedIssue);
      setIssueUrl(preselectedIssue.url);
      setSelectedIssueNumber(preselectedIssue.number.toString());
      setLinkType('issue');
      setDisplayedLinkType('issue');
      // Auto-fill workspace name and branch from issue
      const workspaceName = issueToWorkspaceName(preselectedIssue);
      const branchName = issueToBranchName(preselectedIssue);
      setName(workspaceName);
      setBranch(branchName);
    }
  }, [isOpen, preselectedIssue]);

  useEffect(() => {
    let cancelled = false;

    async function loadLlmRouting() {
      if (!isOpen) {
        return;
      }

      setIsLlmRoutingLoading(true);
      try {
        const config = await llmProvidersApi.get();
        if (cancelled) return;

        const provider = resolveWorkspaceIssueTodoProvider(config);
        setTodoProviderLabel(provider?.label ?? null);
      } catch {
        if (!cancelled) {
          setTodoProviderLabel(null);
        }
      } finally {
        if (!cancelled) {
          setIsLlmRoutingLoading(false);
        }
      }
    }

    loadLlmRouting();
    return () => {
      cancelled = true;
    };
  }, [isOpen]);

  useEffect(() => {
    let cancelled = false;

    async function loadRepoContext() {
      if (!isOpen || !selectedProjectId || !selectedProjectPath) {
        return;
      }

      setIsRepoLoading(true);
      setIsBaseBranchesLoading(true);
      setIssueError(null);
      setRepoContext(null);
      setRemoteBranches([]);
      setIssues([]);
      setIssuePreview(null);
      setSelectedIssueNumber('');
      setIssueUrl('');
      setPrs([]);
      setPrPreview(null);
      setSelectedPrNumber('');
      setPrUrl('');
      setPrError(null);
      setLinkType('none');
      setAutoExtractTodos(false);
      setAutoExtractTodosPr(false);
      setHasSetupScript(false);

      try {
        const fetchedRemoteBranches = await gitApi.listRemoteBranches(selectedProjectPath);
        if (!cancelled) {
          const nextRemoteBranches = fetchedRemoteBranches.sort();
          setRemoteBranches(nextRemoteBranches);
          if (nextRemoteBranches.includes('main')) {
            setBaseBranch('main');
          } else if (nextRemoteBranches.length > 0) {
            setBaseBranch(nextRemoteBranches[0]);
          } else {
            setBaseBranch('main');
          }
        }

        const scripts = await wsScriptApi.get(selectedProjectId);
        if (!cancelled) {
          setHasSetupScript(
            typeof scripts.setup === 'string' && scripts.setup.trim().length > 0,
          );
        }

        const status = await gitApi.getStatus(selectedProjectPath);
        if (cancelled) return;

        if (status.github_owner && status.github_repo) {
          const nextContext = {
            owner: status.github_owner,
            repo: status.github_repo,
          };
          setRepoContext(nextContext);

          const cacheKey = `${nextContext.owner}/${nextContext.repo}`;
          const cachedIssues = issueListCache.get(cacheKey);
          if (cachedIssues && cachedIssues.expiresAt > Date.now()) {
            setIssues(cachedIssues.issues);
          } else {
            setIsIssuesLoading(true);
            const fetchedIssues = await wsGithubApi.listIssues(nextContext);
            if (cancelled) return;
            setIssues(fetchedIssues);
            issueListCache.set(cacheKey, {
              expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
              issues: fetchedIssues,
            });
          }

          const cachedPrs = prListCache.get(cacheKey);
          if (cachedPrs && cachedPrs.expiresAt > Date.now()) {
            setPrs(cachedPrs.prs);
          } else {
            setIsPrsLoading(true);
            try {
              const fetchedPrs = await wsGithubApi.listPrs(nextContext);
              if (cancelled) return;
              setPrs(fetchedPrs);
              prListCache.set(cacheKey, {
                expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
                prs: fetchedPrs,
              });
            } catch (error) {
              if (!cancelled) {
                setPrError(error instanceof Error ? error.message : 'Failed to load GitHub PRs');
              }
            }
          }
        }
      } catch (error) {
        if (!cancelled) {
          setIssueError(error instanceof Error ? error.message : 'Failed to load GitHub issues');
        }
      } finally {
        if (!cancelled) {
          setIsRepoLoading(false);
          setIsBaseBranchesLoading(false);
          setIsIssuesLoading(false);
          setIsPrsLoading(false);
        }
      }
    }

    loadRepoContext();
    return () => {
      cancelled = true;
    };
  }, [isOpen, selectedProjectId, selectedProjectPath]);

  useEffect(() => {
    if (!issuePreview) {
      if (!prPreview) {
        generatedBranchRef.current = null;
      }
      return;
    }

    if (!nameTouchedRef.current) {
      setName(issueToWorkspaceName(issuePreview));
    }
    if (!branchTouchedRef.current) {
      const generated = issueToBranchName(issuePreview);
      generatedBranchRef.current = generated;
      setBranch(generated);
    }
  }, [issuePreview, prPreview]);

  useEffect(() => {
    if (!prPreview) return;

    if (!nameTouchedRef.current) {
      setName(prToWorkspaceName(prPreview));
    }
    setBranch(prPreview.head_ref);
    if (prPreview.base_ref) {
      setBaseBranch(prPreview.base_ref);
    }
  }, [prPreview]);

  useEffect(() => {
    if (!issuePreview || !todoProviderLabel) setAutoExtractTodos(false);
  }, [issuePreview, todoProviderLabel]);

  useEffect(() => {
    if (!prPreview || !todoProviderLabel) setAutoExtractTodosPr(false);
  }, [prPreview, todoProviderLabel]);

  const clearPrSelection = () => {
    setPrPreview(null);
    setSelectedPrNumber('');
    setPrUrl('');
    setPrError(null);
    setAutoExtractTodosPr(false);
  };

  const clearIssueSelection = () => {
    setIssuePreview(null);
    setSelectedIssueNumber('');
    setIssueUrl('');
    setIssueError(null);
    setAutoExtractTodos(false);
  };

  const handleSelectLinkType = (next: 'issue' | 'pr') => {
    if (preselectedIssue) {
      return;
    }

    if (linkType === next) {
      setLinkType('none');
      if (next === 'issue') clearIssueSelection();
      else clearPrSelection();
      return;
    }
    setLinkType(next);
    if (next === 'issue') clearPrSelection();
    else clearIssueSelection();
  };

  const handleSelectIssue = async (value: string) => {
    setSelectedIssueNumber(value);
    setIssueUrl('');
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);

    const selected = issues.find((issue) => String(issue.number) === value) ?? null;
    setIssuePreview(selected);
    clearPrSelection();
  };

  const handleSelectPr = (value: string) => {
    setSelectedPrNumber(value);
    setPrUrl('');
    setPrError(null);
    setBranchError(null);
    setSubmitError(null);
    const selected = prs.find((pr) => String(pr.number) === value) ?? null;
    setPrPreview(selected);
    clearIssueSelection();
  };

  const handleLoadPrFromUrl = async () => {
    if (!prUrl.trim()) {
      setPrError(null);
      return;
    }
    setIsPrPreviewLoading(true);
    setPrError(null);
    setBranchError(null);
    setSubmitError(null);
    setSelectedPrNumber('');
    try {
      const preview = await wsGithubApi.getPr({ prUrl: prUrl.trim() });
      const currentRepo = repoContext ? `${repoContext.owner}/${repoContext.repo}` : null;
      const previewRepo = `${preview.owner}/${preview.repo}`;
      if (currentRepo && currentRepo !== previewRepo) {
        setPrPreview(null);
        setPrError(`PR belongs to ${previewRepo}, but current project is ${currentRepo}.`);
        return;
      }
      setPrPreview(preview);
      clearIssueSelection();
    } catch (error) {
      setPrPreview(null);
      setPrError(error instanceof Error ? error.message : 'Failed to load PR preview');
    } finally {
      setIsPrPreviewLoading(false);
    }
  };

  const handleRefreshPrs = async () => {
    if (!repoContext) return;
    setIsPrsLoading(true);
    setPrError(null);
    try {
      const cacheKey = `${repoContext.owner}/${repoContext.repo}`;
      prListCache.delete(cacheKey);
      const fetchedPrs = await wsGithubApi.listPrs(repoContext);
      setPrs(fetchedPrs);
      prListCache.set(cacheKey, {
        expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
        prs: fetchedPrs,
      });
    } catch (error) {
      setPrError(error instanceof Error ? error.message : 'Failed to refresh GitHub PRs');
    } finally {
      setIsPrsLoading(false);
    }
  };

  const handleLoadIssueFromUrl = async () => {
    if (!issueUrl.trim()) {
      setIssueError(null);
      return;
    }

    setIsIssuePreviewLoading(true);
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);
    setSelectedIssueNumber('');

    try {
      const preview = await wsGithubApi.getIssue({ issueUrl: issueUrl.trim() });
      const currentRepo = repoContext ? `${repoContext.owner}/${repoContext.repo}` : null;
      const previewRepo = `${preview.owner}/${preview.repo}`;

      if (currentRepo && currentRepo !== previewRepo) {
        setIssuePreview(null);
        setIssueError(`Issue belongs to ${previewRepo}, but current project is ${currentRepo}.`);
        return;
      }

      setIssuePreview(preview);
      clearPrSelection();
    } catch (error) {
      setIssuePreview(null);
      setIssueError(error instanceof Error ? error.message : 'Failed to load issue preview');
    } finally {
      setIsIssuePreviewLoading(false);
    }
  };

  const handleRefreshIssues = async () => {
    if (!repoContext) return;
    setIsIssuesLoading(true);
    setIssueError(null);
    try {
      const cacheKey = `${repoContext.owner}/${repoContext.repo}`;
      issueListCache.delete(cacheKey);
      const fetchedIssues = await wsGithubApi.listIssues(repoContext);
      setIssues(fetchedIssues);
      issueListCache.set(cacheKey, {
        expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
        issues: fetchedIssues,
      });
    } catch (error) {
      setIssueError(error instanceof Error ? error.message : 'Failed to refresh GitHub issues');
    } finally {
      setIsIssuesLoading(false);
    }
  };

  const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    nameTouchedRef.current = true;
    setBranchError(null);
    setSubmitError(null);
    setName(event.target.value);
  };

  const handleBranchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    branchTouchedRef.current = true;
    setBranchError(null);
    setSubmitError(null);
    setBranch(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!projectId) return;

    let keepGlobalLoading = false;
    setIsSubmitting(true);
    showCreating();
    setBranchError(null);
    setSubmitError(null);
    try {
      const finalDisplayName = prPreview
        ? name.trim() || prToWorkspaceName(prPreview)
        : name.trim() || (issuePreview ? issueToWorkspaceName(issuePreview) : '');
      const finalBranch = prPreview
        ? prPreview.head_ref
        : branch.trim() ||
          (!branchTouchedRef.current && generatedBranchRef.current) ||
          (issuePreview ? issueToBranchName(issuePreview) : '');
      const finalBaseBranch = prPreview ? prPreview.base_ref || baseBranch : baseBranch;
      const workspaceId = await addWorkspace({
        projectId,
        name: finalBranch,
        displayName: finalDisplayName || null,
        branch: finalBranch,
        baseBranch: finalBaseBranch,
        initialRequirement: null,
        githubIssue: prPreview ? null : issuePreview,
        githubPr: prPreview,
        autoExtractTodos:
          !!todoProviderLabel &&
          ((prPreview && autoExtractTodosPr) || (!prPreview && !!issuePreview && autoExtractTodos)),
        hasSetupScript,
        priority,
        workflowStatus,
        labels: selectedLabels,
      });
      keepGlobalLoading = true;
      showOpening(workspaceId);
      onClose();
      router.push(`/workspace?id=${workspaceId}`);
    } catch (error) {
      clearWorkspaceCreationOverlay();
      const message = sanitizeCreateWorkspaceErrorMessage(
        error instanceof Error ? error.message : 'Failed to create workspace',
      );

      if (isBranchConflictError(message)) {
        setBranchError(message);
        requestAnimationFrame(() => {
          branchFieldRef.current?.scrollIntoView({
            behavior: 'smooth',
            block: 'center',
          });
          branchInputRef.current?.focus();
        });
      } else {
        setSubmitError(message);
      }
    } finally {
      if (!keepGlobalLoading) {
        setIsSubmitting(false);
      }
    }
  };

  const handleRegenerateBranch = () => {
    const nextBranch = regeneratePokemonSuffixBranch(branch, issuePreview?.number);
    branchTouchedRef.current = true;
    setBranch(nextBranch);
    setBranchError(null);
    setSubmitError(null);
    requestAnimationFrame(() => {
      branchInputRef.current?.focus();
    });
  };

  const repoLabel = repoContext ? `${repoContext.owner}/${repoContext.repo}` : 'No GitHub repository';
  const issueBodyPreview = issuePreview?.body?.trim() || 'No issue description provided.';
  const hasGithubContext = !!issuePreview || !!prPreview;
  const canAutoExtractTodosIssue = !!issuePreview && !!todoProviderLabel && !isLlmRoutingLoading;
  const canAutoExtractTodosPr = !!prPreview && !!todoProviderLabel && !isLlmRoutingLoading;
  const filteredRemoteBranches = useMemo(
    () => remoteBranches.filter((remoteBranch) =>
      remoteBranch.toLowerCase().includes(baseBranchFilter.trim().toLowerCase()),
    ),
    [remoteBranches, baseBranchFilter],
  );
  const buildAutoExtractDescription = (kind: 'issue' | 'pr') => {
    const hasPreview = kind === 'issue' ? !!issuePreview : !!prPreview;
    if (!hasPreview) return `Import a GitHub ${kind === 'pr' ? 'PR' : 'issue'} first.`;
    if (isLlmRoutingLoading) return 'Checking LLM routing...';
    if (todoProviderLabel)
      return `Uses ${todoProviderLabel} to extract an initial task checklist from the ${kind === 'pr' ? 'PR' : 'issue'} description.`;
    return 'Configure LLM Providers > Routing > Workspace issue TODO extraction first.';
  };
  const autoExtractDescriptionIssue = buildAutoExtractDescription('issue');
  const autoExtractDescriptionPr = buildAutoExtractDescription('pr');
  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[720px] max-h-[80vh] overflow-y-auto [scrollbar-gutter:stable] gap-4 bg-background p-6 pt-7">
        <DialogHeader className="flex flex-row items-start justify-between gap-4 pr-8">
          <DialogTitle>{preselectedIssue ? 'Build Workspace from Issue' : 'Create New Workspace'}</DialogTitle>
          <div className="flex items-center gap-2 text-xs text-muted-foreground shrink-0">
            <Github className="size-3.5" />
            {!projectSelectionInHeader ? (
              <>
                <span>{selectedProject?.name ?? 'Unknown project'}</span>
                <span className="opacity-40">•</span>
              </>
            ) : null}
            {isRepoLoading ? (
              <span className="inline-flex items-center gap-1">
                <Loader2 className="size-3 animate-spin" />
                Detecting repository
              </span>
            ) : (
              <span>{repoLabel}</span>
            )}
          </div>
        </DialogHeader>
        <div className="-mx-6 border-b border-border/60" />

        <form onSubmit={handleSubmit} className="flex flex-col">
          <div className="pr-1 pt-2 space-y-5">
            {!defaultProjectId && projectSelectionInHeader && (
              <div className="grid gap-2">
                <Label htmlFor="project-inline">Project</Label>
                <Select value={projectId} onValueChange={setProjectId}>
                  <SelectTrigger id="project-inline">
                    <SelectValue placeholder="Please select a project" />
                  </SelectTrigger>
                  <SelectContent>
                    {projects.map((project) => (
                      <SelectItem key={project.id} value={project.id}>
                        {project.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {!projectId ? (
                  <p className="text-xs text-destructive">
                    Please select a project to continue.
                  </p>
                ) : null}
              </div>
            )}

            {!defaultProjectId && !projectSelectionInHeader && (
              <div className="grid gap-2">
                <Label htmlFor="project">Project</Label>
                <Select
                  value={projectId}
                  onValueChange={setProjectId}
                  disabled={!!defaultProjectId}
                >
                  <SelectTrigger id="project">
                    <SelectValue placeholder="Select a project" />
                  </SelectTrigger>
                  <SelectContent>
                    {projects.map((project) => (
                      <SelectItem key={project.id} value={project.id}>
                        {project.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="workspace-name">Name</Label>
                <Input
                  id="workspace-name"
                  value={name}
                  onChange={handleNameChange}
                  placeholder="Workspace display name, typing..."
                  autoFocus
                />
                <p className="text-xs text-muted-foreground">
                  Leave empty to let Atmos generate a name, or import one from a GitHub issue.
                </p>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="workspace-base-branch-trigger">Base branch</Label>
                <DropdownMenu
                  open={isBaseBranchOpen}
                  onOpenChange={(open) => {
                    setIsBaseBranchOpen(open);
                    if (open) setBaseBranchFilter('');
                  }}
                >
                  <DropdownMenuTrigger asChild>
                    <button
                      id="workspace-base-branch-trigger"
                      type="button"
                      disabled={isBaseBranchesLoading || remoteBranches.length === 0}
                      className="border-input placeholder:text-muted-foreground ring-offset-background focus-visible:border-ring focus-visible:ring-ring/50 dark:bg-input/30 flex h-9 w-full min-w-0 items-center justify-between rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
                    >
                      <div className="flex items-center min-w-0 text-muted-foreground">
                        <span className="opacity-50 shrink-0 mr-1">origin/</span>
                        <span className="truncate">{baseBranch}</span>
                      </div>
                      <ChevronDown className="size-4 opacity-40 ml-2 shrink-0" />
                    </button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start" className="w-[var(--radix-dropdown-menu-trigger-width)] p-3 bg-background overflow-visible">
                    <div className="space-y-2">
                      <p className="text-[12px] text-muted-foreground">Select target branch</p>
                      <Input
                        value={baseBranchFilter}
                        onChange={(e) => setBaseBranchFilter(e.target.value)}
                        onKeyDown={(e) => e.stopPropagation()}
                        placeholder="Search branches..."
                        className="h-8 text-[12px] bg-background"
                      />
                    </div>
                    <ScrollArea className="h-[240px] mt-2 overflow-x-auto">
                      <div className="p-1 w-max min-w-full">
                        {isBaseBranchesLoading ? (
                          <div className="p-2 text-[12px] text-muted-foreground text-center">Loading branches...</div>
                        ) : filteredRemoteBranches.length > 0 ? (
                          filteredRemoteBranches.map((remoteBranch) => (
                            <DropdownMenuItem
                              key={remoteBranch}
                              onClick={() => setBaseBranch(remoteBranch)}
                              className={cn(
                                'flex items-center justify-between text-[13px] cursor-pointer whitespace-nowrap min-w-max',
                                baseBranch === remoteBranch && 'bg-accent text-accent-foreground font-medium',
                              )}
                            >
                              <div className="flex items-center whitespace-nowrap">
                                {baseBranch === remoteBranch ? (
                                  <Check className="size-3.5 mr-2 text-emerald-500 shrink-0" />
                                ) : (
                                  <GitBranch className="size-3.5 mr-2 text-muted-foreground shrink-0" />
                                )}
                                <span className="text-muted-foreground/60 mr-1">origin/</span>
                                <span>{remoteBranch}</span>
                              </div>
                            </DropdownMenuItem>
                          ))
                        ) : (
                          <div className="p-2 text-[12px] text-muted-foreground text-center">No matching branches</div>
                        )}
                      </div>
                    </ScrollArea>
                  </DropdownMenuContent>
                </DropdownMenu>
                <p className="text-xs text-muted-foreground">
                  Workspace worktree and downstream Git comparisons will use this remote branch.
                </p>
                {!!selectedProjectId && !isBaseBranchesLoading && remoteBranches.length === 0 && (
                  <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                    No remote branches found for this project.
                  </div>
                )}
              </div>

              <div ref={branchFieldRef} className="grid gap-2">
                <Label htmlFor="workspace-branch">Current workspace branch</Label>
                <Input
                  id="workspace-branch"
                  ref={branchInputRef}
                  value={branch}
                  onChange={handleBranchChange}
                  placeholder="Workspace branch, typing..."
                />
                {branchError && (
                  <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                    <span>{branchError}</span>
                    {isAutoGeneratedBranchConflictError(branchError) && (
                      <Button
                        type="button"
                        variant="link"
                        className="ml-1 h-auto p-0 text-xs align-baseline"
                        onClick={handleRegenerateBranch}
                      >
                        Random generate again
                      </Button>
                    )}
                  </div>
                )}
                <p className="text-xs text-muted-foreground">
                  Branch name is independent from the displayed workspace name.
                </p>
              </div>
            </div>

            <div className="mt-1 rounded-md border border-border bg-background">
              <div className="flex items-center gap-2 p-1.5">
              <button
                type="button"
                onClick={() => handleSelectLinkType('issue')}
                disabled={!!preselectedIssue}
                className={cn(
                  'inline-flex flex-1 items-center justify-center gap-2 rounded-md px-3 py-2 text-sm transition-colors',
                  linkType === 'issue'
                    ? 'bg-muted text-foreground shadow-sm'
                    : 'text-muted-foreground hover:bg-muted/60 hover:text-foreground',
                  preselectedIssue && 'cursor-not-allowed opacity-80',
                )}
              >
                <CircleDot className="size-4" />
                <span className="font-medium">GitHub Issue</span>
              </button>
              <button
                type="button"
                onClick={() => handleSelectLinkType('pr')}
                disabled={!!preselectedIssue}
                className={cn(
                  'inline-flex flex-1 items-center justify-center gap-2 rounded-md px-3 py-2 text-sm transition-colors',
                  linkType === 'pr'
                    ? 'bg-muted text-foreground shadow-sm'
                    : 'text-muted-foreground hover:bg-muted/60 hover:text-foreground',
                  preselectedIssue && 'cursor-not-allowed opacity-50',
                )}
              >
                <GitPullRequestArrow className="size-4" />
                <span className="font-medium">GitHub PR</span>
              </button>
              {repoContext && linkType === 'issue' ? (
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="size-7"
                  onClick={() => void handleRefreshIssues()}
                  disabled={isIssuesLoading}
                  title="Refresh issues"
                >
                  <RotateCw className={cn("size-3.5", isIssuesLoading && "animate-spin [animation-direction:reverse]")} />
                </Button>
              ) : repoContext && linkType === 'pr' ? (
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="size-7"
                  onClick={() => void handleRefreshPrs()}
                  disabled={isPrsLoading}
                  title="Refresh PRs"
                >
                  <RotateCw className={cn("size-3.5", isPrsLoading && "animate-spin [animation-direction:reverse]")} />
                </Button>
              ) : null}
              </div>

            <Collapsible open={linkType !== 'none'}>
              <CollapsibleContent>
            {displayedLinkType === 'issue' ? (
              <div className="border-t border-border">
                <div className="space-y-4 px-6 py-5">
                    {repoContext ? (
                      <>
                        <div className="grid gap-2">
                          <Label htmlFor="issue-select">
                            {preselectedIssue ? 'Linked GitHub Issue' : 'Select from repository'}
                          </Label>
                          <Select
                            value={selectedIssueNumber}
                            onValueChange={handleSelectIssue}
                            disabled={!!preselectedIssue || (!isIssuesLoading && issues.length === 0)}
                          >
                            <SelectTrigger
                              id="issue-select"
                              className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
                            >
                              <SelectValue
                                placeholder={isIssuesLoading ? 'Loading issues...' : issues.length === 0 ? 'No issues available' : 'Select issue'}
                              />
                            </SelectTrigger>
                            <SelectContent className="max-h-80">
                              {issues.length === 0 ? (
                                <div className="px-2 py-1.5 text-xs text-muted-foreground">
                                  No GitHub issues found
                                </div>
                              ) : (
                                issues.map((issue) => (
                                  <SelectItem key={issue.number} value={String(issue.number)}>
                                    <div className="flex min-w-0 items-center gap-2">
                                      <span className="font-mono text-xs text-muted-foreground">
                                        #{issue.number}
                                      </span>
                                      <span className="truncate">{issue.title}</span>
                                    </div>
                                  </SelectItem>
                                ))
                              )}
                            </SelectContent>
                          </Select>
                        </div>

                        <div className="grid gap-2">
                          <Label htmlFor="issue-url">Or paste issue URL</Label>
                          <div className="flex gap-2">
                            <Input
                              id="issue-url"
                              value={issueUrl}
                              onChange={(event) => {
                                setIssuePreview(null);
                                setIssueError(null);
                                setIssueUrl(event.target.value);
                              }}
                              placeholder={`https://github.com/${repoContext.owner}/${repoContext.repo}/issues/40`}
                            />
                            <Button
                              type="button"
                              variant="outline"
                              size="icon"
                              onClick={handleLoadIssueFromUrl}
                              disabled={isIssuePreviewLoading || !issueUrl.trim()}
                              title="Load issue"
                            >
                              {isIssuePreviewLoading ? (
                                <Loader2 className="size-4 animate-spin" />
                              ) : (
                                <CloudDownload className="size-4" />
                              )}
                            </Button>
                          </div>
                        </div>
                      </>
                    ) : selectedProjectId ? (
                      <div className="rounded-md border border-dashed border-border px-3 py-4 text-sm text-muted-foreground">
                        This project does not expose a GitHub remote, so issue import is unavailable.
                      </div>
                    ) : (
                      <div className="rounded-md border border-dashed border-border px-3 py-4 text-sm text-muted-foreground">
                        Select a project first to load GitHub issue sync.
                      </div>
                    )}

                    {issueError && (
                      <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                        {issueError}
                      </div>
                    )}
                    {isIssuePreviewLoading ? (
                      <div className="flex items-center gap-2 rounded-md border border-border px-3 py-4 text-sm text-muted-foreground">
                        <Loader2 className="size-4 animate-spin" />
                        Loading issue preview
                      </div>
                    ) : issuePreview ? (
                      <Card className="border-border bg-muted/20">
                        <CardContent className="space-y-3 p-4">
                          <div className="flex items-start justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <span className="text-xs text-muted-foreground">
                                  {issuePreview.owner}/{issuePreview.repo}#{issuePreview.number}
                                </span>
                                <Button
                                  type="button"
                                  variant="outline"
                                  size="sm"
                                  className="h-6 gap-1 rounded-md px-2 text-[11px]"
                                  onClick={() =>
                                    window.open(issuePreview.url, '_blank', 'noopener,noreferrer')
                                  }
                                >
                                  <ExternalLink className="size-3" />
                                  Open on GitHub
                                </Button>
                              </div>
                              <h3 className="mt-1 truncate text-sm font-medium text-foreground">
                                {issuePreview.title}
                              </h3>
                            </div>
                            <Badge variant="secondary" className="capitalize shrink-0">
                              {issuePreview.state}
                            </Badge>
                          </div>

                          {issuePreview.labels.length > 0 && (
                            <div className="flex flex-wrap gap-2">
                              {issuePreview.labels.map((label) => (
                                <Badge key={label.name} variant="outline">
                                  {label.name}
                                </Badge>
                              ))}
                            </div>
                          )}

                          <p className="whitespace-pre-wrap text-xs leading-5 text-muted-foreground line-clamp-6">
                            {issueBodyPreview}
                          </p>
                        </CardContent>
                      </Card>
                    ) : null}

                    <label className="flex items-center gap-3 rounded-md border border-border px-3 py-3 text-sm">
                      <Checkbox
                        checked={autoExtractTodos}
                        onCheckedChange={(checked) => setAutoExtractTodos(Boolean(checked))}
                        disabled={!canAutoExtractTodosIssue}
                      />
                      <div className="min-w-0">
                        <div className="flex items-center gap-2 font-medium text-foreground">
                          <Sparkles className="size-4 text-muted-foreground" />
                          Auto-extract TODOs with LLM
                        </div>
                        <p className="mt-1 text-xs text-muted-foreground">{autoExtractDescriptionIssue}</p>
                      </div>
                    </label>
                </div>
              </div>
            ) : null}

            {displayedLinkType === 'pr' ? (
              <div className="border-t border-border">
                <div className="space-y-4 px-6 py-5">
                    {repoContext ? (
                      <>
                        <div className="grid gap-2">
                          <Label htmlFor="pr-select">Select from repository</Label>
                          <Select
                            value={selectedPrNumber}
                            onValueChange={handleSelectPr}
                            disabled={!isPrsLoading && prs.length === 0}
                          >
                            <SelectTrigger
                              id="pr-select"
                              className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
                            >
                              <SelectValue
                                placeholder={isPrsLoading ? 'Loading PRs...' : prs.length === 0 ? 'No PRs available' : 'Select PR'}
                              />
                            </SelectTrigger>
                            <SelectContent className="max-h-80">
                              {prs.length === 0 ? (
                                <div className="px-2 py-1.5 text-xs text-muted-foreground">
                                  No GitHub PRs found
                                </div>
                              ) : (
                                prs.map((pr) => (
                                  <SelectItem key={pr.number} value={String(pr.number)}>
                                    <div className="flex min-w-0 items-center gap-2">
                                      <span className="font-mono text-xs text-muted-foreground">
                                        #{pr.number}
                                      </span>
                                      <span className="truncate">{pr.title}</span>
                                    </div>
                                  </SelectItem>
                                ))
                              )}
                            </SelectContent>
                          </Select>
                        </div>

                        <div className="grid gap-2">
                          <Label htmlFor="pr-url">Or paste PR URL</Label>
                          <div className="flex gap-2">
                            <Input
                              id="pr-url"
                              value={prUrl}
                              onChange={(event) => {
                                setPrPreview(null);
                                setPrError(null);
                                setPrUrl(event.target.value);
                              }}
                              placeholder={`https://github.com/${repoContext.owner}/${repoContext.repo}/pull/40`}
                            />
                            <Button
                              type="button"
                              variant="outline"
                              size="icon"
                              onClick={handleLoadPrFromUrl}
                              disabled={isPrPreviewLoading || !prUrl.trim()}
                              title="Load PR"
                            >
                              {isPrPreviewLoading ? (
                                <Loader2 className="size-4 animate-spin" />
                              ) : (
                                <CloudDownload className="size-4" />
                              )}
                            </Button>
                          </div>
                        </div>
                      </>
                    ) : selectedProjectId ? (
                      <div className="rounded-md border border-dashed border-border px-3 py-4 text-sm text-muted-foreground">
                        This project does not expose a GitHub remote, so PR import is unavailable.
                      </div>
                    ) : (
                      <div className="rounded-md border border-dashed border-border px-3 py-4 text-sm text-muted-foreground">
                        Select a project first to load GitHub PRs.
                      </div>
                    )}

                    {prError && (
                      <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                        {prError}
                      </div>
                    )}

                    {isPrPreviewLoading ? (
                      <div className="flex items-center gap-2 rounded-md border border-border px-3 py-4 text-sm text-muted-foreground">
                        <Loader2 className="size-4 animate-spin" />
                        Loading PR preview
                      </div>
                    ) : prPreview ? (
                      <Card className="border-border bg-muted/20">
                        <CardContent className="space-y-3 p-4">
                          <div className="flex items-start justify-between gap-3">
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <span className="text-xs text-muted-foreground">
                                  {prPreview.owner}/{prPreview.repo}#{prPreview.number}
                                </span>
                                <Button
                                  type="button"
                                  variant="outline"
                                  size="sm"
                                  className="h-6 gap-1 rounded-md px-2 text-[11px]"
                                  onClick={() =>
                                    window.open(prPreview.url, '_blank', 'noopener,noreferrer')
                                  }
                                >
                                  <ExternalLink className="size-3" />
                                  Open on GitHub
                                </Button>
                              </div>
                              <h3 className="mt-1 truncate text-sm font-medium text-foreground">
                                {prPreview.title}
                              </h3>
                              <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
                                <span className="inline-flex items-center gap-1">
                                  <GitBranch className="size-3" />
                                  {prPreview.head_ref}
                                </span>
                                <span className="opacity-50">→</span>
                                <span className="inline-flex items-center gap-1">
                                  <GitBranch className="size-3" />
                                  {prPreview.base_ref}
                                </span>
                              </div>
                            </div>
                            <Badge variant="secondary" className="capitalize shrink-0">
                              {prPreview.is_draft ? 'draft' : prPreview.state}
                            </Badge>
                          </div>

                          {prPreview.labels.length > 0 && (
                            <div className="flex flex-wrap gap-2">
                              {prPreview.labels.map((label) => (
                                <Badge key={label.name} variant="outline">
                                  {label.name}
                                </Badge>
                              ))}
                            </div>
                          )}

                          <p className="whitespace-pre-wrap text-xs leading-5 text-muted-foreground line-clamp-6">
                            {prPreview.body?.trim() || 'No PR description provided.'}
                          </p>

                          <div className="rounded-md border border-border bg-background/40 px-3 py-2 text-[11px] text-muted-foreground">
                            The workspace will reuse <span className="font-mono text-foreground">{prPreview.head_ref}</span> directly — no new branch will be created.
                          </div>
                        </CardContent>
                      </Card>
                    ) : null}

                    <label className="flex items-center gap-3 rounded-md border border-border px-3 py-3 text-sm">
                      <Checkbox
                        checked={autoExtractTodosPr}
                        onCheckedChange={(checked) => setAutoExtractTodosPr(Boolean(checked))}
                        disabled={!canAutoExtractTodosPr}
                      />
                      <div className="min-w-0">
                        <div className="flex items-center gap-2 font-medium text-foreground">
                          <Sparkles className="size-4 text-muted-foreground" />
                          Auto-extract TODOs with LLM
                        </div>
                        <p className="mt-1 text-xs text-muted-foreground">{autoExtractDescriptionPr}</p>
                      </div>
                    </label>
                </div>
              </div>
            ) : null}
              </CollapsibleContent>
            </Collapsible>
            </div>

            {submitError && (
              <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                {submitError}
              </div>
            )}
          </div>

          <div className="mx-1 mt-4 border-b border-border/60" />
          <DialogFooter className="mt-4 flex w-full flex-row items-center justify-between sm:justify-between">
            <div className="flex items-center gap-2">
              <WorkspacePrioritySelect
                value={priority}
                onChange={setPriority}
                triggerVariant="icon"
                contentSide="top"
              />
              <WorkspaceStatusSelect
                value={workflowStatus}
                onChange={setWorkflowStatus}
                triggerVariant="icon"
                contentSide="top"
              />
              <WorkspaceLabelPicker
                labels={selectedLabels}
                availableLabels={workspaceLabels}
                onChange={setSelectedLabels}
                onCreateLabel={createWorkspaceLabel}
                triggerVariant="icon"
                contentSide="top"
                editorSide="left"
              />
              <WorkspaceLabelDots labels={selectedLabels} overlap className="pl-1" />
            </div>

            <div className="flex items-center gap-2">
              <Button type="button" variant="ghost" onClick={onClose} disabled={isSubmitting}>
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={
                  isSubmitting ||
                  !projectId ||
                  isIssuePreviewLoading ||
                  isBaseBranchesLoading ||
                  remoteBranches.length === 0
                }
              >
                {isSubmitting ? 'Creating...' : 'Create Workspace'}
              </Button>
            </div>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};
