import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Dialog, DialogContent, Input, Label } from '@workspace/ui';
import type { WorkspacePriority, WorkspaceWorkflowStatus, WorkspaceLabel } from '@/types/types';
import {
  BaseBranchField,
  CreateWorkspaceFooter,
  CreateWorkspaceHeader,
  GithubLinkImportSection,
  ProjectSelectField,
  WorkspaceBranchField,
} from '@/components/dialogs/CreateWorkspaceDialogParts';
import {
  IssueLinkPanel,
  PrLinkPanel,
} from '@/components/dialogs/CreateWorkspaceDialogGithubPanels';
import type { RepoContext } from '@/components/dialogs/CreateWorkspaceDialogTypes';
import { useProjectStore } from '@/hooks/use-project-store';
import {
  gitApi,
  llmProvidersApi,
  type GithubIssuePayload,
  type GithubPrPayload,
  wsScriptApi,
  wsGithubApi,
} from '@/api/ws-api';
import { useAppRouter } from '@/hooks/use-app-router';
import { useWorkspaceCreationStore } from '@/hooks/use-workspace-creation-store';
import {
  ISSUE_CACHE_TTL_MS,
  issueListCache,
  issueToBranchName,
  issueToWorkspaceName,
  isAutoGeneratedBranchConflictError,
  isBranchConflictError,
  prListCache,
  prToWorkspaceName,
  regeneratePokemonSuffixBranch,
  resolveWorkspaceIssueTodoProvider,
  sanitizeCreateWorkspaceErrorMessage,
} from '@/components/welcome/welcome-page-helpers';

interface CreateWorkspaceDialogProps {
  isOpen: boolean;
  onClose: () => void;
  defaultProjectId?: string;
  defaultWorkflowStatus?: WorkspaceWorkflowStatus;
  projectSelectionInHeader?: boolean;
  requireProjectSelection?: boolean;
  // Build from Issue Only mode
  preselectedIssue?: GithubIssuePayload;
  sourceWorkspaceId?: string;
}

export const CreateWorkspaceDialog: React.FC<CreateWorkspaceDialogProps> = ({
  isOpen,
  onClose,
  defaultProjectId,
  defaultWorkflowStatus,
  projectSelectionInHeader = false,
  requireProjectSelection = false,
  preselectedIssue,
}: CreateWorkspaceDialogProps) => {
  const router = useAppRouter();
  const projects = useProjectStore((s) => s.projects);
  const addWorkspace = useProjectStore((s) => s.addWorkspace);
  const showCreating = useWorkspaceCreationStore((s) => s.showCreating);
  const showOpening = useWorkspaceCreationStore((s) => s.showOpening);
  const clearWorkspaceCreationOverlay = useWorkspaceCreationStore((s) => s.clear);

  const [projectId, setProjectId] = useState(() => {
    if (defaultProjectId) return defaultProjectId;
    if (requireProjectSelection) return '';
    return projects.length > 0 ? projects[0].id : '';
  });
  const [name, setName] = useState('');
  const [branch, setBranch] = useState('');
  const [baseBranch, setBaseBranch] = useState('main');
  const [remoteBranches, setRemoteBranches] = useState<string[]>([]);
  const [baseBranchFilter, setBaseBranchFilter] = useState('');
  const [isBaseBranchOpen, setIsBaseBranchOpen] = useState(false);
  const [issueUrl, setIssueUrl] = useState('');
  const [selectedIssueNumber, setSelectedIssueNumber] = useState<string>('');
  const [issuePreview, setIssuePreview] = useState<GithubIssuePayload | null>(null);
  const [issues, setIssues] = useState<GithubIssuePayload[]>([]);
  const [prUrl, setPrUrl] = useState('');
  const [selectedPrNumber, setSelectedPrNumber] = useState<string>('');
  const [prPreview, setPrPreview] = useState<GithubPrPayload | null>(null);
  const [prs, setPrs] = useState<GithubPrPayload[]>([]);
  const [prError, setPrError] = useState<string | null>(null);
  const [isPrsLoading, setIsPrsLoading] = useState(false);
  const [isPrPreviewLoading, setIsPrPreviewLoading] = useState(false);
  const [repoContext, setRepoContext] = useState<RepoContext | null>(null);
  const [isRepoLoading, setIsRepoLoading] = useState(false);
  const [isBaseBranchesLoading, setIsBaseBranchesLoading] = useState(false);
  const [isIssuesLoading, setIsIssuesLoading] = useState(false);
  const [isIssuePreviewLoading, setIsIssuePreviewLoading] = useState(false);
  const [isLlmRoutingLoading, setIsLlmRoutingLoading] = useState(false);
  const [hasSetupScript, setHasSetupScript] = useState(false);
  const [issueError, setIssueError] = useState<string | null>(null);
  const [branchError, setBranchError] = useState<string | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [autoExtractTodos, setAutoExtractTodos] = useState(false);
  const [autoExtractTodosPr, setAutoExtractTodosPr] = useState(false);
  const [linkType, setLinkType] = useState<'none' | 'issue' | 'pr'>('none');
  const [displayedLinkType, setDisplayedLinkType] = useState<'issue' | 'pr'>('issue');
  useEffect(() => {
    if (linkType !== 'none') setDisplayedLinkType(linkType);
  }, [linkType]);
  const [todoProviderLabel, setTodoProviderLabel] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Metadata states - defaults: no_priority, in_progress, empty labels
  const [priority, setPriority] = useState<WorkspacePriority>('no_priority');
  const [workflowStatus, setWorkflowStatus] = useState<WorkspaceWorkflowStatus>(
    defaultWorkflowStatus ?? 'in_progress',
  );
  const [selectedLabels, setSelectedLabels] = useState<WorkspaceLabel[]>([]);

  const workspaceLabels = useProjectStore(s => s.workspaceLabels);
  const createWorkspaceLabel = useProjectStore(s => s.createWorkspaceLabel);

  const nameTouchedRef = useRef(false);
  const branchTouchedRef = useRef(false);
  const generatedBranchRef = useRef<string | null>(null);
  const branchFieldRef = useRef<HTMLDivElement | null>(null);
  const branchInputRef = useRef<HTMLInputElement | null>(null);

  const selectedProject = useMemo(
    () => projects.find((project) => project.id === projectId) ?? null,
    [projectId, projects],
  );
  const selectedProjectId = selectedProject?.id ?? null;
  const selectedProjectPath = selectedProject?.mainFilePath ?? null;

  useEffect(() => {
    if (defaultProjectId) {
      setProjectId(defaultProjectId);
      return;
    }

    if (!projectId && projects.length > 0 && !requireProjectSelection) {
      setProjectId(projects[0].id);
    }
  }, [defaultProjectId, projectId, projects, requireProjectSelection]);

  useEffect(() => {
    if (!isOpen) return;
    setWorkflowStatus(defaultWorkflowStatus ?? 'in_progress');
  }, [defaultWorkflowStatus, isOpen]);

  useEffect(() => {
    if (!isOpen) {
      setProjectId(
        defaultProjectId || (!requireProjectSelection && projects.length > 0 ? projects[0].id : ''),
      );
      setName('');
      setBranch('');
      setBaseBranch('main');
      setRemoteBranches([]);
      setBaseBranchFilter('');
      setIsBaseBranchOpen(false);
      setIssueUrl('');
      setSelectedIssueNumber('');
      setIssuePreview(null);
      setIssues([]);
      setPrUrl('');
      setSelectedPrNumber('');
      setPrPreview(null);
      setPrs([]);
      setPrError(null);
      setIsPrsLoading(false);
      setIsPrPreviewLoading(false);
      setIsRepoLoading(false);
      setIsBaseBranchesLoading(false);
      setIsIssuesLoading(false);
      setIsIssuePreviewLoading(false);
      setIsLlmRoutingLoading(false);
      setHasSetupScript(false);
      setIssueError(null);
      setBranchError(null);
      setSubmitError(null);
      setAutoExtractTodos(false);
      setAutoExtractTodosPr(false);
      setLinkType('none');
      setDisplayedLinkType('issue');
      setTodoProviderLabel(null);
      setIsSubmitting(false);
      setPriority('no_priority');
      setWorkflowStatus(defaultWorkflowStatus ?? 'in_progress');
      setSelectedLabels([]);
      // Reset refs
      nameTouchedRef.current = false;
      branchTouchedRef.current = false;
      generatedBranchRef.current = null;
    }
  }, [defaultProjectId, isOpen, projects, requireProjectSelection, defaultWorkflowStatus]);

  // Handle preselectedIssue for Build from Issue Only mode
  useEffect(() => {
    if (isOpen && preselectedIssue) {
      setIssuePreview(preselectedIssue);
      setIssueUrl(preselectedIssue.url);
      setSelectedIssueNumber(preselectedIssue.number.toString());
      setLinkType('issue');
      setDisplayedLinkType('issue');
      // Auto-fill workspace name and branch from issue
      const workspaceName = issueToWorkspaceName(preselectedIssue);
      const branchName = issueToBranchName(preselectedIssue);
      setName(workspaceName);
      setBranch(branchName);
    }
  }, [isOpen, preselectedIssue]);

  useEffect(() => {
    let cancelled = false;

    async function loadLlmRouting() {
      if (!isOpen) {
        return;
      }

      setIsLlmRoutingLoading(true);
      try {
        const config = await llmProvidersApi.get();
        if (cancelled) return;

        const provider = resolveWorkspaceIssueTodoProvider(config);
        setTodoProviderLabel(provider?.label ?? null);
      } catch {
        if (!cancelled) {
          setTodoProviderLabel(null);
        }
      } finally {
        if (!cancelled) {
          setIsLlmRoutingLoading(false);
        }
      }
    }

    loadLlmRouting();
    return () => {
      cancelled = true;
    };
  }, [isOpen]);

  useEffect(() => {
    let cancelled = false;

    async function loadRepoContext() {
      if (!isOpen || !selectedProjectId || !selectedProjectPath) {
        return;
      }

      setIsRepoLoading(true);
      setIsBaseBranchesLoading(true);
      setIssueError(null);
      setRepoContext(null);
      setRemoteBranches([]);
      setIssues([]);
      if (!preselectedIssue) {
        setIssuePreview(null);
        setSelectedIssueNumber('');
        setIssueUrl('');
      }
      setPrs([]);
      setPrPreview(null);
      setSelectedPrNumber('');
      setPrUrl('');
      setPrError(null);
      if (!preselectedIssue) {
        setLinkType('none');
      }
      setAutoExtractTodos(false);
      setAutoExtractTodosPr(false);
      setHasSetupScript(false);

      try {
        const fetchedRemoteBranches = await gitApi.listRemoteBranches(selectedProjectPath);
        if (!cancelled) {
          const nextRemoteBranches = fetchedRemoteBranches.sort();
          setRemoteBranches(nextRemoteBranches);
          if (nextRemoteBranches.includes('main')) {
            setBaseBranch('main');
          } else if (nextRemoteBranches.length > 0) {
            setBaseBranch(nextRemoteBranches[0]);
          } else {
            setBaseBranch('main');
          }
        }

        const scripts = await wsScriptApi.get(selectedProjectId);
        if (!cancelled) {
          setHasSetupScript(
            typeof scripts.setup === 'string' && scripts.setup.trim().length > 0,
          );
        }

        const status = await gitApi.getStatus(selectedProjectPath);
        if (cancelled) return;

        if (status.github_owner && status.github_repo) {
          const nextContext = {
            owner: status.github_owner,
            repo: status.github_repo,
          };
          setRepoContext(nextContext);

          const cacheKey = `${nextContext.owner}/${nextContext.repo}`;
          const cachedIssues = issueListCache.get(cacheKey);
          if (cachedIssues && cachedIssues.expiresAt > Date.now()) {
            setIssues(cachedIssues.issues);
          } else {
            setIsIssuesLoading(true);
            const fetchedIssues = await wsGithubApi.listIssues(nextContext);
            if (cancelled) return;
            setIssues(fetchedIssues);
            issueListCache.set(cacheKey, {
              expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
              issues: fetchedIssues,
            });
          }

          const cachedPrs = prListCache.get(cacheKey);
          if (cachedPrs && cachedPrs.expiresAt > Date.now()) {
            setPrs(cachedPrs.prs);
          } else {
            setIsPrsLoading(true);
            try {
              const fetchedPrs = await wsGithubApi.listPrs(nextContext);
              if (cancelled) return;
              setPrs(fetchedPrs);
              prListCache.set(cacheKey, {
                expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
                prs: fetchedPrs,
              });
            } catch (error) {
              if (!cancelled) {
                setPrError(error instanceof Error ? error.message : 'Failed to load GitHub PRs');
              }
            }
          }
        }
      } catch (error) {
        if (!cancelled) {
          setIssueError(error instanceof Error ? error.message : 'Failed to load GitHub issues');
        }
      } finally {
        if (!cancelled) {
          setIsRepoLoading(false);
          setIsBaseBranchesLoading(false);
          setIsIssuesLoading(false);
          setIsPrsLoading(false);
        }
      }
    }

    loadRepoContext();
    return () => {
      cancelled = true;
    };
  }, [isOpen, preselectedIssue, selectedProjectId, selectedProjectPath]);

  useEffect(() => {
    if (!issuePreview) {
      if (!prPreview) {
        generatedBranchRef.current = null;
      }
      return;
    }

    if (!nameTouchedRef.current) {
      setName(issueToWorkspaceName(issuePreview));
    }
    if (!branchTouchedRef.current) {
      const generated = issueToBranchName(issuePreview);
      generatedBranchRef.current = generated;
      setBranch(generated);
    }
  }, [issuePreview, prPreview]);

  useEffect(() => {
    if (!prPreview) return;

    if (!nameTouchedRef.current) {
      setName(prToWorkspaceName(prPreview));
    }
    setBranch(prPreview.head_ref);
    if (prPreview.base_ref) {
      setBaseBranch(prPreview.base_ref);
    }
  }, [prPreview]);

  useEffect(() => {
    if (!issuePreview || !todoProviderLabel) setAutoExtractTodos(false);
  }, [issuePreview, todoProviderLabel]);

  useEffect(() => {
    if (!prPreview || !todoProviderLabel) setAutoExtractTodosPr(false);
  }, [prPreview, todoProviderLabel]);

  const clearPrSelection = () => {
    setPrPreview(null);
    setSelectedPrNumber('');
    setPrUrl('');
    setPrError(null);
    setAutoExtractTodosPr(false);
  };

  const clearIssueSelection = () => {
    setIssuePreview(null);
    setSelectedIssueNumber('');
    setIssueUrl('');
    setIssueError(null);
    setAutoExtractTodos(false);
  };

  const handleSelectLinkType = (next: 'issue' | 'pr') => {
    if (preselectedIssue) {
      return;
    }

    if (linkType === next) {
      setLinkType('none');
      if (next === 'issue') clearIssueSelection();
      else clearPrSelection();
      return;
    }
    setLinkType(next);
    if (next === 'issue') clearPrSelection();
    else clearIssueSelection();
  };

  const handleSelectIssue = async (value: string) => {
    setSelectedIssueNumber(value);
    setIssueUrl('');
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);

    const selected = issues.find((issue) => String(issue.number) === value) ?? null;
    setIssuePreview(selected);
    clearPrSelection();
  };

  const handleSelectPr = (value: string) => {
    setSelectedPrNumber(value);
    setPrUrl('');
    setPrError(null);
    setBranchError(null);
    setSubmitError(null);
    const selected = prs.find((pr) => String(pr.number) === value) ?? null;
    setPrPreview(selected);
    clearIssueSelection();
  };

  const handleLoadPrFromUrl = async () => {
    if (!prUrl.trim()) {
      setPrError(null);
      return;
    }
    setIsPrPreviewLoading(true);
    setPrError(null);
    setBranchError(null);
    setSubmitError(null);
    setSelectedPrNumber('');
    try {
      const preview = await wsGithubApi.getPr({ prUrl: prUrl.trim() });
      const currentRepo = repoContext ? `${repoContext.owner}/${repoContext.repo}` : null;
      const previewRepo = `${preview.owner}/${preview.repo}`;
      if (currentRepo && currentRepo !== previewRepo) {
        setPrPreview(null);
        setPrError(`PR belongs to ${previewRepo}, but current project is ${currentRepo}.`);
        return;
      }
      setPrPreview(preview);
      clearIssueSelection();
    } catch (error) {
      setPrPreview(null);
      setPrError(error instanceof Error ? error.message : 'Failed to load PR preview');
    } finally {
      setIsPrPreviewLoading(false);
    }
  };

  const handleRefreshPrs = async () => {
    if (!repoContext) return;
    setIsPrsLoading(true);
    setPrError(null);
    try {
      const cacheKey = `${repoContext.owner}/${repoContext.repo}`;
      prListCache.delete(cacheKey);
      const fetchedPrs = await wsGithubApi.listPrs(repoContext);
      setPrs(fetchedPrs);
      prListCache.set(cacheKey, {
        expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
        prs: fetchedPrs,
      });
    } catch (error) {
      setPrError(error instanceof Error ? error.message : 'Failed to refresh GitHub PRs');
    } finally {
      setIsPrsLoading(false);
    }
  };

  const handleLoadIssueFromUrl = async () => {
    if (!issueUrl.trim()) {
      setIssueError(null);
      return;
    }

    setIsIssuePreviewLoading(true);
    setIssueError(null);
    setBranchError(null);
    setSubmitError(null);
    setSelectedIssueNumber('');

    try {
      const preview = await wsGithubApi.getIssue({ issueUrl: issueUrl.trim() });
      const currentRepo = repoContext ? `${repoContext.owner}/${repoContext.repo}` : null;
      const previewRepo = `${preview.owner}/${preview.repo}`;

      if (currentRepo && currentRepo !== previewRepo) {
        setIssuePreview(null);
        setIssueError(`Issue belongs to ${previewRepo}, but current project is ${currentRepo}.`);
        return;
      }

      setIssuePreview(preview);
      clearPrSelection();
    } catch (error) {
      setIssuePreview(null);
      setIssueError(error instanceof Error ? error.message : 'Failed to load issue preview');
    } finally {
      setIsIssuePreviewLoading(false);
    }
  };

  const handleRefreshIssues = async () => {
    if (!repoContext) return;
    setIsIssuesLoading(true);
    setIssueError(null);
    try {
      const cacheKey = `${repoContext.owner}/${repoContext.repo}`;
      issueListCache.delete(cacheKey);
      const fetchedIssues = await wsGithubApi.listIssues(repoContext);
      setIssues(fetchedIssues);
      issueListCache.set(cacheKey, {
        expiresAt: Date.now() + ISSUE_CACHE_TTL_MS,
        issues: fetchedIssues,
      });
    } catch (error) {
      setIssueError(error instanceof Error ? error.message : 'Failed to refresh GitHub issues');
    } finally {
      setIsIssuesLoading(false);
    }
  };

  const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    nameTouchedRef.current = true;
    setBranchError(null);
    setSubmitError(null);
    setName(event.target.value);
  };

  const handleBranchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    branchTouchedRef.current = true;
    setBranchError(null);
    setSubmitError(null);
    setBranch(event.target.value);
  };

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!projectId) return;

    let keepGlobalLoading = false;
    setIsSubmitting(true);
    showCreating();
    setBranchError(null);
    setSubmitError(null);
    try {
      const finalDisplayName = prPreview
        ? name.trim() || prToWorkspaceName(prPreview)
        : name.trim() || (issuePreview ? issueToWorkspaceName(issuePreview) : '');
      const finalBranch = prPreview
        ? prPreview.head_ref
        : branch.trim() ||
          (!branchTouchedRef.current && generatedBranchRef.current) ||
          (issuePreview ? issueToBranchName(issuePreview) : '');
      const finalBaseBranch = prPreview ? prPreview.base_ref || baseBranch : baseBranch;

      // Create labels from GitHub issue/PR if present
      let labelsToUse = selectedLabels;
      if (prPreview && prPreview.labels && prPreview.labels.length > 0) {
        const source = 'gitHub_pr' as const;
        for (const prLabel of prPreview.labels) {
          // Check if label already exists with same name (case-insensitive) and source
          const existingLabel = workspaceLabels.find(
            (l) => l.name.toLowerCase() === prLabel.name.toLowerCase() && l.source === source
          );
          if (!existingLabel) {
            const newLabel = await createWorkspaceLabel({
              name: prLabel.name,
              color: prLabel.color ? `#${prLabel.color.replace(/^#/, '')}` : '#94a3b8',
              source,
            });
            labelsToUse = [...labelsToUse, newLabel];
          } else if (!labelsToUse.find((l) => l.id === existingLabel.id)) {
            labelsToUse = [...labelsToUse, existingLabel];
          }
        }
      } else if (issuePreview && issuePreview.labels && issuePreview.labels.length > 0) {
        const source = 'gitHub_issue' as const;
        for (const issueLabel of issuePreview.labels) {
          // Check if label already exists with same name (case-insensitive) and source
          const existingLabel = workspaceLabels.find(
            (l) => l.name.toLowerCase() === issueLabel.name.toLowerCase() && l.source === source
          );
          if (!existingLabel) {
            const newLabel = await createWorkspaceLabel({
              name: issueLabel.name,
              color: issueLabel.color ? `#${issueLabel.color.replace(/^#/, '')}` : '#94a3b8',
              source,
            });
            labelsToUse = [...labelsToUse, newLabel];
          } else if (!labelsToUse.find((l) => l.id === existingLabel.id)) {
            labelsToUse = [...labelsToUse, existingLabel];
          }
        }
      }

      const workspaceId = await addWorkspace({
        projectId,
        name: finalBranch,
        displayName: finalDisplayName || null,
        branch: finalBranch,
        baseBranch: finalBaseBranch,
        initialRequirement: null,
        githubIssue: prPreview ? null : issuePreview,
        githubPr: prPreview,
        autoExtractTodos:
          !!todoProviderLabel &&
          ((prPreview && autoExtractTodosPr) || (!prPreview && !!issuePreview && autoExtractTodos)),
        hasSetupScript,
        priority,
        workflowStatus,
        labels: labelsToUse,
      });
      keepGlobalLoading = true;
      showOpening(workspaceId);
      onClose();
      router.push(`/workspace?id=${workspaceId}`);
    } catch (error) {
      clearWorkspaceCreationOverlay();
      const message = sanitizeCreateWorkspaceErrorMessage(
        error instanceof Error ? error.message : 'Failed to create workspace',
      );

      if (isBranchConflictError(message)) {
        setBranchError(message);
        requestAnimationFrame(() => {
          branchFieldRef.current?.scrollIntoView({
            behavior: 'smooth',
            block: 'center',
          });
          branchInputRef.current?.focus();
        });
      } else {
        setSubmitError(message);
      }
    } finally {
      if (!keepGlobalLoading) {
        setIsSubmitting(false);
      }
    }
  };

  const handleRegenerateBranch = () => {
    const nextBranch = regeneratePokemonSuffixBranch(branch, issuePreview?.number);
    branchTouchedRef.current = true;
    setBranch(nextBranch);
    setBranchError(null);
    setSubmitError(null);
    requestAnimationFrame(() => {
      branchInputRef.current?.focus();
    });
  };

  const repoLabel = repoContext ? `${repoContext.owner}/${repoContext.repo}` : 'No GitHub repository';
  const issueBodyPreview = issuePreview?.body?.trim() || 'No issue description provided.';
  const canAutoExtractTodosIssue = !!issuePreview && !!todoProviderLabel && !isLlmRoutingLoading;
  const canAutoExtractTodosPr = !!prPreview && !!todoProviderLabel && !isLlmRoutingLoading;
  const filteredRemoteBranches = useMemo(
    () => remoteBranches.filter((remoteBranch) =>
      remoteBranch.toLowerCase().includes(baseBranchFilter.trim().toLowerCase()),
    ),
    [remoteBranches, baseBranchFilter],
  );
  const buildAutoExtractDescription = (kind: 'issue' | 'pr') => {
    const hasPreview = kind === 'issue' ? !!issuePreview : !!prPreview;
    if (!hasPreview) return `Import a GitHub ${kind === 'pr' ? 'PR' : 'issue'} first.`;
    if (isLlmRoutingLoading) return 'Checking LLM routing...';
    if (todoProviderLabel)
      return `Uses ${todoProviderLabel} to extract an initial task checklist from the ${kind === 'pr' ? 'PR' : 'issue'} description.`;
    return 'Configure LLM Providers > Routing > Workspace issue TODO extraction first.';
  };
  const autoExtractDescriptionIssue = buildAutoExtractDescription('issue');
  const autoExtractDescriptionPr = buildAutoExtractDescription('pr');
  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[720px] max-h-[80vh] overflow-y-auto [scrollbar-gutter:stable] gap-4 bg-background p-6 pt-7">
        <CreateWorkspaceHeader
          isBuildFromIssue={!!preselectedIssue}
          projectSelectionInHeader={projectSelectionInHeader}
          selectedProjectName={selectedProject?.name ?? null}
          isRepoLoading={isRepoLoading}
          repoLabel={repoLabel}
        />
        <div className="-mx-6 border-b border-border/60" />

        <form onSubmit={handleSubmit} className="flex flex-col">
          <div className="pr-1 pt-2 space-y-5">
            {!defaultProjectId && projectSelectionInHeader && (
              <ProjectSelectField
                id="project-inline"
                label="Project"
                placeholder="Please select a project"
                value={projectId}
                projects={projects}
                onChange={setProjectId}
                requireSelectionMessage="Please select a project to continue."
              />
            )}

            {!defaultProjectId && !projectSelectionInHeader && (
              <ProjectSelectField
                id="project"
                label="Project"
                placeholder="Select a project"
                value={projectId}
                projects={projects}
                onChange={setProjectId}
                disabled={!!defaultProjectId}
              />
            )}

            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="workspace-name">Name</Label>
                <Input
                  id="workspace-name"
                  value={name}
                  onChange={handleNameChange}
                  placeholder="Workspace display name, typing..."
                  autoFocus
                />
                <p className="text-xs text-muted-foreground">
                  Leave empty to let Atmos generate a name, or import one from a GitHub issue.
                </p>
              </div>

              <BaseBranchField
                baseBranch={baseBranch}
                isOpen={isBaseBranchOpen}
                isLoading={isBaseBranchesLoading}
                remoteBranches={remoteBranches}
                branchFilter={baseBranchFilter}
                filteredRemoteBranches={filteredRemoteBranches}
                selectedProjectId={selectedProjectId}
                onOpenChange={(open) => {
                  setIsBaseBranchOpen(open);
                  if (open) setBaseBranchFilter('');
                }}
                onFilterChange={setBaseBranchFilter}
                onSelectBranch={setBaseBranch}
              />

              <WorkspaceBranchField
                branchFieldRef={branchFieldRef}
                branchInputRef={branchInputRef}
                branch={branch}
                branchError={branchError}
                canRegenerateBranch={!!branchError && isAutoGeneratedBranchConflictError(branchError)}
                onBranchChange={handleBranchChange}
                onRegenerateBranch={handleRegenerateBranch}
              />
            </div>

            <GithubLinkImportSection
              linkType={linkType}
              displayedLinkType={displayedLinkType}
              isPreselectedIssue={!!preselectedIssue}
              repoContext={repoContext}
              isIssuesLoading={isIssuesLoading}
              isPrsLoading={isPrsLoading}
              onSelectLinkType={handleSelectLinkType}
              onRefreshIssues={() => void handleRefreshIssues()}
              onRefreshPrs={() => void handleRefreshPrs()}
              issuePanel={
                <IssueLinkPanel
                  repoContext={repoContext}
                  selectedProjectId={selectedProjectId}
                  isPreselectedIssue={!!preselectedIssue}
                  issues={issues}
                  selectedIssueNumber={selectedIssueNumber}
                  issueUrl={issueUrl}
                  issueError={issueError}
                  isIssuesLoading={isIssuesLoading}
                  isIssuePreviewLoading={isIssuePreviewLoading}
                  issuePreview={issuePreview}
                  issueBodyPreview={issueBodyPreview}
                  autoExtractTodos={autoExtractTodos}
                  canAutoExtractTodos={canAutoExtractTodosIssue}
                  autoExtractDescription={autoExtractDescriptionIssue}
                  onSelectIssue={handleSelectIssue}
                  onIssueUrlChange={(value) => {
                    setIssuePreview(null);
                    setIssueError(null);
                    setIssueUrl(value);
                  }}
                  onLoadIssueFromUrl={handleLoadIssueFromUrl}
                  onAutoExtractTodosChange={(checked) => setAutoExtractTodos(Boolean(checked))}
                />
              }
              prPanel={
                <PrLinkPanel
                  repoContext={repoContext}
                  selectedProjectId={selectedProjectId}
                  prs={prs}
                  selectedPrNumber={selectedPrNumber}
                  prUrl={prUrl}
                  prError={prError}
                  isPrsLoading={isPrsLoading}
                  isPrPreviewLoading={isPrPreviewLoading}
                  prPreview={prPreview}
                  autoExtractTodosPr={autoExtractTodosPr}
                  canAutoExtractTodos={canAutoExtractTodosPr}
                  autoExtractDescription={autoExtractDescriptionPr}
                  onSelectPr={handleSelectPr}
                  onPrUrlChange={(value) => {
                    setPrPreview(null);
                    setPrError(null);
                    setPrUrl(value);
                  }}
                  onLoadPrFromUrl={handleLoadPrFromUrl}
                  onAutoExtractTodosChange={(checked) => setAutoExtractTodosPr(Boolean(checked))}
                />
              }
            />

            {submitError && (
              <div className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive">
                {submitError}
              </div>
            )}
          </div>

          <div className="mx-1 mt-4 border-b border-border/60" />
          <CreateWorkspaceFooter
            priority={priority}
            workflowStatus={workflowStatus}
            selectedLabels={selectedLabels}
            workspaceLabels={workspaceLabels}
            isSubmitting={isSubmitting}
            canSubmit={
              !isSubmitting &&
              !!projectId &&
              !isIssuePreviewLoading &&
              !isBaseBranchesLoading &&
              remoteBranches.length > 0
            }
            onPriorityChange={setPriority}
            onWorkflowStatusChange={setWorkflowStatus}
            onLabelsChange={setSelectedLabels}
            onCreateLabel={createWorkspaceLabel}
            onClose={onClose}
          />
        </form>
      </DialogContent>
    </Dialog>
  );
};
