export type {
  LocalService,
  LocalServiceKind,
  LocalServiceOwner,
  LocalServiceProcessNode,
  LocalServiceStatus,
  LocalServiceStopEscalationReason,
  LocalServiceStopMode,
  LocalServiceStopRequest,
  LocalServiceStopResponse,
  LocalServicesScanRequest,
  LocalServicesScanResponse,
  LocalServicesScope,
  LocalServicesUnavailable,
} from "@/api/ws/local-services-api";
