import type { MdLiveCopyFn } from "./types";

export const MD_LIVE_COPY_EN: Record<string, string> = {
  copied: "Copied",
  slashGroupHeading: "Heading",
  slashGroupBasic: "Basic",
  slashGroupAdvanced: "Advanced",
  slashGroupMedia: "Media",
  slashGroupOthers: "Others",
  slashHeading1: "Heading 1",
  slashHeading2: "Heading 2",
  slashHeading3: "Heading 3",
  slashHeading4: "Heading 4",
  slashHeading5: "Heading 5",
  slashHeading6: "Heading 6",
  slashBulletList: "Bullet list",
  slashOrderedList: "Numbered list",
  slashTaskList: "To-do list",
  slashQuote: "Blockquote",
  slashCode: "Code block",
  slashInlineCode: "Inline code",
  slashTable: "Table",
  slashDivider: "Divider",
  slashImage: "Image",
  slashVideo: "Video",
  slashAudio: "Audio",
  slashFile: "File",
  slashEmoji: "Emoji",
  slashEmojiLoading: "Loading...",
  slashNoResults: "No results",
  toolbarGroupOperate: "Operate",
  toolbarGroupConvert: "Convert",
  toolbarParagraph: "Paragraph",
  toolbarHeading: "Heading",
  toolbarList: "List",
  toolbarQuote: "Quote",
  toolbarCode: "Code",
  toolbarBulletList: "Bullet list",
  toolbarOrderedList: "Numbered list",
  toolbarTaskList: "To-do list",
  toolbarAi: "Ask AI",
  toolbarInlineCode: "Inline code",
  toolbarBold: "Bold",
  toolbarItalic: "Italic",
  toolbarStrikethrough: "Strikethrough",
  toolbarCopy: "Copy",
  toolbarCopyPrompt: "Copy prompt",
  toolbarAsk: "Ask",
  toolbarRewrite: "Rewrite",
  toolbarSummarize: "Summarize",
};

export function mdLiveLabel(key: string, copy?: MdLiveCopyFn): string {
  return copy?.(key) ?? MD_LIVE_COPY_EN[key] ?? key;
}
