"use client";

import React from "react";
import { useTranslations } from "next-intl";
import {
  Badge,
  Button,
  Card,
  CardContent,
  Checkbox,
  Collapsible,
  CollapsibleContent,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  Input,
  Label,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ScrollArea,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  cn,
} from "@workspace/ui";
import {
  Tabs,
  TabsList,
  TabsTrigger,
} from "@workspace/ui/components/motion/tabs";
import {
  Check,
  ChevronDown,
  CircleDot,
  CloudDownload,
  Ellipsis,
  ExternalLink,
  GitBranch,
  GitPullRequestArrow,
  Loader2,
  LoaderCircle,
  RotateCw,
  Sparkles,
} from "lucide-react";
import { LinearIcon } from "@workspace/ui/components/icons/linear-icon";
import type { GithubIssuePayload, GithubPrPayload } from "@/api/ws-api";
import type { LinearIssuePayload } from "@atmos/api-types/ws/dto/linear";
import {
  isAutoGeneratedBranchConflictError,
  type RepoContext,
} from "@/features/welcome/lib/welcome-page-helpers";

export function WelcomeAdvancedOptions({
  autoExtractDescriptionIssue,
  autoExtractDescriptionPr,
  autoExtractTodos,
  autoExtractTodosPr,
  baseBranch,
  baseBranchFilter,
  branch,
  branchError,
  branchInputRef,
  canAutoExtractTodosIssue,
  canAutoExtractTodosPr,
  displayedLinkType,
  filteredRemoteBranches,
  handleLoadIssueFromUrl,
  handleLoadMoreIssues,
  handleLoadMoreLinear,
  handleLoadMorePrs,
  handleLoadPrFromUrl,
  handleRefreshIssues,
  handleRefreshLinear,
  handleRefreshPrs,
  handleRegenerateBranch,
  handleSelectIssue,
  handleSelectLinear,
  handleSelectLinkType,
  handleSelectPr,
  isAdvancedOpen,
  isBaseBranchesLoading,
  isBaseBranchOpen,
  isIssuePreviewLoading,
  isIssuesLoading,
  isIssuesLoadingMore,
  isLinearLoading,
  isLinearLoadingMore,
  isPrPreviewLoading,
  isPrsLoading,
  isPrsLoadingMore,
  issueError,
  issuePreview,
  issues,
  issuesHasMore,
  issueUrl,
  linearConnected,
  linearError,
  linearHasMore,
  linearIssues,
  linearPreview,
  linkType,
  name,
  onIssueUrlChange,
  onNameChange,
  onBranchChange,
  onPrUrlChange,
  prError,
  prPreview,
  prs,
  prsHasMore,
  prUrl,
  remoteBranches,
  repoContext,
  selectedIssueNumber,
  selectedLinearId,
  selectedPrNumber,
  selectedProjectId,
  setAutoExtractTodos,
  setAutoExtractTodosPr,
  setBaseBranch,
  setBaseBranchFilter,
  setIsAdvancedOpen,
  setIsBaseBranchOpen,
  submitError,
}: {
  autoExtractDescriptionIssue: string;
  autoExtractDescriptionPr: string;
  autoExtractTodos: boolean;
  autoExtractTodosPr: boolean;
  baseBranch: string;
  baseBranchFilter: string;
  branch: string;
  branchError: string | null;
  branchInputRef: React.RefObject<HTMLInputElement | null>;
  canAutoExtractTodosIssue: boolean;
  canAutoExtractTodosPr: boolean;
  displayedLinkType: "issue" | "pr" | "linear";
  filteredRemoteBranches: string[];
  handleLoadIssueFromUrl: () => void | Promise<void>;
  handleLoadMoreIssues: () => void | Promise<void>;
  handleLoadMoreLinear: () => void | Promise<void>;
  handleLoadMorePrs: () => void;
  handleLoadPrFromUrl: () => void | Promise<void>;
  handleRefreshIssues: () => void | Promise<void>;
  handleRefreshLinear: () => void | Promise<void>;
  handleRefreshPrs: () => void | Promise<void>;
  handleRegenerateBranch: () => void;
  handleSelectIssue: (value: string) => void;
  handleSelectLinear: (value: string) => void;
  handleSelectLinkType: (next: "issue" | "pr" | "linear") => void;
  handleSelectPr: (value: string) => void;
  isAdvancedOpen: boolean;
  isBaseBranchesLoading: boolean;
  isBaseBranchOpen: boolean;
  isIssuePreviewLoading: boolean;
  isIssuesLoading: boolean;
  isIssuesLoadingMore: boolean;
  isLinearLoading: boolean;
  isLinearLoadingMore: boolean;
  isPrPreviewLoading: boolean;
  isPrsLoading: boolean;
  isPrsLoadingMore: boolean;
  issueError: string | null;
  issuePreview: GithubIssuePayload | null;
  issues: GithubIssuePayload[];
  issuesHasMore: boolean;
  issueUrl: string;
  linearConnected: boolean;
  linearError: string | null;
  linearHasMore: boolean;
  linearIssues: LinearIssuePayload[];
  linearPreview: LinearIssuePayload | null;
  linkType: "none" | "issue" | "pr" | "linear";
  name: string;
  onIssueUrlChange: (value: string) => void;
  onNameChange: (value: string) => void;
  onBranchChange: (value: string) => void;
  onPrUrlChange: (value: string) => void;
  prError: string | null;
  prPreview: GithubPrPayload | null;
  prs: GithubPrPayload[];
  prsHasMore: boolean;
  prUrl: string;
  remoteBranches: string[];
  repoContext: RepoContext | null;
  selectedIssueNumber: string;
  selectedLinearId: string;
  selectedPrNumber: string;
  selectedProjectId: string | null;
  setAutoExtractTodos: (value: boolean) => void;
  setAutoExtractTodosPr: (value: boolean) => void;
  setBaseBranch: (value: string) => void;
  setBaseBranchFilter: (value: string) => void;
  setIsAdvancedOpen: (value: boolean) => void;
  setIsBaseBranchOpen: (value: boolean) => void;
  submitError: string | null;
}) {
  const t = useTranslations("Welcome.components");
  return (
    <Popover open={isAdvancedOpen} onOpenChange={setIsAdvancedOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          className="inline-flex size-9 items-center justify-center rounded-md border border-border/60 bg-background/35 text-muted-foreground hover:bg-accent hover:text-foreground"
          aria-label={t("advanced.openAria")}
        >
          <Ellipsis className="size-4" />
        </button>
      </PopoverTrigger>
      <PopoverContent
        side="right"
        align="end"
        sideOffset={8}
        collisionPadding={16}
        className="flex w-[min(92vw,760px)] max-w-[760px] flex-col overflow-hidden rounded-[1.5rem] border border-border/60 bg-background p-0 shadow-2xl backdrop-blur-md"
        style={{ maxHeight: "var(--radix-popover-content-available-height)" }}
      >
        <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
          <div className="grid gap-5">
            <div className="grid gap-4 md:grid-cols-2">
              <div className="grid gap-2">
                <Label htmlFor="workspace-name-inline">{t("advanced.fields.name")}</Label>
                <Input
                  id="workspace-name-inline"
                  value={name}
                  onChange={(event) => onNameChange(event.target.value)}
                  placeholder={t("advanced.placeholders.workspaceDisplayName")}
                  className="h-10 bg-muted/35"
                />
              </div>

              <div className="grid gap-2">
                <Label htmlFor="workspace-branch-inline">{t("advanced.fields.currentWorkspaceBranch")}</Label>
                <Input
                  id="workspace-branch-inline"
                  ref={branchInputRef}
                  value={branch}
                  onChange={(event) => onBranchChange(event.target.value)}
                  placeholder={t("advanced.placeholders.workspaceBranch")}
                  className="h-10 bg-muted/35"
                />
                {branchError ? (
                  <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
                    <span>{branchError}</span>
                    {isAutoGeneratedBranchConflictError(branchError) ? (
                      <Button
                        type="button"
                        variant="link"
                        className="ml-1 h-auto p-0 text-xs align-baseline"
                        onClick={handleRegenerateBranch}
                      >
                        {t("advanced.randomGenerateAgain")}
                      </Button>
                    ) : null}
                  </div>
                ) : null}
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="workspace-base-branch-trigger-inline">{t("advanced.fields.baseBranch")}</Label>
              <DropdownMenu
                open={isBaseBranchOpen}
                onOpenChange={(open) => {
                  setIsBaseBranchOpen(open);
                  if (open) setBaseBranchFilter("");
                }}
                modal={false}
              >
                <DropdownMenuTrigger asChild>
                  <button
                    id="workspace-base-branch-trigger-inline"
                    type="button"
                    disabled={isBaseBranchesLoading || remoteBranches.length === 0}
                    className="flex h-11 w-full items-center justify-between rounded-xl border border-border/60 bg-muted/35 px-3 text-sm disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <div className="flex min-w-0 items-center text-muted-foreground">
                      <span className="mr-1 shrink-0 opacity-50">origin/</span>
                      <span className="truncate">{baseBranch}</span>
                    </div>
                    <ChevronDown className="size-4 opacity-50" />
                  </button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="start" className="w-[var(--radix-dropdown-menu-trigger-width)] p-3">
                  <div className="space-y-2">
                    <p className="text-[12px] text-muted-foreground">{t("advanced.selectTargetBranch")}</p>
                    <Input
                      value={baseBranchFilter}
                      onChange={(event) => setBaseBranchFilter(event.target.value)}
                      onKeyDown={(event) => event.stopPropagation()}
                      placeholder={t("advanced.placeholders.searchBranches")}
                      className="h-8 text-[12px]"
                    />
                  </div>
                  <ScrollArea className="mt-2 h-[220px] overflow-x-auto">
                    <div className="p-1">
                      {isBaseBranchesLoading ? (
                        <div className="p-2 text-center text-[12px] text-muted-foreground">
                          {t("advanced.loadingBranches")}
                        </div>
                      ) : filteredRemoteBranches.length > 0 ? (
                        filteredRemoteBranches.map((remoteBranch) => (
                          <DropdownMenuItem
                            key={remoteBranch}
                            onClick={() => setBaseBranch(remoteBranch)}
                            className={cn(
                              "cursor-pointer justify-between whitespace-nowrap text-[13px]",
                              baseBranch === remoteBranch &&
                                "bg-accent text-accent-foreground",
                            )}
                          >
                            <span className="flex items-center">
                              {baseBranch === remoteBranch ? (
                                <Check className="mr-2 size-3.5 text-emerald-500" />
                              ) : (
                                <GitBranch className="mr-2 size-3.5 text-muted-foreground" />
                              )}
                              <span className="mr-1 text-muted-foreground/60">origin/</span>
                              <span>{remoteBranch}</span>
                            </span>
                          </DropdownMenuItem>
                        ))
                      ) : (
                        <div className="p-2 text-center text-[12px] text-muted-foreground">
                          {t("advanced.noMatchingBranches")}
                        </div>
                      )}
                    </div>
                  </ScrollArea>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>

            <div className="rounded-2xl border border-border/60 bg-background/35">
              <div className="flex items-center gap-1.5 p-1.5">
                <Tabs
                  value={linkType === "none" ? "none" : linkType}
                  onValueChange={(next) => {
                    if (next === "issue" || next === "pr" || next === "linear") {
                      handleSelectLinkType(next);
                    }
                  }}
                  variant="pill"
                  className="min-w-0 flex-1"
                >
                  <TabsList className="h-8 w-full gap-0.5 p-0.5">
                    <TabsTrigger
                      value="issue"
                      className={cn(
                        "h-7 min-w-0 flex-1 gap-1.5 px-2 text-xs sm:px-3",
                        issuePreview && linkType !== "issue" && "ring-1 ring-primary/35",
                      )}
                    >
                      <CircleDot className="size-3.5 shrink-0" />
                      <span className="truncate">{t("advanced.githubIssue")}</span>
                    </TabsTrigger>
                    <TabsTrigger
                      value="pr"
                      className={cn(
                        "h-7 min-w-0 flex-1 gap-1.5 px-2 text-xs sm:px-3",
                        prPreview && linkType !== "pr" && "ring-1 ring-primary/35",
                      )}
                    >
                      <GitPullRequestArrow className="size-3.5 shrink-0" />
                      <span className="truncate">{t("advanced.githubPr")}</span>
                    </TabsTrigger>
                    <TabsTrigger
                      value="linear"
                      className={cn(
                        "h-7 min-w-0 flex-1 gap-1.5 px-2 text-xs sm:px-3",
                        linearPreview && linkType !== "linear" && "ring-1 ring-primary/35",
                      )}
                    >
                      <LinearIcon className="size-3.5 shrink-0" size={14} />
                      <span className="truncate">{t("advanced.linearIssue")}</span>
                    </TabsTrigger>
                  </TabsList>
                </Tabs>
                {repoContext && linkType === "issue" ? (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-8 shrink-0"
                    onClick={() => void handleRefreshIssues()}
                    disabled={isIssuesLoading}
                    title={t("advanced.refreshIssues")}
                  >
                    {isIssuesLoading ? <LoaderCircle className="size-4 animate-spin" /> : <RotateCw className="size-4" />}
                  </Button>
                ) : repoContext && linkType === "pr" ? (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-8 shrink-0"
                    onClick={() => void handleRefreshPrs()}
                    disabled={isPrsLoading}
                    title={t("advanced.refreshPrs")}
                  >
                    {isPrsLoading ? <LoaderCircle className="size-4 animate-spin" /> : <RotateCw className="size-4" />}
                  </Button>
                ) : linkType === "linear" ? (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="size-8 shrink-0"
                    onClick={() => void handleRefreshLinear()}
                    disabled={isLinearLoading}
                    title={t("advanced.refreshLinear")}
                  >
                    {isLinearLoading ? <LoaderCircle className="size-4 animate-spin" /> : <RotateCw className="size-4" />}
                  </Button>
                ) : null}
              </div>

              <Collapsible open={linkType !== "none"}>
                <CollapsibleContent>
                  {displayedLinkType === "issue" ? (
                    <IssueLinkPanel
                      autoExtractDescription={autoExtractDescriptionIssue}
                      autoExtractTodos={autoExtractTodos}
                      canAutoExtractTodos={canAutoExtractTodosIssue}
                      handleLoadIssueFromUrl={handleLoadIssueFromUrl}
                      handleLoadMoreIssues={handleLoadMoreIssues}
                      handleSelectIssue={handleSelectIssue}
                      isIssuePreviewLoading={isIssuePreviewLoading}
                      isIssuesLoading={isIssuesLoading}
                      isIssuesLoadingMore={isIssuesLoadingMore}
                      issueError={issueError}
                      issuePreview={issuePreview}
                      issues={issues}
                      issuesHasMore={issuesHasMore}
                      issueUrl={issueUrl}
                      onIssueUrlChange={onIssueUrlChange}
                      repoContext={repoContext}
                      selectedIssueNumber={selectedIssueNumber}
                      selectedProjectId={selectedProjectId}
                      setAutoExtractTodos={setAutoExtractTodos}
                    />
                  ) : null}

                  {displayedLinkType === "pr" ? (
                    <PrLinkPanel
                      autoExtractDescription={autoExtractDescriptionPr}
                      autoExtractTodos={autoExtractTodosPr}
                      canAutoExtractTodos={canAutoExtractTodosPr}
                      handleLoadMorePrs={handleLoadMorePrs}
                      handleLoadPrFromUrl={handleLoadPrFromUrl}
                      handleSelectPr={handleSelectPr}
                      isPrPreviewLoading={isPrPreviewLoading}
                      isPrsLoading={isPrsLoading}
                      isPrsLoadingMore={isPrsLoadingMore}
                      onPrUrlChange={onPrUrlChange}
                      prError={prError}
                      prPreview={prPreview}
                      prs={prs}
                      prsHasMore={prsHasMore}
                      prUrl={prUrl}
                      repoContext={repoContext}
                      selectedPrNumber={selectedPrNumber}
                      selectedProjectId={selectedProjectId}
                      setAutoExtractTodos={setAutoExtractTodosPr}
                    />
                  ) : null}

                  {displayedLinkType === "linear" ? (
                    <LinearLinkPanel
                      handleLoadMoreLinear={handleLoadMoreLinear}
                      handleSelectLinear={handleSelectLinear}
                      isLinearLoading={isLinearLoading}
                      isLinearLoadingMore={isLinearLoadingMore}
                      linearConnected={linearConnected}
                      linearError={linearError}
                      linearHasMore={linearHasMore}
                      linearIssues={linearIssues}
                      linearPreview={linearPreview}
                      selectedLinearId={selectedLinearId}
                    />
                  ) : null}
                </CollapsibleContent>
              </Collapsible>
            </div>

            {submitError ? (
              <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
                {submitError}
              </div>
            ) : null}
          </div>
        </div>
      </PopoverContent>
    </Popover>
  );
}

function SelectLoadMoreFooter({
  hasMore,
  loading,
  onLoadMore,
  label,
  loadingLabel,
}: {
  hasMore: boolean;
  loading: boolean;
  onLoadMore: () => void;
  label: string;
  loadingLabel: string;
}) {
  if (!hasMore) return null;
  return (
    <div
      className="sticky bottom-0 z-10 border-t border-border/60 bg-popover px-2 py-1.5"
      onPointerDown={(event) => event.preventDefault()}
    >
      <button
        type="button"
        className="flex w-full items-center justify-center gap-1.5 rounded-md px-2 py-1.5 text-xs font-medium text-muted-foreground hover:bg-muted hover:text-foreground disabled:opacity-60"
        disabled={loading}
        onClick={(event) => {
          event.preventDefault();
          event.stopPropagation();
          onLoadMore();
        }}
      >
        {loading ? <Loader2 className="size-3.5 animate-spin" /> : null}
        {loading ? loadingLabel : label}
      </button>
    </div>
  );
}

function IssueLinkPanel({
  autoExtractDescription,
  autoExtractTodos,
  canAutoExtractTodos,
  handleLoadIssueFromUrl,
  handleLoadMoreIssues,
  handleSelectIssue,
  isIssuePreviewLoading,
  isIssuesLoading,
  isIssuesLoadingMore,
  issueError,
  issuePreview,
  issues,
  issuesHasMore,
  issueUrl,
  onIssueUrlChange,
  repoContext,
  selectedIssueNumber,
  selectedProjectId,
  setAutoExtractTodos,
}: {
  autoExtractDescription: string;
  autoExtractTodos: boolean;
  canAutoExtractTodos: boolean;
  handleLoadIssueFromUrl: () => void | Promise<void>;
  handleLoadMoreIssues: () => void | Promise<void>;
  handleSelectIssue: (value: string) => void;
  isIssuePreviewLoading: boolean;
  isIssuesLoading: boolean;
  isIssuesLoadingMore: boolean;
  issueError: string | null;
  issuePreview: GithubIssuePayload | null;
  issues: GithubIssuePayload[];
  issuesHasMore: boolean;
  issueUrl: string;
  onIssueUrlChange: (value: string) => void;
  repoContext: RepoContext | null;
  selectedIssueNumber: string;
  selectedProjectId: string | null;
  setAutoExtractTodos: (value: boolean) => void;
}) {
  const t = useTranslations("Welcome.components");
  return (
    <div className="border-t border-border/60 p-4">
      <div className="space-y-4">
        {repoContext ? (
          <div className="grid min-w-0 gap-4 md:grid-cols-[minmax(0,1fr)_auto]">
            <div className="grid min-w-0 gap-2">
              <Label htmlFor="issue-select-inline">{t("advanced.issue.selectFromRepository")}</Label>
              <Select
                value={selectedIssueNumber}
                onValueChange={handleSelectIssue}
                disabled={!isIssuesLoading && issues.length === 0}
              >
                <SelectTrigger
                  id="issue-select-inline"
                  className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
                >
                  <SelectValue
                    placeholder={
                      isIssuesLoading
                        ? t("advanced.issue.loadingIssues")
                        : issues.length === 0
                          ? t("advanced.issue.noIssuesAvailable")
                          : t("advanced.issue.selectIssue")
                    }
                  />
                </SelectTrigger>
                <SelectContent className="max-h-80">
                  {issues.length === 0 ? (
                    <div className="px-2 py-1.5 text-xs text-muted-foreground">
                      {t("advanced.issue.noGithubIssuesFound")}
                    </div>
                  ) : (
                    issues.map((issue) => (
                      <SelectItem key={issue.number} value={String(issue.number)}>
                        <div className="flex min-w-0 items-center gap-2">
                          <span className="font-mono text-xs text-muted-foreground">
                            #{issue.number}
                          </span>
                          <span className="truncate">{issue.title}</span>
                        </div>
                      </SelectItem>
                    ))
                  )}
                  <SelectLoadMoreFooter
                    hasMore={issuesHasMore}
                    loading={isIssuesLoadingMore}
                    onLoadMore={() => void handleLoadMoreIssues()}
                    label={t("advanced.loadMore")}
                    loadingLabel={t("advanced.loadingMore")}
                  />
                </SelectContent>
              </Select>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="issue-url-inline">{t("advanced.issue.pasteIssueUrl")}</Label>
              <div className="flex gap-2">
                <Input
                  id="issue-url-inline"
                  value={issueUrl}
                  onChange={(event) => onIssueUrlChange(event.target.value)}
                  placeholder={t("advanced.issue.issueUrlPlaceholder", { owner: repoContext.owner, repo: repoContext.repo })}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => void handleLoadIssueFromUrl()}
                  disabled={isIssuePreviewLoading || !issueUrl.trim()}
                  title={t("advanced.issue.loadIssue")}
                >
                  {isIssuePreviewLoading ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <CloudDownload className="size-4" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        ) : selectedProjectId ? (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            {t("advanced.issue.projectNoGithubRemote")}
          </div>
        ) : (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            {t("advanced.issue.selectProjectFirst")}
          </div>
        )}

        {issueError ? (
          <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
            {issueError}
          </div>
        ) : null}

        {isIssuePreviewLoading ? (
          <div className="flex items-center gap-2 rounded-xl border border-border/70 px-3 py-4 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            {t("advanced.issue.loadingIssuePreview")}
          </div>
        ) : issuePreview ? (
          <GithubPreviewCard
            bodyFallback={t("advanced.issue.noIssueDescription")}
            labels={issuePreview.labels}
            owner={issuePreview.owner}
            repo={issuePreview.repo}
            number={issuePreview.number}
            state={issuePreview.state}
            title={issuePreview.title}
            url={issuePreview.url}
            body={issuePreview.body}
          />
        ) : null}

        <AutoExtractTodosCheckbox
          checked={autoExtractTodos}
          description={autoExtractDescription}
          disabled={!canAutoExtractTodos}
          onChange={setAutoExtractTodos}
        />
      </div>
    </div>
  );
}

function PrLinkPanel({
  autoExtractDescription,
  autoExtractTodos,
  canAutoExtractTodos,
  handleLoadMorePrs,
  handleLoadPrFromUrl,
  handleSelectPr,
  isPrPreviewLoading,
  isPrsLoading,
  isPrsLoadingMore,
  onPrUrlChange,
  prError,
  prPreview,
  prs,
  prsHasMore,
  prUrl,
  repoContext,
  selectedPrNumber,
  selectedProjectId,
  setAutoExtractTodos,
}: {
  autoExtractDescription: string;
  autoExtractTodos: boolean;
  canAutoExtractTodos: boolean;
  handleLoadMorePrs: () => void;
  handleLoadPrFromUrl: () => void | Promise<void>;
  handleSelectPr: (value: string) => void;
  isPrPreviewLoading: boolean;
  isPrsLoading: boolean;
  isPrsLoadingMore: boolean;
  onPrUrlChange: (value: string) => void;
  prError: string | null;
  prPreview: GithubPrPayload | null;
  prs: GithubPrPayload[];
  prsHasMore: boolean;
  prUrl: string;
  repoContext: RepoContext | null;
  selectedPrNumber: string;
  selectedProjectId: string | null;
  setAutoExtractTodos: (value: boolean) => void;
}) {
  const t = useTranslations("Welcome.components");
  return (
    <div className="border-t border-border/60 p-4">
      <div className="space-y-4">
        {repoContext ? (
          <div className="grid min-w-0 gap-4 md:grid-cols-[minmax(0,1fr)_auto]">
            <div className="grid min-w-0 gap-2">
              <Label htmlFor="pr-select-inline">{t("advanced.pr.selectFromRepository")}</Label>
              <Select
                value={selectedPrNumber}
                onValueChange={handleSelectPr}
                disabled={!isPrsLoading && prs.length === 0}
              >
                <SelectTrigger
                  id="pr-select-inline"
                  className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
                >
                  <SelectValue
                    placeholder={
                      isPrsLoading
                        ? t("advanced.pr.loadingPrs")
                        : prs.length === 0
                          ? t("advanced.pr.noPrsAvailable")
                          : t("advanced.pr.selectPr")
                    }
                  />
                </SelectTrigger>
                <SelectContent className="max-h-80">
                  {prs.length === 0 ? (
                    <div className="px-2 py-1.5 text-xs text-muted-foreground">
                      {t("advanced.pr.noGithubPrsFound")}
                    </div>
                  ) : (
                    prs.map((pr) => (
                      <SelectItem key={pr.number} value={String(pr.number)}>
                        <div className="flex min-w-0 items-center gap-2">
                          <span className="font-mono text-xs text-muted-foreground">
                            #{pr.number}
                          </span>
                          <span className="truncate">{pr.title}</span>
                        </div>
                      </SelectItem>
                    ))
                  )}
                  <SelectLoadMoreFooter
                    hasMore={prsHasMore}
                    loading={isPrsLoadingMore}
                    onLoadMore={handleLoadMorePrs}
                    label={t("advanced.loadMore")}
                    loadingLabel={t("advanced.loadingMore")}
                  />
                </SelectContent>
              </Select>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="pr-url-inline">{t("advanced.pr.pastePrUrl")}</Label>
              <div className="flex gap-2">
                <Input
                  id="pr-url-inline"
                  value={prUrl}
                  onChange={(event) => onPrUrlChange(event.target.value)}
                  placeholder={t("advanced.pr.prUrlPlaceholder", { owner: repoContext.owner, repo: repoContext.repo })}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => void handleLoadPrFromUrl()}
                  disabled={isPrPreviewLoading || !prUrl.trim()}
                  title={t("advanced.pr.loadPr")}
                >
                  {isPrPreviewLoading ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <CloudDownload className="size-4" />
                  )}
                </Button>
              </div>
            </div>
          </div>
        ) : selectedProjectId ? (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            {t("advanced.pr.projectNoGithubRemote")}
          </div>
        ) : (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            {t("advanced.pr.selectProjectFirst")}
          </div>
        )}

        {prError ? (
          <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
            {prError}
          </div>
        ) : null}

        {isPrPreviewLoading ? (
          <div className="flex items-center gap-2 rounded-xl border border-border/70 px-3 py-4 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            {t("advanced.pr.loadingPrPreview")}
          </div>
        ) : prPreview ? (
          <GithubPreviewCard
            bodyFallback={t("advanced.pr.noPrDescription")}
            labels={prPreview.labels}
            owner={prPreview.owner}
            repo={prPreview.repo}
            number={prPreview.number}
            state={prPreview.is_draft ? "draft" : prPreview.state}
            title={prPreview.title}
            url={prPreview.url}
            body={prPreview.body}
            branchMeta={
              <>
                <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
                  <span className="inline-flex items-center gap-1">
                    <GitBranch className="size-3" />
                    {prPreview.head_ref}
                  </span>
                  <span className="opacity-50">→</span>
                  <span className="inline-flex items-center gap-1">
                    <GitBranch className="size-3" />
                    {prPreview.base_ref}
                  </span>
                </div>
                <div className="rounded-md border border-border/70 bg-background/40 px-3 py-2 text-[11px] text-muted-foreground">
                  {t.rich("advanced.pr.reuseBranchNotice", {
                    branch: prPreview.head_ref,
                    mono: (chunks) => <span className="font-mono text-foreground">{chunks}</span>,
                  })}
                </div>
              </>
            }
          />
        ) : null}

        <AutoExtractTodosCheckbox
          checked={autoExtractTodos}
          description={autoExtractDescription}
          disabled={!canAutoExtractTodos}
          onChange={setAutoExtractTodos}
        />
      </div>
    </div>
  );
}

function LinearLinkPanel({
  handleLoadMoreLinear,
  handleSelectLinear,
  isLinearLoading,
  isLinearLoadingMore,
  linearConnected,
  linearError,
  linearHasMore,
  linearIssues,
  linearPreview,
  selectedLinearId,
}: {
  handleLoadMoreLinear: () => void | Promise<void>;
  handleSelectLinear: (value: string) => void;
  isLinearLoading: boolean;
  isLinearLoadingMore: boolean;
  linearConnected: boolean;
  linearError: string | null;
  linearHasMore: boolean;
  linearIssues: LinearIssuePayload[];
  linearPreview: LinearIssuePayload | null;
  selectedLinearId: string;
}) {
  const t = useTranslations("Welcome.components");
  return (
    <div className="border-t border-border/60 p-4">
      <div className="space-y-4">
        {!linearConnected && !isLinearLoading ? (
          <div className="rounded-xl border border-dashed border-border/70 px-3 py-4 text-sm text-muted-foreground">
            {t("advanced.linear.notConnected")}
          </div>
        ) : (
          <div className="grid min-w-0 gap-2">
            <Label htmlFor="linear-select-inline">
              {t("advanced.linear.selectIssue")}
            </Label>
            <Select
              value={selectedLinearId}
              onValueChange={handleSelectLinear}
              disabled={!isLinearLoading && linearIssues.length === 0}
            >
              <SelectTrigger
                id="linear-select-inline"
                className="w-full min-w-0 [&>span]:flex [&>span]:min-w-0 [&>span]:flex-1 [&>span]:truncate"
              >
                <SelectValue
                  placeholder={
                    isLinearLoading
                      ? t("advanced.linear.loadingIssues")
                      : linearIssues.length === 0
                        ? t("advanced.linear.noIssuesAvailable")
                        : t("advanced.linear.selectIssuePlaceholder")
                  }
                />
              </SelectTrigger>
              <SelectContent className="max-h-80">
                {linearIssues.length === 0 ? (
                  <div className="px-2 py-1.5 text-xs text-muted-foreground">
                    {t("advanced.linear.noOpenIssues")}
                  </div>
                ) : (
                  linearIssues.map((issue) => (
                    <SelectItem key={issue.id} value={issue.id}>
                      <div className="flex min-w-0 items-center gap-2">
                        <span className="font-mono text-xs text-muted-foreground">
                          {issue.identifier}
                        </span>
                        <span className="truncate">{issue.title}</span>
                      </div>
                    </SelectItem>
                  ))
                )}
                <SelectLoadMoreFooter
                  hasMore={linearHasMore}
                  loading={isLinearLoadingMore}
                  onLoadMore={() => void handleLoadMoreLinear()}
                  label={t("advanced.loadMore")}
                  loadingLabel={t("advanced.loadingMore")}
                />
              </SelectContent>
            </Select>
            <p className="text-[11px] text-muted-foreground">
              {t("advanced.linear.openOnlyHint")}
            </p>
          </div>
        )}

        {linearError ? (
          <div className="rounded-xl border border-destructive/30 bg-destructive/8 px-3 py-2 text-xs text-destructive">
            {linearError}
          </div>
        ) : null}

        {isLinearLoading && !linearPreview ? (
          <div className="flex items-center gap-2 rounded-xl border border-border/70 px-3 py-4 text-sm text-muted-foreground">
            <Loader2 className="size-4 animate-spin" />
            {t("advanced.linear.loadingIssues")}
          </div>
        ) : linearPreview ? (
          <Card className="rounded-xl border border-border/70 bg-muted/20 shadow-none">
            <CardContent className="space-y-3 p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <LinearIcon className="size-3.5 text-muted-foreground" size={14} />
                    <span className="font-mono text-xs text-muted-foreground">
                      {linearPreview.identifier}
                    </span>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="h-6 gap-1 rounded-md px-2 text-[11px]"
                      onClick={() =>
                        window.open(linearPreview.url, "_blank", "noopener,noreferrer")
                      }
                    >
                      <ExternalLink className="size-3" />
                      {t("advanced.preview.openOnLinear")}
                    </Button>
                  </div>
                  <h3 className="mt-1 truncate text-sm font-medium text-foreground">
                    {linearPreview.title}
                  </h3>
                </div>
                {linearPreview.state_name ? (
                  <Badge variant="secondary" className="rounded-full">
                    {linearPreview.state_name}
                  </Badge>
                ) : null}
              </div>
              {linearPreview.description ? (
                <p className="line-clamp-4 whitespace-pre-wrap text-xs text-muted-foreground">
                  {linearPreview.description}
                </p>
              ) : (
                <p className="text-xs text-muted-foreground">
                  {t("advanced.linear.noDescription")}
                </p>
              )}
            </CardContent>
          </Card>
        ) : null}
      </div>
    </div>
  );
}

function GithubPreviewCard({
  body,
  bodyFallback,
  branchMeta,
  labels,
  number,
  owner,
  repo,
  state,
  title,
  url,
}: {
  body: string | null;
  bodyFallback: string;
  branchMeta?: React.ReactNode;
  labels: Array<{ name: string }>;
  number: number;
  owner: string;
  repo: string;
  state: string;
  title: string;
  url: string;
}) {
  const t = useTranslations("Welcome.components");
  return (
    <Card className="rounded-xl border border-border/70 bg-muted/20 shadow-none">
      <CardContent className="space-y-3 p-4">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground">
                {owner}/{repo}#{number}
              </span>
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="h-6 gap-1 rounded-md px-2 text-[11px]"
                onClick={() => window.open(url, "_blank", "noopener,noreferrer")}
              >
                <ExternalLink className="size-3" />
                {t("advanced.preview.openOnGithub")}
              </Button>
            </div>
            <h3 className="mt-1 truncate text-sm font-medium text-foreground">
              {title}
            </h3>
            {branchMeta}
          </div>
          <Badge variant="secondary" className="rounded-full capitalize">
            {state}
          </Badge>
        </div>

        {labels.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {labels.map((label) => (
              <Badge key={label.name} variant="outline" className="rounded-full">
                {label.name}
              </Badge>
            ))}
          </div>
        ) : null}

        <p className="line-clamp-6 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">
          {body?.trim() || bodyFallback}
        </p>
      </CardContent>
    </Card>
  );
}

function AutoExtractTodosCheckbox({
  checked,
  description,
  disabled,
  onChange,
}: {
  checked: boolean;
  description: string;
  disabled: boolean;
  onChange: (value: boolean) => void;
}) {
  const t = useTranslations("Welcome.components");
  return (
    <label className="flex items-center gap-3 rounded-xl border border-border/70 px-3 py-3 text-sm">
      <Checkbox
        checked={checked}
        onCheckedChange={(nextChecked) => onChange(Boolean(nextChecked))}
        disabled={disabled}
      />
      <div className="min-w-0">
        <div className="flex items-center gap-2 font-medium text-foreground">
          <Sparkles className="size-4 text-muted-foreground" />
          {t("advanced.autoExtractTodos")}
        </div>
        <p className="mt-1 text-xs text-muted-foreground">
          {description}
        </p>
      </div>
    </label>
  );
}
