export {
  MARKDOWN_TABLE_CLASS,
  MARKDOWN_TABLE_HEAD_CLASS,
  MARKDOWN_TABLE_ROW_CLASS,
  MARKDOWN_TABLE_TD_CLASS,
  MARKDOWN_TABLE_TH_CLASS,
  MARKDOWN_TABLE_WRAP_CLASS,
} from "@workspace/ui/lib/markdown-table";
